Communitheme/gtk-3.0/_colors.scss
Communitheme/gtk-3.0/_common.scss
Communitheme/gtk-3.0/_drawing.scss
Communitheme/gtk-3.0/_ubuntu-colors.scss
Communitheme/gtk-3.0/gtk-dark.scss
Communitheme/gtk-3.0/gtk.scss

flatten the theme by removing gradients and shadows
dark headerbar (transparent unless maximized)
use of ubuntu touch/suru colors

initial changes based on mockups

---

Communitheme/gtk-3.0/_apps.scss
Communitheme/gtk-3.0/_colors.scss
Communitheme/gtk-3.0/_common.scss
Communitheme/gtk-3.0/_drawing.scss

Updated each element to look more like Suru's. Closes issue #14
More can be seen here: [scrollbars](https://docs.ubuntu.com/phone/en/apps/design/building-blocks/scrolling), [switches, checks, etc.](https://docs.ubuntu.com/phone/en/apps/design/building-blocks/selection-controls).

Update checkbox, radio, switch, spinner & scrollbar to resemble Suru's

---

Communitheme/gtk-3.0/_apps.scss
Communitheme/gtk-3.0/_common.scss

- Temp fix for #43
- Selected stackswitchers used the wrong text color

Remove tint for selected Nautilus icons and fix stackswitcher

---

.travis.yml

Ensure any PR is checked for building in the current ubuntu archive.

Add CI to build every PR

---

.travis.yml

* Change url to upstream url now that the changes are upstream
* Added there autodetection of the derivative, so simplify by removing some
env variables.

Move to travis.debian.net

---

Communitheme/gtk-3.0/_common.scss

Reduced from 22px to 20px
closes #78

Reduced window control backround size

---

Communitheme/gtk-3.0/_ubuntu-colors.scss

Changed from #292929 to #101 
closes #101

Changed headerbar bg color

---

Communitheme/gtk-3.0/_common.scss

Fixed missing black underline on first/last child in stackswitcher

---

Communitheme/gtk-3.0/_common.scss

- Uses inkstone for maximized windows

Separator for maximized windows

---

Communitheme/gtk-3.0/_common.scss

- Make (actual) min-height: 32px
- Make (actual) padding: 0 8px
Closes #140

Reduce tooltip size

---

Communitheme/gtk-3.0/_common.scss

Reduced by 1px to make it more elegant and clean
closes #113

Reduced scale's slider thickness in fine-tune mode

---

Communitheme/gtk-3.0/_common.scss
Communitheme/gtk-3.0/_drawing.scss

Implemented button design rules on dark

---

Communitheme/gtk-3.0/_common.scss

Implemented transparent switch

---

Communitheme/gtk-3.0/_common.scss

Removed hover effect from sidebar active row

---

Communitheme/gtk-3.0/_common.scss

Increased underlined focus effect to 2px

---

Communitheme/gtk-3.0/_common.scss

Removes hover effects when a window is in backdrop

No sidebar hover when in backdrop state

---

Communitheme/gtk-3.0/_common.scss

Rounded focus rectangles

---

Communitheme/gtk-3.0/_colors.scss
Communitheme/gtk-3.0/_common.scss

- Make the transition more smoother
- Use `rgba()` colors instead of `opacity` for more smoother transition
- Adjust scrollbar position/size

Improve scrollbars

---

Communitheme/gtk-3.0/_common.scss

- Decreases element padding so buttons are smaller
Closes issue #85

Decrease element padding

---

Communitheme/gtk-3.0/_common.scss
Communitheme/gtk-3.0/_drawing.scss

- Uses 500 as the Ubuntu font is already a little wide
Closes issue #127

Make title fonts bolder (font-weight: 500)

---

Communitheme/gtk-3.0/_apps.scss

- Workaround for issue #43
- It was under the wrong class name

Reduces nautilus' folder highlight effect in iconview

---

Communitheme/gtk-3.0/_common.scss

Let dark variant use the same backdrop border color as the light one

---

Communitheme/gtk-3.0/_common.scss
Communitheme/gtk-3.0/_drawing.scss

Applied Canonical design to checkbox and radiobutton

---

Communitheme/gtk-3.0/_common.scss

Reverted outline-offset to -3px

---

Communitheme/gtk-3.0/_ubuntu-colors.scss

Reverted terminal background and text color to classic Ubuntu

---

Communitheme/gtk-3.0/_common.scss

Made message dialog more similar to interactive dialog

---

Communitheme/gtk-3.0/_common.scss

Fixed invisible bottom corners in message dialog

---

Communitheme/gtk-3.0/_apps.scss

Separate reviews in Software as boxes

---

Communitheme/gtk-3.0/_common.scss

Make separators in view distinguishable

---

Communitheme/gtk-3.0/_common.scss

Fixed non-csd blurry windows

---

Communitheme/gtk-3.0/_colors.scss
Communitheme/gtk-3.0/_common.scss
Communitheme/gtk-3.0/_drawing.scss

Closes issue #156 
Closes issue #157

Use $fg_color for entry fields, inactive tabs use $text_color

---

Communitheme/gtk-3.0/_apps.scss

Fixed terminal headerbar hover

---

Communitheme/gtk-3.0/_colors.scss
Communitheme/gtk-3.0/_common.scss
Communitheme/gtk-3.0/_drawing.scss

- added 10% darker borders on button in light variant
- fixed spinner hover effect in dark variant

Fixed new brighter button style

---

Communitheme/gtk-3.0/_common.scss

- Decrease image button left and right padding to make image-buttons 1:1 after previous size adjustment
- Decrease entry field height to match button height

Decrease entry field height and image button padding

---

Communitheme/gtk-3.0/_common.scss

Made button margins more uniform in modaldialogs

---

Communitheme/gtk-3.0/_common.scss

Display headerbar in printer config correctly

---

.travis.yml
debian/changelog
debian/control

Change as well gtk2 dep with the version in bionic as libadwaita has moved packages.

Switch to bionic

---

Communitheme/gtk-3.0/_common.scss

Removed hover effect on active notebook tab

---

Communitheme/gtk-3.0/_colors.scss
Communitheme/gtk-3.0/_common.scss
Communitheme/gtk-3.0/_drawing.scss

Made entry colors in headerbar as with pathbar

---

Communitheme/gtk-3.0/_drawing.scss

Entry field has a sunken look using box-shadow. Focused entry field has a soft orange glow.

Sunken entry with orange glow on focus

---

Communitheme/gtk-3.0/_colors.scss
Communitheme/gtk-3.0/_common.scss
Communitheme/gtk-3.0/_drawing.scss

- Rework buttons
- Add `outline-offset: -3px` to buttons
- Return button hilight

Rework buttons

---

Communitheme/gtk-3.0/_common.scss

Replaced none with transparent to fix error parsing

---

Communitheme/gtk-3.0/_drawing.scss

On dark backgrounds, hover hightlight increased +10%
closes #250

Increased button hover brightness

---

Communitheme/gtk-3.0/_common.scss

Fix backdrop dark text color on headerbar

---

Communitheme/gtk-3.0/_common.scss

See #183
This PR also fixes the wrong icon source of arrows in menu.

Make the menu corners round

---

.travis.yml
README.md

Change README to follow new install instructions.

Build snap version for each commits and PR

---

Communitheme/gtk-3.0/_common.scss

Implementation of https://github.com/ubuntu/gtk-communitheme/issues/319
@clobrano please review, old code is commented

red close button only on hover and pressed

---

Communitheme/gtk-3.0/_common.scss

Remove color inversion on selected checkboxes and radios

---

Communitheme/gtk-3.0/_common.scss

Uses the light style as seen in #309.
Still up for discussion, so if it doesn't get merged :man_shrugging:

Light app notifications

---

Communitheme/gtk-3.0/_colors.scss
Communitheme/gtk-3.0/_common.scss
Communitheme/gtk-3.0/_drawing.scss

- Make the background a little bit darker
- Restyle buttons
- Fix excessively long transition of buttons
- Remove inner box-shadow of entries
- Fix button/entry sizing
- Fix frame border-color
See #288
Closes #278

Restyle buttons

---

Communitheme/gtk-3.0/_drawing.scss

Remove entry field glow

---

Communitheme/gtk-3.0/_common.scss

Use orange strip for selected sidebar rows

---

Communitheme/gtk-3.0/_common.scss

Use insensitive_borders_color for disabled menu checks and radios

---

Communitheme/gtk-3.0/_colors.scss
Communitheme/gtk-3.0/_common.scss
Communitheme/gtk-3.0/_drawing.scss

Review of:
- label colors for button and entries in backdrop (inactive) state
- spinbutton (horizontal) increase/decrease button
- check/radio button
Before
After

Fix backdrop state (attempt #2)

---

Communitheme/gtk-3.0/_common.scss

A solution to https://github.com/ubuntu/gnome-shell-communitheme/issues/98

slider_border-radius_10px

---

Communitheme/gtk-3.0/_drawing.scss

This commit gives success and destructive button a darker background
when in insensitive state
closes #152

Added insensitive state to special buttons

---

Communitheme/gtk-3.0/_common.scss

This change completes https://github.com/ubuntu/gnome-shell-communitheme/pull/125

Added window vertical border in maximized state

---

Communitheme/gtk-3.0/_common.scss

Use $base_hover_color for selected treeview rows

---

Communitheme/gtk-3.0/_common.scss

Reverts ubuntu/gtk-communitheme#372

Revert "Use $base_hover_color for selected treeview rows"

---

Communitheme/gtk-3.0/_common.scss

Add bg color to selected list row

---

Communitheme/gtk-3.0/_common.scss

Fixing this https://github.com/ubuntu/gtk-communitheme/issues/383:
Looks good @madsrh ?

Enhance_installation_colors_in_software

---

Communitheme/gtk-3.0/_common.scss
Communitheme/gtk-3.0/_ubuntu-colors.scss

- removed bottom border from headerbar/titlebar
- use headerbar bg color for menubar
- added side borders to menubar
closes #391

Connect menubar with headerbar/titlebar

---

Communitheme/gtk-3.0/_drawing.scss

Fixes a regression introduced with #384.
see also #397

Fixed missing hover effect to normal check/radio

---

Communitheme/gtk-3.0/_common.scss
Communitheme/gtk-3.0/_drawing.scss

Switch in button style

---

Communitheme/gtk-3.0/_common.scss
Communitheme/gtk-3.0/_drawing.scss

Save dialog enhancement

---

Communitheme/gtk-3.0/_apps.scss
Communitheme/gtk-3.0/_common.scss

Made overlay-indicator (scrollbar) transparent and borderless

---

Communitheme/gtk-3.0/_common.scss

Closes https://github.com/ubuntu/gtk-communitheme/issues/413

style_appmenu_button_in_headerbar

---

Communitheme/gtk-3.0/_drawing.scss

Fixed missing semicolon

---

Communitheme/gtk-3.0/_common.scss

Fixes https://github.com/ubuntu/gtk-communitheme/issues/369#issuecomment-387534007

Fix_backdrop_active

---

Communitheme/gtk-3.0/_apps.scss

Removed nautilus canvas top padding

---

Communitheme/gtk-3.0/_ubuntu-colors.scss

Made headerbar backdrop color brighter to improve distinction from active headerbar

Made headerbar backdrop color brighter

---

Communitheme/gtk-2.0/gtkrc

This PR updates #392 giving menubar bg color #2B2929

Updated bg menubar color

---

Communitheme/gtk-3.0/_common.scss
Communitheme/gtk-3.0/_drawing.scss

- removed unnecessary lines in common
- added the new design to the draw circle mixin
- this fixes a small black circle delay -> Closes https://github.com/ubuntu/gtk-communitheme/issues/402
@clobrano correct me if I am wrong =) because you opened the issue before the "newer" design

Moved_logic_back_to_the_draw_circle_mixin

---

Communitheme/gtk-3.0/_common.scss

Fixed shift in headerbar when click on app-menu

---

Communitheme/gtk-3.0/_common.scss
Communitheme/gtk-3.0/_drawing.scss

- made headerbar disabled switch more visible when in normal and backdrop state
- minor adjustments to the enabled switch
closes #446

Adjusted headerbar disabled switch

---

Communitheme/gtk-3.0/_common.scss
Communitheme/gtk-3.0/_drawing.scss

Also use blue instead of purple for some prompts:

Infobar buttons

---

Communitheme/gtk-3.0/_common.scss
Communitheme/gtk-3.0/_drawing.scss

Added pressed effect on checked non-flat buttons

---

Communitheme/gtk-3.0/_common.scss

Restore treeview background color, add transition to switch

---

Communitheme/gtk-3.0/_common.scss

Fixed Firefox menu border issue

Fixed Firefox menu border issue

---

Communitheme/gtk-3.0/_common.scss

Seen [here](https://github.com/ubuntu/gtk-communitheme/pull/389#issuecomment-391880002)

Use plain buttons for infobar

---

Communitheme/gtk-3.0/_drawing.scss

Adds a very slight shadow based on the button shadow to entries

Entry top shadow

---

Communitheme/gtk-3.0/_colors.scss
Communitheme/gtk-3.0/_common.scss

Discussed with @madsrh 
Is this okay for you @clobrano ?

use_shadow_variables

---

Communitheme/gtk-3.0/_common.scss

Fixed undefined state in headerbar separator

---

Communitheme/gtk-3.0/_common.scss

closes #473
Removed also old fix that only reverted the shape change in some
cases.

Fixed uncheded radio shape change when selected

---

Communitheme/gtk-3.0/_common.scss

Fixed spinbutton hover color in dark variant

---

Communitheme/gtk-3.0/_colors.scss
Communitheme/gtk-3.0/_common.scss

Pale blue as selected color for editable text only

---

Communitheme/gtk-3.0/_common.scss

Closes https://github.com/ubuntu/gtk-communitheme/issues/502#issuecomment-393701360

selected_text_backdrop_improvements

---

Communitheme/gtk-3.0/_apps.scss
Communitheme/gtk-3.0/_common.scss

Seen in this comment:
https://github.com/ubuntu/gtk-communitheme/issues/464#issuecomment-394326852
Closes https://github.com/ubuntu/gtk-communitheme/issues/464

Add_Padding_To_Menus

---

Communitheme/gtk-3.0/_apps.scss

Fixes https://github.com/ubuntu/gtk-communitheme/issues/510 chromium only

fix_chromium

---

Communitheme/gtk-3.0/_common.scss

- improved hover button transition
- added hover transition to non-flat button
see https://github.com/ubuntu/gtk-communitheme/issues/184#issuecomment-392477771

Added hover transition to non-flat buttons

---

Communitheme/gtk-3.0/_common.scss

give treeview arrows the same color as label

---

Communitheme/gtk-3.0/_drawing.scss

Closes https://github.com/ubuntu/gtk-communitheme/issues/523

Use transparent inset shadows instead of dashed lines for undershoots

---

Communitheme/gtk-3.0/_drawing.scss

Made suggested action label button more visible when disabled

---

Communitheme/gtk-3.0/_apps.scss

Round labels for nautilus selection in view

---

Communitheme/gtk-3.0/_common.scss

Beautify emoji-picker popover style

---

Communitheme/gtk-3.0/_common.scss

Removed lightweight style for radio/checkbox

---

Communitheme/gtk-3.0/_common.scss

border-radius for selected elements in inconview

---

Communitheme/gtk-3.0/_drawing.scss

Added back box-shadow to button in normal state

---

Communitheme/gtk-3.0/_apps.scss

Closes https://github.com/ubuntu/gtk-communitheme/issues/540

base_color for the nautilus window background in the dark version

---

Communitheme/gtk-3.0/_common.scss
Communitheme/gtk-3.0/_drawing.scss

Closes https://github.com/ubuntu/gtk-communitheme/issues/549
After:

Adapt dark variant headerbarpathbar bg in backdrop to light variant

---

Communitheme/gtk-3.0/_common.scss

Menus again: Padding top bottom & no border radius for items

---

Communitheme/gtk-3.0/_apps.scss

Closes https://github.com/ubuntu/gtk-communitheme/issues/553

Base color for dark variant treeview header in nautilus

---

Communitheme/gtk-3.0/_common.scss

Closes https://github.com/ubuntu/gtk-communitheme/issues/430

Add active effect for min and max buttons

---

Communitheme/gtk-3.0/_apps.scss

Closes https://github.com/ubuntu/gtk-communitheme/issues/557

bg_color for tab background

---

Communitheme/gtk-3.0/_drawing.scss

Dark variant only changes:
- less brightening of active btns hover
- lightened up the border top color for entries
- makes dark variant slider backdrop color similar to light version
- removes the light border effect in the backdrop for sliders
- makes entries bg color similar to btns in backdrop

Dark refinements

---

Communitheme/gtk-3.0/_colors.scss
Communitheme/gtk-3.0/_common.scss

https://community.ubuntu.com/t/call-for-participation-an-ubuntu-default-theme-lead-by-the-community/1545/1288?

Light blue for selected text

---

Communitheme/gtk-3.0/_common.scss
Communitheme/gtk-3.0/_drawing.scss

Finally...
Closes https://github.com/ubuntu/gtk-communitheme/issues/430

Draw a circle on active backdrop close button

---

Communitheme/gtk-3.0/_apps.scss

Closes https://github.com/ubuntu/gtk-communitheme/issues/570

Fix backdrop treeview header color for darktheme

---

Communitheme/gtk-3.0/_colors.scss
Communitheme/gtk-3.0/_common.scss

Closes https://github.com/ubuntu/gtk-communitheme/issues/574

Darker blue text selection for entries in headerbar

---

Communitheme/gtk-3.0/_apps.scss

Added orange bg to selected row in Nemo's places sidebar

---

Communitheme/gtk-3.0/_apps.scss
Communitheme/gtk-3.0/_common.scss

Closes https://github.com/ubuntu/gtk-communitheme/issues/580

wm_border left and right for dark theme

---

Communitheme/gtk-3.0/_common.scss

Fixed typo inside the code

---

Communitheme/gtk-3.0/_common.scss

Closes https://github.com/ubuntu/gtk-communitheme/issues/602

Remove border again due to a problem with SSD applications

---

Communitheme/gtk-3.0/_apps.scss

Closes #599
Also links the linked buttons in the toolbar.

Nemo tweaks

---

Communitheme/gtk-3.0/_common.scss

Added hover effect to app-notification close button

---

Communitheme/gtk-3.0/_apps.scss

Restyled drop-active box-shadow ring on nautilus tab

---

gtk/src/gtk-2.0/gtkrc

Closes https://github.com/ubuntu/communitheme/issues/579
Before:
After:

Shrink gtk2 icon size in toolbars

---

gtk/src/gtk-3.0/_common.scss

Closes https://github.com/ubuntu/yaru/issues/306

Default button and outline style

---

gtk/src/gtk-3.0/_common.scss

Accidentally taken the text color.
Fg_color should be correct.
@clobrano please check and then merge if its correct ;)

Use headerbar_fg_color for .default btns in headerbar

---

gtk/src/gtk-3.0/_common.scss

Replaced :insensitive pseudoclass with :disabled

---

gtk/src/gtk-3.0/_common.scss

Made message dialog all white

---

gtk/src/gtk-3.0/_common.scss

fixed levelbar backdrop colors

---

gtk/src/gtk-3.0/_common.scss
gtk/src/gtk-3.0/_drawing.scss

Closes https://github.com/ubuntu/yaru/issues/750
Continuation of https://github.com/ubuntu/yaru/pull/753
In agreement with @clobrano opening this new PR
Results:

Make active and active-hover buttons flat for headerbar

---

gtk/src/gtk-3.0/_colors.scss
gtk/src/gtk-3.0/_common.scss
gtk/src/gtk-3.0/_drawing.scss

radio check fine tuning

---

gnome-shell/src/gnome-shell-sass/_colors.scss

from fg_color to white
and adapt the transparency
After:
Before:
@clobrano @madsrh like discussed on telegram

Change base_hover and base_active transparentized color

---

gtk/src/gtk-3.0/_apps.scss

Closes https://github.com/ubuntu/yaru/issues/781

Use transparentized selcted fg color instead of silk

---

gtk/src/gtk-3.0/_colors.scss
gtk/src/gtk-3.0/_common.scss

Closes https://github.com/ubuntu/yaru/issues/783
Let's see if the testing snap works again ;) @madsrh 
Otherwise I post screenshots again

Popover and context menu border unification & lighter popovers for dark variant

---

gtk/src/gtk-3.0/_common.scss

Testing PR
As seen here:
https://github.com/ubuntu/yaru/issues/769#issuecomment-419113951

Bold font for default buttons

---

gtk/src/gtk-3.0/_common.scss
gtk/src/gtk-3.0/_drawing.scss

Closes https://github.com/ubuntu/yaru/issues/789
@clobrano @madsrh

Infobar enhancement

---

gtk/src/gtk-3.0/_apps.scss

Make scrollbars background transparent, adapting to other scrollbars

---

gtk/src/gtk-3.0/_common.scss

Exclude destruction action buttons also from the .default button styling

---

gtk/src/gtk-3.0/_colors.scss

see https://github.com/ubuntu/yaru/pull/785#issuecomment-419699148

colors/menu: Slightly increase dark menu background color

---

gtk/src/gtk-3.0/_drawing.scss

drawing/switch dark: made insensitive border as in spinbutton

---

gtk/src/light/gtk-3.0/_apps.scss

apps/nautilus: fixed circular button backdrop transition

---

gnome-shell/src/gnome-shell-sass/_common.scss
gnome-shell/src/gnome-shell-sass/_drawing.scss
gtk/src/light/gtk-3.0/_common.scss

Closes https://github.com/ubuntu/yaru/issues/880

Gtk and shell btn outline colors

---

gtk/src/light/gtk-3.0/_apps.scss

apps/software-center: fixed theme parsing error

---

gtk/src/light/gtk-3.0/_apps.scss

Just to get my foot wet again:
Closes two minor issues: #804 and #883

Fix Issue804 and Issue883

---

gnome-shell/src/gnome-shell-sass/_common.scss

Closes https://github.com/ubuntu/yaru/issues/957
@madsrh @clobrano @godlyranchdressing please check

Style buttons in light dialogues

---

gtk/src/light/gtk-3.20/_drawing.scss

Closes https://github.com/ubuntu/yaru/issues/975
Before
After

Reduce darkening of Gtk dark entries top border

---

gtk/src/light/gtk-3.20/_common.scss

Closes https://github.com/ubuntu/yaru/issues/983
But I need to test this on my host first, so far only tested on 3.30 files

Style tag labels

---

gtk/src/light/gtk-3.20/_common.scss

Unify stackswitcher and buttonbox style

---

gtk/src/light/gtk-3.20/_common.scss

Style backdrop and checked:active .path-bar buttons :)

Fix backdrop and checked:active

---

gtk/src/light/gtk-3.20/_common.scss
gtk/src/light/gtk-3.20/_drawing.scss

This commit is necessary to fix a little mismatch between button and
stackswitcher border in previous implementation

Reuse all buttonbox code for stackswitcher

---

gtk/src/light/gtk-3.0/_common.scss
gtk/src/light/gtk-3.20/_common.scss

Remove menuitem transition from context menus and popovers

---

gtk/src/light/gtk-3.20/_colors.scss
gtk/src/light/gtk-3.20/_drawing.scss

Fix osd button active and active:hover states

---

gtk/src/light/gtk-3.20/_common.scss
gtk/src/light/gtk-3.20/_drawing.scss

Add a specific check in hover to adapt bg color for menu buttons
use boders_color for borders in backdrop:hover
closes #1036

Fix menu button hover

---

gtk/src/light/gtk-3.20/_drawing.scss

Reduced the darkness of undershoot bg resulting in a better look, especially in the backdrop 
+ minor refactoring of the variable

Reduce the darkness of dark var undershoots + refactoring

---

gtk/src/light/gtk-3.20/_common.scss
gtk/src/light/gtk-3.20/assets/bullet-symbolic.svg
gtk/src/light/gtk-3.20/assets/check-symbolic.svg
gtk/src/light/gtk-3.20/assets/dash-symbolic.svg

Add proper svg image scaling and fix svg opacity

---

icons/Suru/scalable/actions/system-shutdown-symbolic.svg
icons/src/scalable/source-symbolic.svg

Now this icon looks in the same style as other icons.

Remake shutdown icon

---

gnome-shell/src/gnome-shell-sass/_colors.scss
gnome-shell/src/gnome-shell-sass/_common.scss
gnome-shell/src/gnome-shell-sass/_drawing.scss
gtk/src/light/gtk-3.20/_colors.scss
gtk/src/light/gtk-3.20/_common.scss
gtk/src/light/gtk-3.20/_drawing.scss

As discussed :)
Just a code clean up, no color changes

Replace focus_color with selected_bg_color in shell and gtk themes

---

icons/Suru/scalable/actions/system-shutdown-symbolic.svg
icons/src/scalable/source-symbolic.svg

Reverts ubuntu/yaru#1063
as discussed

Revert "Remake shutdown icon"

---

icons/Suru/scalable/actions/system-shutdown-symbolic.svg
icons/src/scalable/source-symbolic.svg

Reverts ubuntu/yaru#1080
(for now, because it creates conflicts currently)

Revert "Revert "Remake shutdown icon""

---

gtk/src/light/gtk-3.20/_common.scss

Closes https://github.com/ubuntu/yaru/issues/1086
@iainlane please test again

Fix .path-bar button styling

---

gtk/src/light/gtk-3.20/_common.scss

Add roundness to #pathbarbox sliderbuttons

---

CONTRIBUTING.md

Eh.. nothing much. I'm just reading the contributing guideline and it looks like you guys forget to complete the sentence at https://github.com/ubuntu/yaru/commit/25136654a68dedd8225808b1dea170cfc073a80b#diff-6a3371457528722a734f3c51d9238c13R7 and I found it on README so I guess I should complete it :D 
Sorry if this is too small of a PR.. I'm trying to go through the issue list to find something to do

Update "sound" part in contributing guideline

---

icons/Suru/scalable/actions/window-new-symbolic.svg
icons/src/scalable/source-symbolic.svg

#1177 
As always, please check this thoroughly!
- window-new-symbolic.svg
- source-symbolic.svg

Added window-new-symbolic.svg

---

gtk/src/light/gtk-3.20/_drawing.scss

Fix Gtk theme selectionmode buttons on hover

---

gtk/src/light/gtk-3.20/_common.scss

Reverts ubuntu/yaru#1188
Due to https://github.com/ubuntu/yaru/issues/1190

Revert "Fix Light/Dark emoji.popover button:checked difference"

---

icons/src/symlinks/fullcolor/places.list

added missing places.list entry for symlinking between folder.png and
inode-directory.png

update places.list with inode-directory symlink

---

icons/Suru/16x16/apps/org.gnome.seahorse.Application.png
icons/Suru/16x16@2x/apps/org.gnome.seahorse.Application.png
icons/Suru/24x24/apps/org.gnome.seahorse.Application.png
icons/Suru/24x24@2x/apps/org.gnome.seahorse.Application.png
icons/Suru/256x256/apps/org.gnome.seahorse.Application.png
icons/Suru/256x256@2x/apps/org.gnome.seahorse.Application.png
icons/Suru/32x32/apps/org.gnome.seahorse.Application.png
icons/Suru/32x32@2x/apps/org.gnome.seahorse.Application.png
icons/Suru/48x48/apps/org.gnome.seahorse.Application.png
icons/Suru/48x48@2x/apps/org.gnome.seahorse.Application.png
icons/Suru/scalable/apps/org.gnome.seahorse.Application-symbolic.svg
icons/src/symlinks/fullcolor/apps.list
icons/src/symlinks/symbolic/apps.list

Closes https://github.com/ubuntu/yaru/issues/1198

Symlink: passwords-app->org.gnome.seahorse.Application

---

debian/changelog
gtk/src/light/gtk-3.20/_common.scss

link in infobar was using the color expected for a selected state.
Fixing this adding the proper selector
closes #1256

infobar link invisible

---

icons/Suru/16x16/apps/update-notifier.png
icons/Suru/16x16@2x/apps/update-notifier.png
icons/Suru/24x24/apps/update-notifier.png
icons/Suru/24x24@2x/apps/update-notifier.png
icons/Suru/256x256/apps/update-notifier.png
icons/Suru/256x256@2x/apps/update-notifier.png
icons/Suru/32x32/apps/update-notifier.png
icons/Suru/32x32@2x/apps/update-notifier.png
icons/Suru/48x48/apps/update-notifier.png
icons/Suru/48x48@2x/apps/update-notifier.png
icons/Suru/scalable/apps/update-notifier-symbolic.svg
icons/src/symlinks/fullcolor/apps.list
icons/src/symlinks/symbolic/apps.list

Cherry-pick from bionic_IconTheme_remove_update_notifier_symlinks
Closes #1210

Disco: Cherry-Pick from Bionic Branch - Remove apt-daemon-download>updatenotifier symlinks

---

icons/Suru/16x16/apps/org.gnome.Notes.png
icons/Suru/16x16@2x/apps/org.gnome.Notes.png
icons/Suru/24x24/apps/org.gnome.Notes.png
icons/Suru/24x24@2x/apps/org.gnome.Notes.png
icons/Suru/256x256/apps/org.gnome.Notes.png
icons/Suru/256x256@2x/apps/org.gnome.Notes.png
icons/Suru/32x32/apps/org.gnome.Notes.png
icons/Suru/32x32@2x/apps/org.gnome.Notes.png
icons/Suru/48x48/apps/org.gnome.Notes.png
icons/Suru/48x48@2x/apps/org.gnome.Notes.png
icons/Suru/scalable/apps/org.gnome.Notes-symbolic.svg
icons/src/symlinks/fullcolor/apps.list
icons/src/symlinks/symbolic/apps.list

Cherry-picked from bionic_IconTheme_gnome_notes_symlinks

Disco: Cherry-picked from bionic - Symlinks notes-app>org.gnome.Notes

---

icons/Suru/16x16/apps/update-notifier.png
icons/Suru/16x16@2x/apps/update-notifier.png
icons/Suru/24x24/apps/update-notifier.png
icons/Suru/24x24@2x/apps/update-notifier.png
icons/Suru/256x256/apps/update-notifier.png
icons/Suru/256x256@2x/apps/update-notifier.png
icons/Suru/32x32/apps/update-notifier.png
icons/Suru/32x32@2x/apps/update-notifier.png
icons/Suru/48x48/apps/update-notifier.png
icons/Suru/48x48@2x/apps/update-notifier.png
icons/Suru/scalable/apps/update-notifier-symbolic.svg
icons/src/symlinks/fullcolor/apps.list
icons/src/symlinks/symbolic/apps.list

Bionic: Remove apt-daemon-download>updatenotifier symlinks

---

build-helpers/prepare-build-snap

Enable again testing snap for bionic PR

---

gnome-shell/src/gnome-shell-sass/_common.scss
gtk/src/light/gtk-3.20/_common.scss

Cherry-picking the normal font weight into bionic

Bionic font weight sync

---

gtk/src/light/gtk-3.20/_common.scss

Cherry-picking sidebar selection change into bionic
See: https://github.com/ubuntu/yaru/pull/1303

Bionic: light gray sidebar row selection

---

gnome-shell/src/gnome-shell-sass/_common.scss

To work on super bright wallpapers by increasing the radius and changing the offset to 0/0
Closes https://github.com/ubuntu/yaru/issues/1333

Change the screenshield shadows

---

gtk/src/light/gtk-3.20/_common.scss
gtk/src/light/gtk-3.20/_drawing.scss

Cherry-Picking
https://github.com/ubuntu/yaru/pull/1330/commits/d5d630665c67fa9fb78d0220b6348844837248ea
and
https://github.com/ubuntu/yaru/pull/1330/commits/aebee1883db735570f3199a0720fb9b6e4972f61
and
https://github.com/ubuntu/yaru/pull/1330/commits/4e4a54438b922308a9b8bfd5f525f5de50cff236
from
https://github.com/ubuntu/yaru/tree/GtkTheme_DarkThemeSwitches

Bionic gtk theme dark theme switches

---

gnome-shell/src/gnome-shell-sass/_common.scss
gtk/src/light/gtk-3.20/_common.scss

Cherry-picking
https://github.com/ubuntu/yaru/pull/1346/commits/6cbb02a6ee72732c741a534f1841a77114603419
and
https://github.com/ubuntu/yaru/pull/1346/commits/c710105091d2297eb37c8169799b20240280927b
from 
https://github.com/ubuntu/yaru/tree/Gtk_and_Shell_Theme_TooltipAdaption

Bionic gtk and shell theme tool tip adaption

---

gtk/src/light/gtk-3.20/_common.scss

Fix wrong fg_color for btns in selected rows

---

gtk/src/light/gtk-3.20/_common.scss

Cherry-picking
https://github.com/ubuntu/yaru/pull/1353/commits/129bc0c4cf007720ba53af3cc3ad95721b27fb93
from
https://github.com/ubuntu/yaru/pull/1353

Bionic: Fix wrong fg_color for btns in selected rows

---

gnome-shell/src/gnome-shell-sass/_common.scss
gnome-shell/src/gnome-shell-sass/_drawing.scss

Closes #1342 
Edit: the user icon looks like this now:

Alternative Darker GDM

---

gnome-shell/src/gnome-shell-sass/_common.scss
gnome-shell/src/gnome-shell-sass/_drawing.scss

Cherry-picking and commiting "manually", to adapt the bionic branch to https://github.com/ubuntu/yaru/tree/ShellTheme_GDM
We/I need to test this on our bionic installations, I hope I did not mess up any merge conflict handling

Bionic: shelltheme gdm

---

gtk/src/light/gtk-3.20/_common.scss

sidebar: fix orange border in selected row's button

---

debian/changelog
gtk/src/light/gtk-3.20/_common.scss

As mentioned on https://github.com/ubuntu/yaru/issues/1370

Cherry pick #1368

---

gtk/src/light/gtk-3.20/_common.scss

Cherry-picked 
https://github.com/ubuntu/yaru/pull/1378/commits/d9717f6e0f76f697bde6c764512ae32d4f0aa7f0
from 
https://github.com/ubuntu/yaru/tree/GtkTheme_selectedlistbox_fix

Bionic: Fix selected row bug

---

gtk/src/light/gtk-3.20/_common.scss

Revert "Fix hb entry border bug"

---

gnome-shell/src/gnome-shell-sass/_common.scss

Closes https://github.com/ubuntu/yaru/issues/1393

Remove dialog shadow

---

gnome-shell/src/gnome-shell-sass/_common.scss

Cherry-pick from https://github.com/ubuntu/yaru/pull/1394

Bionic: remove dialog shadows

---

gtk/src/light/gtk-3.20/_apps.scss

apps.scss: Nemo remove nautilus tweaks

---

gtk/src/light/gtk-3.20/_tweaks.scss

- fixed the need to re-insert the selection mode styling with :not() pseudo class for .selection-mode and .selection-menu
@clobrano please test it if you have time :)
Todo:

WIP: Reduce _tweaks.scss code

---

gtk/src/light/gtk-3.20/_tweaks.scss

- in headerbar... by excluding them from the dark styling + add dedicated styling for them when they are disabled ....

Fix suggested and destructive action btns

---

gtk/src/light/gtk-3.20/_colors.scss
gtk/src/light/gtk-3.20/_common.scss
gtk/upstream/gtk+3.0/Adwaita/_colors.scss
gtk/upstream/gtk+3.0/Adwaita/_common.scss
gtk/upstream/gtk+3.0/Adwaita/gtk-contained-dark.css
gtk/upstream/gtk+3.0/Adwaita/gtk-contained.css

- updated _common and _drawing in the upstream folder via carlos awesome script which included a fix for hard readbable app noficiations and round titlebuttons
- copied those changes, minus our metrics, into our _common and _colors

Update from upstream

---

gnome-shell/src/gnome-shell-sass/_common.scss
gnome-shell/src/gnome-shell-sass/_drawing.scss
gnome-shell/src/gnome-shell-sass/_high-contrast-colors.scss
gnome-shell/upstream/gnome-shell-sass/_common.scss
gnome-shell/upstream/gnome-shell-sass/_drawing.scss
gnome-shell/upstream/gnome-shell-sass/_high-contrast-colors.scss

This adds support for app-icons DnD, app folders and fixes the missing search
results.

gnome-shell: Sync scss with upstream changes for 3.34

---

icons/Suru/16x16/apps/org.gnome.SimpleScan.png
icons/Suru/16x16@2x/apps/org.gnome.SimpleScan.png
icons/Suru/24x24/apps/org.gnome.SimpleScan.png
icons/Suru/24x24@2x/apps/org.gnome.SimpleScan.png
icons/Suru/256x256/apps/org.gnome.SimpleScan.png
icons/Suru/256x256@2x/apps/org.gnome.SimpleScan.png
icons/Suru/32x32/apps/org.gnome.SimpleScan.png
icons/Suru/32x32@2x/apps/org.gnome.SimpleScan.png
icons/Suru/48x48/apps/org.gnome.SimpleScan.png
icons/Suru/48x48@2x/apps/org.gnome.SimpleScan.png
icons/Suru/scalable/apps/org.gnome.SimpleScan-symbolic.svg
icons/src/symlinks/fullcolor/apps.list
icons/src/symlinks/symbolic/apps.list

Add new simpe-scan symlinks

---

debian/changelog

changelog: update for upcoming 19.10.1 release

---

gtk/src/light/gtk-3.20/_tweaks.scss

Use fg_color for hovered menuitems

---

gnome-shell/src/gnome-shell-sass/_common.scss

- copied from https://github.com/ubuntu/yaru/pull/1239

Round edges for desktop icons

---

gtk/src/light/gtk-3.20/_apps.scss

Current floating-bar style does not match with the new light
variant.
Restyle it similar to upstream
closes #1498

apps: Restyle Nautilus floating-bar

---

gtk/src/light/gtk-3.20/_colors.scss
gtk/src/light/gtk-3.20/_tweaks.scss

- sync OSD color with the shell
- style app notifications like shell notifications + a stronger shadow

OSD color and app notification changes

---

gtk/src/light/gtk-3.20/_apps.scss
gtk/src/light/gtk-3.20/_ubuntu-colors.scss

Revert "Terminal additions"

---

icons/Suru/scalable/apps/evince-symbolic.svg
icons/Suru/scalable/apps/org.gnome.Evince-symbolic.svg
icons/src/scalable/source-symbolic.svg
icons/src/symlinks/symbolic/apps.list

Symbolic icon for new Evince design

---

gtk/src/default/gtk-3.20/_headerbar.scss

An example of this button could be find in Gedit's sidebar (the
"Documents") button.
closes #1561

headerbar: add mixed style to button.popup.toggle button

---

snap/snapcraft.yaml

Replace hard-coded versioning with automatic one based on git
New versioning will be "Major.minor", where Major is the latest tag in
the branch and minor the number of commits since the latest tagged one.
closes #1534

[bionic] snapcraft.yaml: better versioning

---

gnome-shell/src/gnome-shell-sass/_common.scss

Import style from upstream MR !720
https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/720
closes #1526

application view: style rename-folder popup

---

gtk/src/default/gtk-3.20/_tweaks.scss

Cherry pick from https://github.com/ubuntu/yaru/issues/1584

Bionic: Remove dowstream check/radio flattening

---

gtk/src/default/gtk-3.20/_tweaks.scss

Fix app notification buttons

---

gtk/src/default/gtk-3.20/_tweaks.scss

Bionic: Fix app notification buttons

---

gtk/src/default/gtk-3.20/_headerbar.scss

Fix headerbar focused entries

---

gtk/src/dark/gtk-2.0/gtkrc

gtk2: use same color for menu in gtk2 and gtk3

---

icons/Suru/scalable/status/weather-few-clouds-symbolic.svg

This was a nice quick one!
Closes #1566

Adding missing icon for weather-few-clouds-symbolic

---

icons/Suru/scalable/actions/favorite-new-symbolic.svg
icons/Suru/scalable/emblems/emblem-system-symbolic.svg
icons/Suru/scalable/mimetypes/application-x-addon-symbolic.svg
icons/Suru/scalable/status/volume-warning-symbolic.svg
icons/src/scalable/source-symbolic.svg

This is the cherry pick of #1616 for Bionic.

Bionic: four missing symbols

---

icons/Suru/scalable/status/weather-few-clouds-symbolic.svg

This is the cherry pick of #1617.

Bionic: weather-few-clouds-symbolic

---

gnome-shell/src/gnome-shell-sass/_common.scss

- fixes https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1848053

Add a color for the finger print label

---

gtk/src/default/gtk-3.20/_tweaks.scss

Lighten headerbar border-color for the dark theme

---

gtk/src/default/gtk-3.20/_tweaks.scss

Cherry-pick from https://github.com/ubuntu/yaru/pull/1647

Bionic: Lighten headerbar border-color for the dark theme

---

gtk/src/default/gtk-3.20/_tweaks.scss

gtk/tweaks: remove text shadow in osd

---

gnome-shell/src/gnome-shell-sass/_common.scss
gnome-shell/upstream/gnome-shell-sass/_common.scss

Let's keep tracking stable version for now

gnome-shell: Sync with 3.34.2 changes

---

.github/workflows/open-pr-on-changes.yaml

Switch gtk to gtk-3-24 one.
GNOME Shell tracks master.

Select branch for autorebase

---

gtk/src/default/gtk-3.20/_colors.scss

brighten up dark menus

---

debian/control
debian/yaru-theme-unity.install

debian: add -unity package configuration

---

icons/Suru/scalable/categories/applications-multimedia-symbolic.svg
icons/src/scalable/source-symbolic.svg

Adding applications-multimedia-symbolic

---

gtk/src/default/gtk-3.20/_colors.scss
gtk/src/default/gtk-3.20/_headerbar.scss

headerbar: increase headerbar backdrop contrast

---

gtk/src/default/gtk-3.20/_common.scss
gtk/src/default/gtk-3.20/_tweaks.scss

tweaks: no borders for checkmarks in file menus and context menus

---

sounds/src/stereo/power-plug.oga
sounds/src/stereo/power-unplug.oga

- power-plug.oga -> device-added.oga
- power-unplug.oga -> device-removed.oga

audio: add missing audio file symlinks

---

gtk/src/default/gtk-3.20/_common.scss
gtk/upstream/gtk+3.0/Adwaita/_common.scss

https://gitlab.gnome.org/GNOME/gtk/merge_requests/1341
->
https://gitlab.gnome.org/GNOME/gtk/issues/1808
Updates from upstream
(including a new line =) )

Gtk theme typography upstream updates

---

gtk/src/default/gtk-3.20/_tweaks.scss

Gtk theme bring back undershoots for scrolled windows

---

gtk/src/default/gtk-3.20/_apps.scss

Fix (without the font-size change) for https://github.com/ubuntu/yaru/issues/1791

Improvements to the floating bar #1791

---

gtk/src/default/gtk-3.20/_apps.scss
gtk/src/default/gtk-3.20/_tweaks.scss

- tweaks: notebook tab checked backdrop use same color as .view
- tweaks: notebook tab checked in backdrop no bottom border
- tweaks: notebook's tab unchecked font weight
- tweaks: fix notebook's tab checked-hover state
closes #1802

New notebook tab's style fixes

---

gtk/src/default/gtk-3.20/_colors.scss

Fixes https://github.com/ubuntu/yaru/issues/1826
Photo by @Feichtmeier 😄

Use old linkcolor in dark theme

---

gtk/src/default/gtk-3.20/_drawing.scss
gtk/src/default/gtk-3.20/_tweaks.scss

- we have forgotten to remove the top highlight here
- increasing brightness and contrast of sliders and buttons in OSDs
Closes #1850

OSD button styling

---

debian/changelog

Update changelog for release 20.04

prepare for release 20.04

---

gtk/src/default/gtk-3.20/_common.scss
gtk/src/default/gtk-3.20/_tweaks.scss
gtk/upstream/gtk+3.0/Adwaita/_common.scss
gtk/upstream/gtk+3.0/Adwaita/gtk-contained-dark.css
gtk/upstream/gtk+3.0/Adwaita/gtk-contained.css

- Fixed outline radii: https://gitlab.gnome.org/GNOME/gtk/merge_requests/1384
- Fixed linked backdrop colors: https://gitlab.gnome.org/GNOME/gtk/merge_requests/1370
- With the outline changes we can remove this code from _tweaks.scss

Gtk theme update from upstream

---

gtk/src/default/gtk-3.20/_apps.scss
icons/src/fullcolor/render-bitmaps.py

Added the actions, legacy and wip folders to the script.

More render-bitmaps sources

---

gnome-shell/src/gnome-shell-sass/_colors.scss
gtk/src/default/gtk-3.20/_colors.scss

@ubuntujaggers @madsrh @clobrano please test and share your opinions

Shell and Gtk: make the focus ring golden

---

icons/Suru/16x16/actions/selection-checked.png
icons/Suru/16x16@2x/actions/selection-checked.png
icons/Suru/24x24/actions/selection-checked.png
icons/Suru/24x24@2x/actions/selection-checked.png
icons/Suru/256x256/actions/selection-checked.png
icons/Suru/256x256@2x/actions/selection-checked.png
icons/Suru/32x32/actions/selection-checked.png
icons/Suru/32x32@2x/actions/selection-checked.png
icons/Suru/48x48/actions/selection-checked.png
icons/Suru/48x48@2x/actions/selection-checked.png
icons/src/symlinks/fullcolor/actions.list

Adding a symlink should fix https://github.com/ubuntu/yaru/issues/1686 ✔️ 
Could you test @Feichtmeier ?

Symlink for selection-checked

---

CONTRIBUTING.md

Pretty self explanatory, unless I've misinterpreted it

Correct number of project parts

---

gtk/src/default/gtk-3.20/_common.scss
gtk/upstream/gtk+3.0/Adwaita/_common.scss

https://gitlab.gnome.org/GNOME/gtk/merge_requests/1448

.osd and .circular button changes from upstream

---

gnome-shell/src/gnome-shell-sass/_colors.scss
gtk/src/default/gtk-3.20/_colors.scss

Revert link color configuration at commit a8183b3
There might be some more details, this is why is still a DRAFT

shell/gtk: rework link color

---

debian/changelog

Let me know if this is fine to release as it is up to commit e402f7b8.
Please don't merge anything before this, or let me know in case so I can rebase.

Prepare for ubuntu release 20.04.2

---

gtk/src/default/gtk-3.20/_tweaks.scss

- remove outline as focused tabs are already checked
- remove backdrop hover
Closes #1993

Tweaks.scss: notebook tab improvements

---

gtk/src/default/gtk-3.20/_apps.scss

nautilus: use destructive color for "stop loading" floating button

---

gtk/src/default/gtk-3.20/_apps.scss

apps/nautilus: make infobar more visible

---

gtk/src/default/gtk-3.20/_apps.scss

Extends PR #2041 according to https://github.com/ubuntu/yaru/issues/1989#issuecomment-595708865
Closes: #1989

apps/nautilus: dim backdrop infobar color

---

icons/Suru/scalable/places/folder-download-symbolic.svg
icons/src/scalable/source-symbolic.svg

Changing proportions of download symbol to match folder icon

---

gtk/src/default/gtk-3.20/_apps.scss

make styling of the title event box the same on each page
Closes https://github.com/ubuntu/yaru/issues/2045

Ubiquity: title box improvements

---

icons/Suru/scalable/actions/edit-clear-all-symbolic.svg
icons/src/scalable/source-symbolic.svg

Adding symbol for edit-clear-all

---

gtk/src/default/gtk-3.20/_common.scss
gtk/src/default/gtk-3.20/_headerbar.scss

- use the same backdrop border color
- use the same background color
Fixes: #2070

Reduce differences between default and dark variant headerbar buttons

---

gnome-shell/src/gnome-shell-sass/_colors.scss
gnome-shell/src/gnome-shell-sass/_common.scss
gnome-shell/src/gnome-shell-sass/_drawing.scss

- sync shell popup with master shell popup color fafafa
- darken slider handle border colors like in master
- update button shadows like in master

Bionic: Sync shell colors and buttons with master

---

gtk/src/default/gtk-3.20/_apps.scss

It's a regression from https://github.com/ubuntu/yaru/pull/2082

Bionic: Re-add nautilus desktop styling

---

icons/Suru/16x16/legacy/gtk-remove.svg
icons/Suru/16x16/legacy/list-remove.svg

Legacy 16px *-remove.svg icons pixel perfect

---

gtk/src/default/gtk-3.20/_apps.scss

Dim icon view caption label color as in Adwaita
Fixes: #2097
LP: #1868383

apps/nautilus: style icon view caption labels

---

icons/Suru/16x16/legacy/gnome-stock-mail-new.svg
icons/Suru/16x16/legacy/gnome-stock-mail-snd.svg
icons/Suru/16x16/legacy/mail-message-new.svg
icons/Suru/16x16/legacy/mail-send.svg
icons/Suru/16x16/legacy/mail-sent.svg
icons/Suru/16x16/legacy/mail_new.svg
icons/Suru/16x16/legacy/stock_mail-compose.svg
icons/Suru/16x16/legacy/stock_mail-send.svg

Fix legacy 16x16 mail icons twisted paths

---

gtk/src/default/gtk-3.20/_apps.scss

apps/nautilus: fix dim-label in selection and backdrop

---

gtk/src/default/gtk-3.20/_common.scss

This reverts commit a8f43dc9c96ba207c67d70900e5d096c35f50bfb.

Revert "use default adwaita button padding"

---

gnome-shell/src/gnome-shell-sass/widgets/_app-grid.scss

I didn't notice anything wrong with them (no actual changes TBH), so feel free to look at these deeper :)

Shell: import some changes from 3.36 upstream branch

---

icons/Suru/16x16/mimetypes/application-x-apple-diskimage.png
icons/Suru/16x16@2x/mimetypes/application-x-apple-diskimage.png
icons/Suru/24x24/mimetypes/application-x-apple-diskimage.png
icons/Suru/24x24@2x/mimetypes/application-x-apple-diskimage.png
icons/Suru/256x256/mimetypes/application-x-apple-diskimage.png
icons/Suru/256x256@2x/mimetypes/application-x-apple-diskimage.png
icons/Suru/32x32/mimetypes/application-x-apple-diskimage.png
icons/Suru/32x32@2x/mimetypes/application-x-apple-diskimage.png
icons/Suru/48x48/mimetypes/application-x-apple-diskimage.png
icons/Suru/48x48@2x/mimetypes/application-x-apple-diskimage.png
icons/src/symlinks/fullcolor/mimetypes.list

Use CD image icon for apple disk images

---

icons/Suru/scalable/status/network-cellular-connected-symbolic.svg
icons/src/scalable/source-symbolic.svg

Removing green from network-cellular-connected-symbolic

---

icons/src/fullcolor/mimetypes/text-x-scala.svg

Issue in : #2231
Deleted Pictograms Layer (hidden) consisting of **Logs**-pictogram
Renamed Pictograms1 to Pictograms
Screenshot: 
Thanks!

Mimetype text x scala

---

icons/Suru/16x16/mimetypes/application-gpx+xml.png
icons/Suru/16x16@2x/mimetypes/application-gpx+xml.png
icons/Suru/24x24/mimetypes/application-gpx+xml.png
icons/Suru/24x24@2x/mimetypes/application-gpx+xml.png
icons/Suru/256x256/mimetypes/application-gpx+xml.png
icons/Suru/256x256@2x/mimetypes/application-gpx+xml.png
icons/Suru/32x32/mimetypes/application-gpx+xml.png
icons/Suru/32x32@2x/mimetypes/application-gpx+xml.png
icons/Suru/48x48/mimetypes/application-gpx+xml.png
icons/Suru/48x48@2x/mimetypes/application-gpx+xml.png
icons/src/symlinks/fullcolor/mimetypes.list

Just link application-geo+json to application-gpx+xml
Closes #2288

Add GPX mimetype

---

icons/Suru/scalable/actions/view-layout-symbolic.svg
icons/src/scalable/source-symbolic.svg

Add view layout symbolic icon

---

CONTRIBUTING.md

Fix typo .cscc -> .scss

---

gnome-shell/src/gnome-shell-sass/_colors.scss
gtk/src/default/gtk-3.20/_colors.scss

Lighten dark theme success_color

---

icons/Suru/scalable/status/network-wireless-connected-symbolic.svg

Removing green color from network-wireless-connected-symbolic

---

icons/Suru/scalable/devices/audio-speakers-bluetooth-symbolic.svg

Remove outline from audio-speakers-bluetooth-symbolic icon

---

gnome-shell/src/gnome-shell-sass/widgets/_app-grid.scss

Give app-grid's folder label/entries osd fg color

---

gnome-shell/src/gnome-shell-sass/_colors.scss

Adapt shell links to gtk links: orange->blue

---

gtk/src/default/gtk-3.20/_tweaks.scss

- style HDY headerbar, actionbar, buttons and labels
Closes #2364 
Closes #2060 
Adwaita reference (yes they have rounded bottom borders)

Style the complete HDY window inclusive top/bottom

---

icons/Suru/16x16/mimetypes/text-x-r-source.png
icons/Suru/16x16@2x/mimetypes/text-x-r-source.png
icons/Suru/24x24/mimetypes/text-x-r-source.png
icons/Suru/24x24@2x/mimetypes/text-x-r-source.png
icons/Suru/256x256/mimetypes/text-x-r-source.png
icons/Suru/256x256@2x/mimetypes/text-x-r-source.png
icons/Suru/32x32/mimetypes/text-x-r-source.png
icons/Suru/32x32@2x/mimetypes/text-x-r-source.png
icons/Suru/48x48/mimetypes/text-x-r-source.png
icons/Suru/48x48@2x/mimetypes/text-x-r-source.png
icons/src/symlinks/fullcolor/mimetypes.list

hi,
this will symlink **text-x-r-source** to **text-x-r**
Thanks!

symlink text-x-r-source to text-x-r

---

gtk/src/default/gtk-3.20/_apps.scss

Fix nautilus icon view backdrop text

---

gtk/src/default/gtk-3.20/_apps.scss

Merging https://github.com/ubuntu/yaru/pull/2397/commits/510b19e12766af61df62649303eb5b60ecaf18d1

Groovy: Fix nautilus icon view backdrop text

---

.github/lpbugtracker.py

"--label" flag does not exist. The right flag name is "-l".

Fix label HUB flag.

---

icons/Suru/scalable/actions/view-sidebar-symbolic.svg

Add missing view-sidebar symbolic icon

---

gtk/src/default/gtk-3.20/libhandy/_Adwaita-base.scss

Fix Libhandy needs-attention color

---

gtk/src/default/gtk-3.20/libhandy/_fallback-base.scss

- Add HdyStatusPage widget 
(https://gitlab.gnome.org/GNOME/libhandy/-/merge_requests/638)
- Add HdyFlap widget 
(https://gitlab.gnome.org/GNOME/libhandy/-/merge_requests/562)

Sync libhandy with upstream

---

icons/src/cursors/test/csscursors.html

Add all these cursors to csscursors.html:
- context-menu
- cell
- grab
- grabbing
- no-drop
- alias
- copy
- nesw-resize
- nwse-resize
- zoom-in
- zoom-out

Add more cursors to csscursors.html

---

gtk/src/default/gtk-3.20/_headerbar.scss
gtk/src/default/gtk-3.20/gtk.scss
gtk/src/default/gtk-3.20/libhandy/_Adwaita-base.scss
gtk/src/default/gtk-3.20/libhandy/_headerbar.scss

Fix Libhandy headerbar sidebar separator background

---

icons/Suru/16x16/mimetypes/application-x-xpinstall.png
icons/Suru/16x16@2x/mimetypes/application-x-xpinstall.png
icons/Suru/24x24/mimetypes/application-x-xpinstall.png
icons/Suru/24x24@2x/mimetypes/application-x-xpinstall.png
icons/Suru/256x256/mimetypes/application-x-xpinstall.png
icons/Suru/256x256@2x/mimetypes/application-x-xpinstall.png
icons/Suru/32x32/mimetypes/application-x-xpinstall.png
icons/Suru/32x32@2x/mimetypes/application-x-xpinstall.png
icons/Suru/48x48/mimetypes/application-x-xpinstall.png
icons/Suru/48x48@2x/mimetypes/application-x-xpinstall.png
icons/src/symlinks/fullcolor/mimetypes.list

Link application-x-addon to application-x-xpinstall
Closes #2531
Related to #2334

Add XPInstall (.xpi) mimetype

---

icons/Suru/16x16/mimetypes/application-x-msdownload.png
icons/Suru/16x16@2x/mimetypes/application-x-msdownload.png
icons/Suru/24x24/mimetypes/application-x-msdownload.png
icons/Suru/24x24@2x/mimetypes/application-x-msdownload.png
icons/Suru/256x256/mimetypes/application-x-msdownload.png
icons/Suru/256x256@2x/mimetypes/application-x-msdownload.png
icons/Suru/32x32/mimetypes/application-x-msdownload.png
icons/Suru/32x32@2x/mimetypes/application-x-msdownload.png
icons/Suru/48x48/mimetypes/application-x-msdownload.png
icons/Suru/48x48@2x/mimetypes/application-x-msdownload.png
icons/src/symlinks/fullcolor/mimetypes.list

Link application-octet-stream to application-x-msdownload
Closes #2529
Related to #2334

Add msdownload (.dll) mimetype

---

gtksourceview/meson.build
gtksourceview/src/dark.xml.in
gtksourceview/src/light.xml.in
gtksourceview/src/meson.build
meson.build
meson_options.txt

This adds dark and light GtkSourceView styles that use a colour palette that matches Yaru.

gtksourceview: Add dark and light styles (Yaru-MATE)

---

gtksourceview/meson.build
gtksourceview/src/dark.xml.in
gtksourceview/src/light.xml.in
gtksourceview/src/meson.build
meson.build
meson_options.txt

This adds dark and light GtkSourceView styles that use a colour palette matching Yaru.

gtksourceview: Add dark and light styles

---

gtk/src/default/gtk-3.20/_apps.scss

round menus for mate

---

gtk/src/default/gtk-3.20/_apps.scss

- dark terminal in default + dark
- properly style OSDs and their progressbar
- clean-ups

terminal and osd improvements

---

metacity/src/dark/metacity-1/unmaximize_focused_normal.svg
metacity/src/dark/metacity-1/unmaximize_focused_prelight.svg
metacity/src/dark/metacity-1/unmaximize_focused_pressed.svg
metacity/src/dark/metacity-1/unmaximize_unfocused.svg
metacity/src/dark/metacity-1/unmaximize_unfocused_prelight.svg
metacity/src/dark/metacity-1/unmaximize_unfocused_pressed.svg
metacity/src/default/metacity-1/unmaximize_focused_normal.svg
metacity/src/default/metacity-1/unmaximize_focused_prelight.svg
metacity/src/default/metacity-1/unmaximize_focused_pressed.svg
metacity/src/default/metacity-1/unmaximize_unfocused.svg
metacity/src/default/metacity-1/unmaximize_unfocused_prelight.svg
metacity/src/default/metacity-1/unmaximize_unfocused_pressed.svg
metacity/src/light/metacity-1/close_unfocused_pressed.svg
metacity/src/light/metacity-1/unmaximize_focused_normal.svg
metacity/src/light/metacity-1/unmaximize_focused_prelight.svg
metacity/src/light/metacity-1/unmaximize_focused_pressed.svg
metacity/src/light/metacity-1/unmaximize_unfocused.svg
metacity/src/light/metacity-1/unmaximize_unfocused_prelight.svg
metacity/src/light/metacity-1/unmaximize_unfocused_pressed.svg
metacity/src/metacity-theme-1.xml.in

When a window is maximized, the maximize button will change to reflect that the window can only be unmaximized.

metacity: Add unmaximize buttons

---

gtk/src/default/gtk-3.20/_apps.scss

Mate fix dialogs

---

CONTRIBUTING.md

This PR add Gtk4 install instructions to CONTRIBUTING.md

Add Gtk4 install instructions

---

gtk/src/default/gtk-4.0/_tweaks.scss

There was a comma missing.
Closes #2597

Fix parsing error

---

.github/workflows/open-pr-on-changes.yaml

This time it should works. Sorry for the mess 😓

RE: Update open-pr-on-changes.yaml

---

gtk/src/default/gtk-3.20/_tweaks.scss
gtk/src/default/gtk-4.0/_tweaks.scss

Gtk4 theme fix tab fg color

---

icons/Suru/scalable/actions/value-decrease-symbolic.svg
icons/Suru/scalable/actions/value-increase-symbolic.svg
icons/src/scalable/actions/value-decrease-symbolic.svg
icons/src/scalable/actions/value-increase-symbolic.svg

Add in/decrease symbolics icons

---

gtk/src/default/gtk-4.0/_headerbar.scss

Remove -gtk-icon-effect from GTK4 _headerbar

---

.github/workflows/open-pr-on-changes.yaml

Use different branch for each Github Action upstream projects

---

gtk/src/default/gtk-4.0/_tweaks.scss

Add missing GTK4 close button active state

---

.github/workflows/build-ci.yaml

Add very simple Build CI test using Github Action.

Add Build CI test

---

gtk/src/default/gtk-4.0/_tweaks.scss

Tweaks Gtk4 sliders

---

gnome-shell/src/gnome-shell-sass/widgets/_misc.scss
gnome-shell/src/gnome-shell-sass/widgets/_slider.scss

ShellTheme: fixes for sliders and avatar

---

gtk/src/default/gtk-3.20/_drawing.scss
gtk/src/default/gtk-3.20/_tweaks.scss

GtkTheme: dark switch improvements

---

gtk/src/default/gtk-3.20/_drawing.scss
gtk/src/default/gtk-4.0/_tweaks.scss

Fix sliders background overflow

---

gtk/src/default/gtk-3.20/_colors.scss
gtk/src/default/gtk-4.0/_colors.scss

gtk: Slighlty lighten up dark alt borders

gtk: Slighlty lighten up dark alt borders

---

gnome-shell/src/gnome-shell-sass/widgets/_app-grid.scss
gnome-shell/src/gnome-shell-sass/widgets/_calendar.scss
gnome-shell/src/gnome-shell-sass/widgets/_dialogs.scss
gnome-shell/src/gnome-shell-sass/widgets/_misc.scss
gnome-shell/src/gnome-shell-sass/widgets/_slider.scss
gnome-shell/src/gnome-shell-sass/widgets/_switcher-popup.scss
gnome-shell/upstream/data/gnome-shell-theme.gresource.xml
gnome-shell/upstream/gnome-shell-high-contrast.scss
gnome-shell/upstream/gnome-shell-sass/_colors.scss
gnome-shell/upstream/gnome-shell-sass/_common.scss
gnome-shell/upstream/gnome-shell-sass/_high-contrast-colors.scss
gnome-shell/upstream/gnome-shell-sass/widgets/_app-grid.scss
gnome-shell/upstream/gnome-shell-sass/widgets/_base.scss
gnome-shell/upstream/gnome-shell-sass/widgets/_calendar.scss
gnome-shell/upstream/gnome-shell-sass/widgets/_dash.scss
gnome-shell/upstream/gnome-shell-sass/widgets/_dialogs.scss
gnome-shell/upstream/gnome-shell-sass/widgets/_login-dialog.scss
gnome-shell/upstream/gnome-shell-sass/widgets/_message-list.scss
gnome-shell/upstream/gnome-shell-sass/widgets/_misc.scss
gnome-shell/upstream/gnome-shell-sass/widgets/_overview.scss
gnome-shell/upstream/gnome-shell-sass/widgets/_panel.scss
gnome-shell/upstream/gnome-shell-sass/widgets/_search-entry.scss
gnome-shell/upstream/gnome-shell-sass/widgets/_window-picker.scss
gnome-shell/upstream/gnome-shell-sass/widgets/_workspace-thumbnails.scss
gnome-shell/upstream/meson.build

Resync stuff from upstream 3.38 branch.
@Feichtmeier there are some changes we were keeping that are not upstream anymore, mostly the switcher values and the polkit dialog icon (that should not change though), so please ensure that this keeps following what we expected.

Gnome 3.38 resync

---

icons/Suru/16x16/apps/update-notifier.png
icons/Suru/16x16@2x/apps/update-notifier.png
icons/Suru/24x24/apps/update-notifier.png
icons/Suru/24x24@2x/apps/update-notifier.png
icons/Suru/256x256/apps/update-notifier.png
icons/Suru/256x256@2x/apps/update-notifier.png
icons/Suru/32x32/apps/update-notifier.png
icons/Suru/32x32@2x/apps/update-notifier.png
icons/Suru/48x48/apps/update-notifier.png
icons/Suru/48x48@2x/apps/update-notifier.png
icons/src/symlinks/fullcolor/apps.list

@madsrh Can you test this please?
Closes #2720

Add symlink for update-notifier icon

---

icons/src/cursors/render-cursors.py

Rework render cursor script to
- re-enable parallel rendering using multiple instances of inkscape (v1.0)
- use proper logging
- improve code legibility

Rework render cursor script

---

gtk/src/default/gtk-3.20/apps/_nautilus.scss

- only color the selected row gray in backdrop
Closes #2822

Gtk3 Nautilus list view change

---

gtk/src/default/gtk-3.20/_tweaks.scss
gtk/src/default/gtk-4.0/_tweaks.scss

related https://github.com/ubuntu/yaru/issues/2539

GtkThemes: revert to upstreams app notifications

---

gtk/src/default/gtk-3.20/_palette.scss
gtk/src/default/gtk-3.20/_tweaks.scss

This reverts commit 456a67907a2df08c7742b301f05b979fa97ed0af.

Revert "Aubergine experiment! Crappy code ONLY FOR  TESTING!"

---

gtk/src/default/gtk-3.20/_tweaks.scss

Fix selected row hover background.

Fix selected row hover background

---

gtk/src/default/gtk-3.20/_tweaks.scss

@Muqtxdir Can you confirm it fix the problem of red button, please?

Fix missing red button into some apps

---

icons/Suru/scalable/actions/crop-symbolic.svg
icons/src/scalable/actions/crop-symbolic.svg

Add missing crop-symbolic icon

---

gnome-shell/src/gnome-shell-sass/_common.scss
gnome-shell/src/gnome-shell-sass/_drawing.scss
gnome-shell/src/gnome-shell-sass/widgets/_app-grid.scss
gnome-shell/src/gnome-shell-sass/widgets/_entries.scss
gnome-shell/src/gnome-shell-sass/widgets/_message-list.scss
gnome-shell/src/gnome-shell-sass/widgets/_search-entry.scss

Sync our GS theme with upstream.
**Note:** they dropped entries border, so I reintroduce them.

Sync GS with upstream

---

create-new-variant.md

Fix code block formatting so markdown parser shows each section properly

Fix code block formatting

---

.github/workflows/open-pr-on-icons-changes.yaml

Hi,
This PR will add the ubuntu pre-installed GNOME Apps to `open-pr-on-icon-changes.yaml`
related: #3033

add pre-installed apps to list

---

icons/Suru/scalable/emblems/app-remove-symbolic.svg

add symlink app-remove-symbolic.svg

---

gtk/src/default/gtk-3.20/_tweaks.scss

Gtk3 fix treeview progressbar

---

gnome-shell/src/gnome-shell-high-contrast.scss

Add missing dock styles to GS hc variant.

Add dock styles to GS hc variant

---

gnome-shell/src/gnome-shell-high-contrast.scss

relevant issue: #3090 
screen-recording:
https://user-images.githubusercontent.com/54065734/136252518-32ca097c-571e-4732-a6b5-31f707f410ec.mp4

high-contrast: fix for using correct hc-toggles

---

gnome-shell/src/gnome-shell-sass/widgets/_slider.scss

Gnome shell sync slide handle

---

gtk/src/default/gtk-3.20/_apps.scss
gtk/src/default/gtk-3.20/apps/_brisk-menu.scss
gtk/src/default/gtk-3.20/apps/_caja.scss
gtk/src/default/gtk-3.20/apps/_mate-multimedia-osd.scss
gtk/src/default/gtk-3.20/apps/_mate-terminal.scss
gtk/src/default/gtk-3.20/apps/_mate.scss

Include all Mate apps styling directly in master.

Include Mate apps styling in master

---

gtk/src/default/gtk-3.20/libhandy/_fallback-base.scss

Sync with upstream.
Related to #3210 and https://gitlab.gnome.org/GNOME/libhandy/-/merge_requests/789

Remove adaptive margins for preferences

---

gnome-shell/src/gnome-shell-sass/_common.scss

Related upstream MR: **Provide :checked state for buttons** (https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2027)
Related to #3213

Sync GS with upstream: Provide :checked state for buttons

---

gtk/src/default/gtk-4.0/_defaults.scss

Related MR: https://gitlab.gnome.org/GNOME/libadwaita/-/merge_requests/346
Related to #3221

Sync _defaults with upstream

---

meson_options.txt

Set mate flavour `false` by default.
I committed by mistake the `true` value in the previous PR.

Set mate flavour false by default

---

gtksourceview/meson.build
gtksourceview/src/dark.xml.in
gtksourceview/src/default.xml.in
gtksourceview/src/mate-dark.xml.in
gtksourceview/src/mate.xml.in
gtksourceview/src/meson.build

Add `gtksourceview` **mate** and **mate-dark** variants.

Add gtksourceview mate and mate-dark variants

---

gtk/src/default/gtk-4.0/_colors-yaru.scss
gtk/src/default/gtk-4.0/_defaults.scss
gtk/src/default/gtk-4.0/_tweaks.scss

Use upstream `$success` color vars instead of our `$suggested` ones.
Related to #3251

Use $success instead of $suggested

---

icons/Yaru/scalable/apps/org.gnome.Usage-symbolic.svg
icons/src/symlinks/symbolic/apps.list

Add **org.gnome.Usage-symbolic** symlink icon
Related to #3250

Add org.gnome.Usage-symbolic symlink icon

---

gtk/src/default/gtk-3.0/_common.scss
gtk/src/default/gtk-3.0/_tweaks.scss

Drop grey selected rows

---

gtk/src/default/gtk-3.0/_tweaks.scss
gtk/src/default/gtk-4.0/_tweaks.scss

unify all titlebuttons to a soft gray

---

icons/Yaru/scalable/actions/document-revert-rtl-symbolic.svg
icons/Yaru/scalable/actions/format-text-direction-rtl-symbolic-rtl.svg
icons/src/symlinks/symbolic/actions.list

Just add some symlinks.
See #3281

Add some symlinks

---

debian/changelog

- sync debian/changelog from `ubuntu/impish`

update changelog to show changes made in 21.10.2

---

gnome-shell/src/gnome-shell-sass/widgets/_looking-glass.scss

Sync Gnome Shell with upstream
Related to #3302

Sync Gnome Shell with upstream

---

CONTRIBUTING.md

- adds a build unsigned deb files from source section in `CONTRIBUTING.MD`

issue no #3221 add instructions for debian files

---

.github/workflows/open-pr-on-changes.yaml

Add Cinnamon theme upstream fetch (https://github.com/linuxmint/mint-themes/tree/master/src/Mint-Y/cinnamon).

Add Cinnamon theme upstream fetch

---

gtk/src/default/gtk-3.0/libhandy/_Adwaita-base.scss

Sync Libadwaita with upstream

---

icons/README.md

**What is this change?**
This change corrects some spelling mistakes in  `/yaru/icons/README.md`
**Why is this change necessary?**
This minor improvement will give readers a more polished reading experience.

Correct typos in Yaru icons README

---

icons/Yaru/scalable/actions/go-jump-rtl-symbolic.svg
icons/Yaru/scalable/status/semi-starred-rtl-symbolic.svg
icons/Yaru/scalable/status/view-wrapped-rtl-symbolic.svg
icons/src/symlinks/symbolic/actions.list
icons/src/symlinks/symbolic/status.list

Sync symbolic icons with upstream.
See #3358

Sync symbolic icons with upstream

---

gnome-shell/upstream/theme/gnome-shell-sass/widgets/_screenshot.scss

Revert "Auto update new upstream snapshot for GNOME Shell"

---

gtk/src/default/gtk-3.0/_colors.scss
gtk/src/default/gtk-3.0/apps/_mate.scss

Make MATE panel dark

---

icons/Yaru/scalable/actions/review-symbolic.svg
icons/src/scalable/actions/review-symbolic.svg

**review-symbolic:**
Related to #3383

Add review-symbolic icon 3383

---

icons/Yaru/scalable/apps/help-link-symbolic.svg
icons/src/symlinks/symbolic/apps.list

Just symlink `help-app-symbolic.svg` to `help-link-symbolic.svg`.
Related to #3390

Sync icon theme with upstream

---

.github/workflows/open-pr-on-changes.yaml

Added support for icon gresource file

open-pr-on-changes: Include gnome-shell icons

---

gtk/src/default/gtk-3.0/_common.scss

Fix Gtk3 headerbar radius

---

gtk/src/mate-dark/gtk-4.0/_colors-yaru.scss
gtk/src/mate-dark/gtk-4.0/_colors.scss
gtk/src/mate-dark/gtk-4.0/_common.scss
gtk/src/mate-dark/gtk-4.0/_compat-colors.scss
gtk/src/mate-dark/gtk-4.0/_defaults.scss
gtk/src/mate-dark/gtk-4.0/_drawing.scss
gtk/src/mate-dark/gtk-4.0/_functions.scss
gtk/src/mate-dark/gtk-4.0/_palette.scss
gtk/src/mate-dark/gtk-4.0/_tweaks.scss
gtk/src/mate-dark/gtk-4.0/_widgets.scss
gtk/src/mate-dark/gtk-4.0/widgets

Fix Yaru-mate-dark symlinks

---

gtk/src/default/gtk-3.0/_common.scss

Fix dialog border-radius

---

gnome-shell/src/gnome-shell-sass/_drawing.scss
gnome-shell/src/gnome-shell-sass/widgets/_search-entry.scss

**Note:** the diff in `_search-entry.scss` is a sync with upstream file.
**Before:**
https://user-images.githubusercontent.com/36476595/156322782-b4dc0741-87e8-4977-aacf-d833b2880e09.mp4
**After:**
https://user-images.githubusercontent.com/36476595/156322801-f3175f21-98de-45a1-b494-231ce7f086ff.mp4

Fix search entry look

---

gnome-shell/src/gnome-shell-sass/widgets/_slider.scss

Fix slider in light theme

---

gnome-shell/src/gnome-shell-sass/_common.scss
gnome-shell/src/gnome-shell-sass/_drawing.scss

Fixe GS buttons look

---

gnome-shell/src/gnome-shell-sass/widgets/_calendar.scss

Fix calendar insensitive label

---

gnome-shell/src/gnome-shell-sass/_common.scss
gnome-shell/src/gnome-shell-sass/widgets/_app-grid.scss
gnome-shell/src/gnome-shell-sass/widgets/_dash.scss
gnome-shell/src/gnome-shell-sass/widgets/_message-list.scss
gnome-shell/src/gnome-shell-sass/widgets/_search-results.scss
gnome-shell/src/gnome-shell-sass/widgets/_switcher-popup.scss

Sync Gnome Shell with upstream 3444

---

gnome-shell/src/gnome-shell-sass/widgets/_login-dialog.scss

Style login dialog entry unfocused state

---

gnome-shell/src/gnome-shell-sass/widgets/_app-grid.scss

Fix page navigation arrow

---

gnome-shell/src/gnome-shell-sass/_colors.scss
gnome-shell/src/gnome-shell-sass/_common.scss
gnome-shell/src/gnome-shell-sass/widgets/_app-grid.scss

Fix app folder edit button

---

icons/Yaru/16x16/apps/timeshift.png
icons/Yaru/16x16@2x/apps/timeshift.png
icons/Yaru/24x24/apps/timeshift.png
icons/Yaru/24x24@2x/apps/timeshift.png
icons/Yaru/256x256/apps/timeshift.png
icons/Yaru/256x256@2x/apps/timeshift.png
icons/Yaru/32x32/apps/timeshift.png
icons/Yaru/32x32@2x/apps/timeshift.png
icons/Yaru/48x48/apps/timeshift.png
icons/Yaru/48x48@2x/apps/timeshift.png
icons/Yaru/scalable/apps/timeshift-symbolic.svg
icons/src/symlinks/fullcolor/apps.list
icons/src/symlinks/symbolic/apps.list

added symlink to timeshift

---

gnome-shell/src/gnome-shell-sass/widgets/_looking-glass.scss

Fix looking glass entry look

---

gnome-shell/src/gnome-shell-sass/_dock.scss

**Before:**
**After:**
CC @Muqtxdir

Fix dock item border-radius

---

icons/src/symlinks/generate-symlinks.sh

Rework generate-symlink.sh to improve readability of the code and of the error reports

Improve icons build scripts

---

gtk/src/default/gtk-3.0/_apps.scss
gtk/src/default/gtk-3.0/apps/_ding.scss

Add ding styling

---

.github/workflows/open-pr-on-optimized-symbolic-icons-changes.yaml
.github/workflows/open-pr-on-rendered-icons-changed.yaml
icons/meson.build
icons/src/fullcolor/render-bitmaps.py

Leave to CI what's its job, so that we don't forget to do it...

CI: Render and optimize icons

---

gtk/src/default/gtk-3.0/apps/_nautilus.scss

**Normal:**
**Backdrop:**
**Normal:**
**Backdrop:**
Closes #2899

Restyle nautilus infobar

---

gtk/src/default/gtk-3.0/apps/_nautilus.scss

**Before:**
https://user-images.githubusercontent.com/36476595/159352691-42ab835c-93c3-4dc9-9bf8-2179c5d5355f.mp4
**After:**
https://user-images.githubusercontent.com/36476595/159352750-5c117296-0fa5-4ec2-a6f6-6650fb79ce0f.mp4
CC @Muqtxdir

Force border-radius of nautilus-canvas-item in focus state

---

gtk/src/default/gtk-3.0/_colors.scss
gtk/src/default/gtk-3.0/apps/_mate.scss

Reverts #3378
This require to create a `mate-dark` icon theme variant before merging.

Revert "Make MATE panel dark"

---

gtk/src/default/gtk-3.0/apps/_caja.scss

Closes #3537
CC @flexiondotorg

Fix invisible caret in caja desktop rename entry

---

metacity/src/dark/metacity-theme-1.xml.in
metacity/src/default/metacity-theme-1.xml.in

This pull request adds window buttons to modal windows. 
- See https://pad.lv/1917185
- Closes #3558

metacity: Add window buttons to modal windows. Fixes #3558

---

gnome-shell/src/gnome-shell-sass/widgets/_calendar.scss

**Before:**
https://user-images.githubusercontent.com/36476595/161377787-2ccf72cd-6a7b-4bf8-b04b-061ebca3969a.mp4
**After:**
https://user-images.githubusercontent.com/36476595/161377788-ba5478b8-3569-498d-bbea-de3f8f9e14d5.mp4
Closes #3579

GS: fix fg_color of unfocused selected calendar day

---

gnome-shell/src/gnome-shell-sass/widgets/_login-dialog.scss

https://user-images.githubusercontent.com/36476595/161377104-711d3365-d1e1-4400-8c28-aa160d49f771.mp4
Closes #3580

GS: fix lock screen switch user button in light theme

---

gnome-shell/src/gnome-shell-sass/widgets/_entries.scss

Reintroduce https://github.com/ubuntu/yaru/pull/1462/commits/26919369bc549673e880b2ef683478d847906b12 from #1462

GS: fix for entries height shift

---

gnome-shell/src/gnome-shell-sass/widgets/_notifications.scss

Fix notifications shadow (revert to upstream look).

Fix notifications shadow (revert to upstream look)

---

gtk/src/default/gtk-3.0/apps/_nautilus.scss

**Before:**
https://user-images.githubusercontent.com/36476595/162835026-60ac68d9-47aa-43f6-9435-a54b07debd7e.mp4
**After:**
https://user-images.githubusercontent.com/36476595/162835873-3b0b9755-4c96-41ce-96a3-12c3d7d777ff.mp4
Closes #3605

Nautilus drop image preview border-radius

---

gtk/src/default/gtk-3.0/apps/_nautilus.scss

**Before:**
**After:**
CC @madsrh 
Closes #3599

Nautilus fix selected item

---

gnome-shell/src/gnome-shell-sass/widgets/_calendar.scss
gnome-shell/src/gnome-shell-sass/widgets/_osd.scss

Sync gnome-shell with upstream

---

gtk/src/default/gtk-3.0/_tweaks.scss

Fix slider states

---

gtk/src/default/gtk-3.0/_tweaks.scss

**Before:**
https://user-images.githubusercontent.com/36476595/167111128-90aaa6b2-34d0-452d-9987-eda19c0e2da1.mp4
**After:**
https://user-images.githubusercontent.com/36476595/167111135-8d372598-b8cf-4bd0-9028-c61c49163dfe.mp4
Closes #3617

Gtk3: fix marks scale

---

gtk/src/default/gtk-3.0/_tweaks.scss

**Before:**
**After:**
Closes  #3611

Gtk3: fix invisible check and radio in selected row

---

gtk/src/default/gtk-3.0/_common.scss

Sync Gtk3 with upstream

---

cinnamon-shell/src/cinnamon-dark/dark-assets/checkbox/radio-checked.svg
cinnamon-shell/src/cinnamon-dark/dark-assets/checkbox/radio-unchecked.svg
cinnamon-shell/src/cinnamon/light-assets/checkbox/radio-checked.svg
cinnamon-shell/src/cinnamon/light-assets/checkbox/radio-unchecked.svg
cinnamon-shell/src/dark/dark-assets/checkbox/radio-checked.svg
cinnamon-shell/src/dark/dark-assets/checkbox/radio-unchecked.svg
cinnamon-shell/src/default/_tweaks.scss
cinnamon-shell/src/default/light-assets/checkbox/radio-checked.svg
cinnamon-shell/src/default/light-assets/checkbox/radio-unchecked.svg

Sync Cinnamon with upstream #3647

---

metacity/src/dark/metacity-theme-1.xml.in

Backport #3677 to `ubuntu/jammy`.

Backport #3677

---

.github/workflows/build-ci.yaml
.github/workflows/build-deb.yaml

Try skip duplicated CI on push/PR

---

icons/Yaru/scalable/categories/org.gnome.Settings-screen-lock-symbolic.svg
icons/Yaru/scalable/categories/org.gnome.Settings-screen-symbolic.svg
icons/src/symlinks/symbolic/categories.list

Sync icons theme with upstream #3710

Sync icon theme with upstream #3710

---

gnome-shell/src/gnome-shell-sass/widgets/_quick-settings.scss

Sync Gnome Shell with upstream.
Related to #3718

Sync Gnome Shell with upstream #3718

---

icons/Yaru/16x16/apps/org.gnome.FileRoller.png
icons/Yaru/16x16/apps/org.gnome.Rhythmbox3.png
icons/Yaru/16x16@2x/apps/org.gnome.FileRoller.png
icons/Yaru/16x16@2x/apps/org.gnome.Rhythmbox3.png
icons/Yaru/24x24/apps/org.gnome.FileRoller.png
icons/Yaru/24x24/apps/org.gnome.Rhythmbox3.png
icons/Yaru/24x24@2x/apps/org.gnome.FileRoller.png
icons/Yaru/24x24@2x/apps/org.gnome.Rhythmbox3.png
icons/Yaru/256x256/apps/org.gnome.FileRoller.png
icons/Yaru/256x256/apps/org.gnome.Rhythmbox3.png
icons/Yaru/256x256@2x/apps/org.gnome.FileRoller.png
icons/Yaru/256x256@2x/apps/org.gnome.Rhythmbox3.png
icons/Yaru/32x32/apps/org.gnome.FileRoller.png
icons/Yaru/32x32/apps/org.gnome.Rhythmbox3.png
icons/Yaru/32x32@2x/apps/org.gnome.FileRoller.png
icons/Yaru/32x32@2x/apps/org.gnome.Rhythmbox3.png
icons/Yaru/48x48/apps/org.gnome.FileRoller.png
icons/Yaru/48x48/apps/org.gnome.Rhythmbox3.png
icons/Yaru/48x48@2x/apps/org.gnome.FileRoller.png
icons/Yaru/48x48@2x/apps/org.gnome.Rhythmbox3.png
icons/Yaru/scalable/apps/org.gnome.FileRoller-symbolic.svg
icons/Yaru/scalable/apps/org.gnome.Rhythmbox3-symbolic.svg
icons/src/symlinks/fullcolor/apps.list
icons/src/symlinks/symbolic/apps.list

@vitalkanev have you got the possibility to test this PR?
Fixes #3727

Archive Manager and Rhythmbox icon are upstream

---

icons/src/fullcolor/render-bitmaps.py

The script was unable to render all icons.

Fix render-bitmaps.py

---

gnome-shell/src/gnome-shell-sass/_drawing.scss
gnome-shell/src/gnome-shell-sass/widgets/_quick-settings.scss

**Before:**
**After:**
Fixes #3716

Tone down accents from quick settings

---

gtk/src/default/gtk-4.0/_common.scss

Sync Gtk4 with upstream #3739

---

gtk/src/default/gtk-4.0/_common.scss

Sync gtk4 with upstream #3750

---

icons/Yaru/16x16/mimetypes/application-x-audacity-project+sqlite3.png
icons/Yaru/16x16@2x/mimetypes/application-x-audacity-project+sqlite3.png
icons/Yaru/24x24/mimetypes/application-x-audacity-project+sqlite3.png
icons/Yaru/24x24@2x/mimetypes/application-x-audacity-project+sqlite3.png
icons/Yaru/256x256/mimetypes/application-x-audacity-project+sqlite3.png
icons/Yaru/256x256@2x/mimetypes/application-x-audacity-project+sqlite3.png
icons/Yaru/32x32/mimetypes/application-x-audacity-project+sqlite3.png
icons/Yaru/32x32@2x/mimetypes/application-x-audacity-project+sqlite3.png
icons/Yaru/48x48/mimetypes/application-x-audacity-project+sqlite3.png
icons/Yaru/48x48@2x/mimetypes/application-x-audacity-project+sqlite3.png
icons/src/symlinks/fullcolor/mimetypes.list

LP#1991461 Add icon for .aup3 Audacity mime type

---

gtk/src/default/gtk-4.0/_common.scss

Sync Gtk4 with upstream

---

gtk/src/default/gtk-3.0/_apps.scss
gtk/src/default/gtk-3.0/apps/_evince.scss

| Before | After | 
| --------- | ------- | 
| ![Capture d’écran du 2022-11-18 18-35-47](https://user-images.githubusercontent.com/36476595/202768386-68c8a8ee-03ab-45b0-ba50-0bbe11790058.png) | ![Capture d’écran du 2022-11-18 18-28-05](https://user-images.githubusercontent.com/36476595/202768400-ee210fc6-1b6d-45b0-939d-c9dccdf9cc38.png) |
Fixes #3768

Evince: darker view background

---

cinnamon-shell/src/default/_colors.scss

I reused colors from #3278
Related to #3278

Sync Cinnamon theme with upsteam

---

.github/workflows/open-pr-on-icons-changes.yaml

See: https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/commit/079d4ca868f53f868771f6e0ff99ba729c430e69

Sync upstream Adwaita icons foler

---

cinnamon-shell/src/default/_colors.scss

Sync cinnamon with upstream

---

cinnamon-shell/src/default/_colors.scss
cinnamon-shell/src/default/_tweaks.scss

**Before:**
**After:**
Fixes #3781

Fix noaccented panel colors

---

gtk/src/default/gtk-4.0/_common.scss

They just added new feature, so no compatibility problem.
Related to #3803

Sync gtk4 with upstream #3803

---

gtk/src/default/gtk-3.0/_tweaks.scss

| Current | PR |
| --- | --- |
| ![Capture d’écran du 2023-01-05 15-49-35](https://user-images.githubusercontent.com/36476595/210807924-113db750-78d7-467c-ac47-81395c3a5333.png) | ![Capture d’écran du 2023-01-05 15-49-18](https://user-images.githubusercontent.com/36476595/210807933-5f7de795-99d0-43df-b566-f4b5b30e66d0.png) |
Fixes #3809

Add soft light border to libhandy apps

---

gnome-shell/src/gnome-shell-sass/widgets/_slider.scss

LP#1989844 "Quick settings changes spacing when toggling Dark Mode"

---

gnome-shell/src/gnome-shell-sass/widgets/_login-lock.scss

Fix GDM 44 look

---

gtk/src/default/gtk-4.0/_tweaks.scss

Fix default decoration windowcontrols sizes

---

gnome-shell/src/gnome-shell-sass/_drawing.scss
gnome-shell/src/gnome-shell-sass/widgets/_looking-glass.scss

**Before:**
**After:**
Closes #3887, closes #3881

GS: fix light theme invisible text

---

.github/workflows/open-pr-on-changes.yaml
.github/workflows/open-pr-on-icons-changes.yaml
.github/workflows/open-pr-on-optimized-symbolic-icons-changes.yaml
.github/workflows/open-pr-on-rendered-icons-changed.yaml

Manually bump version to include a permission fix.
See: https://github.com/peter-evans/create-pull-request/issues/1873#issuecomment-1507796357
Replace #1406

Build(deps): bump peter-evans/create-pull-request from 4 to 5

---

cinnamon-shell/src/cinnamon-shell.scss.in
cinnamon-shell/src/meson.build

CI was failing at build cinnamon theme: https://github.com/ubuntu/yaru/actions/runs/5292303734/jobs/9579016929

Fix cinnamon build

---

gnome-shell/src/data/gnome-shell-icons.gresource.xml
gnome-shell/src/data/icons/scalable/actions/ornament-check-symbolic.svg
gnome-shell/src/data/icons/scalable/actions/ornament-dot-symbolic.svg

Sync Gnome Shell icons with upstream

---

cinnamon-shell/src/sass/_colors.scss
cinnamon-shell/src/sass/_palette.scss
cinnamon-shell/src/sass/_tweaks.scss

@Initu-Castilhos can you test this PR, and confirm that the panel look is fixed (use libadwaita headerbar color)?
Related to #3922

Cinnamon: Drop inverted panel, fix accent and cleanups

---

cinnamon-shell/src/sass/_tweaks.scss

@Initu-Castilhos can you test this PR, please?

Cinnamon: Fix menu-favorites-box background

---

icons/Yaru/16x16/mimetypes/application-x-zerosize.png
icons/Yaru/16x16@2x/mimetypes/application-x-zerosize.png
icons/Yaru/24x24/mimetypes/application-x-zerosize.png
icons/Yaru/24x24@2x/mimetypes/application-x-zerosize.png
icons/Yaru/256x256/mimetypes/application-x-zerosize.png
icons/Yaru/256x256@2x/mimetypes/application-x-zerosize.png
icons/Yaru/32x32/mimetypes/application-x-zerosize.png
icons/Yaru/32x32@2x/mimetypes/application-x-zerosize.png
icons/Yaru/48x48/mimetypes/application-x-zerosize.png
icons/Yaru/48x48@2x/mimetypes/application-x-zerosize.png
icons/src/symlinks/fullcolor/mimetypes.list

**Before**
**After:**
Fixes #3948

Add missing application-x-zerosize mimetype

---

gnome-shell/src/gnome-shell-sass/widgets/_panel.scss

Revert panel height to upstream

---

gnome-shell/src/gnome-shell-sass/_common.scss
gnome-shell/src/gnome-shell-sass/_drawing.scss

GS: fix entries look

---

gnome-shell/src/gnome-shell-sass/widgets/_slider.scss

| | Before | After |
| --- | --- | --- |
| Light | ![Capture d’écran du 2023-09-09 22-49-31](https://github.com/ubuntu/yaru/assets/36476595/2869403e-b37e-43f7-984e-c27c1c5c15c4) | ![Capture d’écran du 2023-09-09 22-47-50](https://github.com/ubuntu/yaru/assets/36476595/b16b81b3-12a4-4b75-967b-162d6b205210) |
| Dark | ![Capture d’écran du 2023-09-09 22-49-36](https://github.com/ubuntu/yaru/assets/36476595/d569d787-a2e7-434d-bff6-b19d323dc18e) | ![Capture d’écran du 2023-09-09 22-47-58](https://github.com/ubuntu/yaru/assets/36476595/b7a62bdd-7200-434b-a64a-83e59bf553d0)

GS: fix slider height

---

gnome-shell/src/gnome-shell-sass/widgets/_looking-glass.scss

Fix looking glass extensions cards

---

gnome-shell/src/gnome-shell-sass/_dock.scss

Dock refininments

---

gnome-shell/src/gnome-shell-sass/_common.scss
gnome-shell/src/gnome-shell-sass/_drawing.scss
gnome-shell/src/gnome-shell-sass/widgets/_app-grid.scss
gnome-shell/src/gnome-shell-sass/widgets/_base.scss
gnome-shell/src/gnome-shell-sass/widgets/_calendar.scss
gnome-shell/src/gnome-shell-sass/widgets/_dash.scss
gnome-shell/src/gnome-shell-sass/widgets/_login-lock.scss
gnome-shell/src/gnome-shell-sass/widgets/_message-list.scss
gnome-shell/src/gnome-shell-sass/widgets/_overview.scss
gnome-shell/src/gnome-shell-sass/widgets/_search-results.scss
gnome-shell/src/gnome-shell-sass/widgets/_slider.scss
gnome-shell/src/gnome-shell-sass/widgets/_window-picker.scss
gnome-shell/src/gnome-shell-sass/widgets/_workspace-switcher.scss

Covers fixes for:
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7488
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7400
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6024
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7628
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7511
https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/issues/507
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7620
See also: https://github.com/ubuntu/yaru/pull/4061

gnome-shell: Sync fixes from gnome-46 branch

---

gtk/src/default/gtk-4.0/_colors-public.scss
gtk/src/default/gtk-4.0/_common.scss

Sync gtk4 update

---

debian/control
meson.build

As we're using some features included in such version

build: Depend on meson 0.60

---

gnome-shell/src/gnome-shell-sass/_dock.scss

Sync code with upstream so that we have styled badges in the overview and optimize their positioning for yaru

Dash to dock tunings
