Communitheme/gtk-3.0/_drawing.scss
_text_shadow_color is used in %needs_attention and button.color, so
it should be available
=> Uncommented _text_shadow_color

Communitheme/gtk-3.0/_common.scss
currently, stackswitcher buttons do not have the same hover effect than other buttons on a headerbar
This commit adds a hover target for this widget with:
- dark headerbar bg and fg color
- gtk-icon-effect highlight
=> Fixed stackswitcher button hover effect

Communitheme/gtk-3.0/_common.scss
Until stackswitcher buttons are not included in "normal" ones, we should keep their style aligned
=> Fixed again stackswitcher button hover effect

Communitheme/gtk-3.0/_common.scss, Communitheme/gtk-3.0/_drawing.scss, Communitheme/gtk-3.0/_ubuntu-colors.scss
To close issue #11:
- _backdrop_color function is used to desaturate colors
- Backdrop colors that relied on _backdrop_color are now variables
- Tidying up of infobar
- Tidying up of checkboxes and radio buttons
=> Desaturate colors in unfocused windows

Communitheme/gtk-3.0/_apps.scss, Communitheme/gtk-3.0/_common.scss, Communitheme/gtk-3.0/_drawing.scss
Closes issue #19 and also fixes the problem with GNOME Software's stackswitcher-like buttons
=> Headerbar buttons now have no border on hover/active

Communitheme/gtk-3.0/_colors.scss
- transparentize by 0.6 insensitive (disabled) button borders to make
them less visible
- reduced darkness of background color from 12% to 7%
current version
new version
closes #13
=> Improved difference between enabled and disabled dropdown buttons

Communitheme/gtk-3.0/_colors.scss
- differentiate hover color for light and dark themes
- light themes, color is now lighter by 7% than bg_color
- dark themes, color is now darker by 7% than bg_color
closes #21
=> Fixed popover menu hover color too light

Communitheme/gtk-3.0/_common.scss, Communitheme/gtk-3.0/_drawing.scss
Using blue for focused elements is closer to Unity 8's design and also fixes a couple visiblity issues for the focused elements (buttons especially, as they already use a grey color)
=> Standardize border-radius and use Suru blue for focused elements

Communitheme/gtk-3.0/_colors.scss, Communitheme/gtk-3.0/_common.scss, Communitheme/gtk-3.0/_drawing.scss
- Fixes the colour mixup with the dark theme (the colour for $bg_color was meant for $base_color and vice versa)
- Uses a color for the dark fill that's closer to Suru's
- Updates $osd_bg_color (to use the proper color from the dark theme)
- Hover and active background colors for modalbuttons
- Headerbar separators use a lighter color
- Standardize use of $c and $tc instead of $_fg and $_bg
- Replaces infobar mixin with a much more sensible loop
- Update dimensions and color for popover to match suru
p.s this will hopefully be the last of my messy pull requests :persevere:
=> Sass cleanup and tweaks for the dark theme and popover

Communitheme/gtk-3.0/_common.scss
- Headerbar buttons now have no hover effect in backdrop unless it's a window button (close, min, max, etc.)
- Headerbar separator uses a light grey color instead of a dark black
Closes #31 #25
=> Lighten headerbar separator, fix headerbar button issues when in backdrop state

Communitheme/gtk-3.0/_common.scss
The new hover color (grey) for menus leads to a white-on-grey visibility issue with checks and radios. This fixes that.
=> Fix menuitem checks and radios

Communitheme/gtk-3.0/_common.scss
This commit changes windows controls from this
to this
closes #40
=> added 5px horizontal margin to windows controls

Communitheme/gtk-3.0/_colors.scss, Communitheme/gtk-3.0/_common.scss, Communitheme/gtk-3.0/_drawing.scss
The styling for OSD buttons and other elements still use styling from Adwaita, this fixes that:
- OSD colors are based on Ubuntu colors
- OSD buttons look like normal buttons with bottom highlight
- Gtkscale elements look uniform no matter where they are (following Suru)
=> Update OSD elements

Communitheme/gtk-3.0/_common.scss, Communitheme/gtk-3.0/_drawing.scss
- Toolbar buttons are flat (headerbar buttons are flat and uses no 3d effect, flat buttons outside of the headerbar now follow suit)
- Button hover and active colors are darker to accomodate for the loss of 3d effect for flat buttons
=> Flat toolbar buttons

Communitheme/gtk-3.0/_common.scss, Communitheme/gtk-3.0/_ubuntu-colors.scss
- Update color palette
- GNOME Web's trough had a black box-shadow
=> Update color palette, fix GNOME web trough

Communitheme/gtk-3.0/_common.scss
%linked-middle defines border-style:none only for right border, then
when it's extended in linked:first-child causes the button to shrink
when hover or backdrop
closes #69
=> Remove border-right-style on %linked-middle

Communitheme/gtk-3.0/_common.scss
Moved text-decoration definition from button:link > label to
button:link:hover > label to let the link button be underlined only when
in hover state.
closes #75
=> Underline links only when hover

Communitheme/gtk-3.0/_colors.scss, Communitheme/gtk-3.0/_common.scss
Replaced dashed outline blue color with a solid orange one transparentized by 0.4
closes #84
=> Fixed dashed outline button color

Communitheme/gtk-3.0/_common.scss
Gtk+ nagged me about it on launching a graphical program from the terminal.
=> outline-radius property missing the “-gtk-” prefix in a couple of instances

Communitheme/gtk-3.0/_common.scss, Communitheme/gtk-3.0/_ubuntu-colors.scss
- Spinner uses _backdrop_color($blue) in backdrop
- Some linked entries would not have a colored border in focus
- Use $graphite for headerbar separators
- Change $headerbar_backdrop_* to $backdrop_headerbar_* for consistency
- Use $text_color in menus
- Notebook tabs have a separator
- Shorten switch shadow to 1px
- Remove inapplicable states for titlebuttons (checked, disabled, etc.)
- Restore hover + active effects for close button
Closes #104
=> Fix entry caret color, add headerbar separator, fix small issues

Communitheme/gtk-3.0/_common.scss
Added 15px as padding-top when in grid view only.
closes #109
=> Added more space between headerbar and canvas in Nautilus

Communitheme/gtk-3.0/_common.scss
Removed external top margin and added some more top and bottom padding
to avoid shrinking the rows too much.
closes #108
=> Removed gap in Nautilus sidebar rows

Communitheme/gtk-3.0/_common.scss, Communitheme/gtk-3.0/_drawing.scss
This PR fixes the following theme parsing errors:
```
$ GTK_THEME=Communitheme gtk3-widget-factory
(gtk3-widget-factory:1976): Gtk-WARNING **: Theme parsing error: gtk.css:494:22: Not a valid image
(gtk3-widget-factory:1976): Gtk-WARNING **: Theme parsing error: gtk.css:649:22: Not a valid image
(gtk3-widget-factory:1976): Gtk-WARNING **: Theme parsing error: gtk.css:803:22: Not a valid image
(gtk3-widget-factory:1976): Gtk-WARNING **: Theme parsing error: gtk.css:832:24: Not a valid image
(gtk3-widget-factory:1976): Gtk-WARNING **: Theme parsing error: gtk.css:858:22: Not a valid image
(gtk3-widget-factory:1976): Gtk-WARNING **: Theme parsing error: gtk.css:941:22: Not a valid image
(gtk3-widget-factory:1976): Gtk-WARNING **: Theme parsing error: gtk.css:1006:22: Not a valid image …
```
=> Fix theme parsing errors

Communitheme/gtk-3.0/_common.scss
This is related to #111.
CSS `padding` doesn't allow negative values. It causes `Theme parsing error`:
```
$ GTK_THEME=Communitheme gtk3-widget-factory
(gtk3-widget-factory:1175): Gtk-WARNING **: Theme parsing error: gtk.css:4610:17: negative values are not allowed.
(gtk3-widget-factory:1175): Gtk-WARNING **: Theme parsing error: gtk.css:4615:15: negative values are not allowed.
(gtk3-widget-factory:1175): Gtk-WARNING **: Theme parsing error: gtk.css:4633:15: negative values are not allowed.
```
This PR improves the code and removes the `placessidebar` gaps with less side effects.
=> Improve removing gaps in Nautilus sidebar

Communitheme/gtk-3.0/_apps.scss, Communitheme/gtk-3.0/_common.scss
I thought current tabs are a bit too large, so I fine-tuned that as follows:
- make `notebook > header` height same as Adwaita.
- 4px margins for `tab`.
- 4px margins for `tab > button`.
- 1px margins for `notebook > header > button` as with Adwaita.
- removed/commented out unnecessary codes.
**Before:**
**After:**
This PR is only size changes, no (actual) design changes.
What do you think?
=> Improve tab sizing

Communitheme/gtk-3.0/_common.scss
Window control hover and active effects affect only the button background
and the symbol (dash, cross, square) and not the red circle.
closes #137
=> Close button red circle does not change on hover and active

Communitheme/gtk-3.0/_drawing.scss
In button mixin, box-shadow is set explicitly only in non-flat buttons.
Unsetting it explicitly on flat button too, to close issue #158 where
box-shadow appears on flat button too.
Note: button in active state needs box-shadow even if flat to have
a "pressed" effect.
=> Explicitly unset button box-shadow in flat button

Communitheme/gtk-3.0/_common.scss
Treeview header buttons are square, but they inherit the squircle outline radius from regular buttons, this commit corrects that
=> Remove treeview header button's outline-radius

Communitheme/gtk-3.0/_common.scss
- The stackswitcher looks a little buggy right now so this reverts it to the old style until a decision is made on how to proceed/alter it (if even)
- Slider-buttons at the end of the path-bar use regular button radius size
=> Reverts the stackswitcher

Communitheme/gtk-3.0/_drawing.scss
The darker border will only be used for buttons that use $headerbar_bg_color
Closes issue #178
=> Fix flat buttons having a too dark border

Communitheme/gtk-3.0/_apps.scss, Communitheme/gtk-3.0/_common.scss
Moved fix for #109 to _apps.scss > Nautilus code to avoid messing up
with other applications.
closes #186 
Please consider also https://github.com/Ubuntu/gtk-communitheme/issues/186#issuecomment-367424861 about scroll effect in Nautilus
=> Limit padding-to in stack grid to Nautilus

Communitheme/gtk-3.0/_common.scss
- removed thick borders when selected
- re-set radio button radius when checked and selected
- re-organized the code
closes #190
=> Fix wrong check and radio button behavior when selected in treeview view

Communitheme/gtk-3.0/_common.scss
Normally, horizontally linked widgets share right/left border, so
when the widget on the left if highlighted, also the left border of
the sibling on the right is highlighted as well.
This commit removes the logic above in headerbars, where horizontally
linked widgets are forcibly separated and do not share any border.
closes #68
=> Fix focus ring horizontal widget in headerbar

Communitheme/gtk-3.0/_common.scss
- Fix the scale height to the current button height (from 34px to 32px)
- Change the fine-tune trough height from 6px to 5px to avoid jumping the slider
- Position the marks slider 1px up (#89)
- Fix the style of vertical marks slider
- Fix the style of color changer scale
Closes #89
=> Improve scales

Communitheme/gtk-3.0/_common.scss, Communitheme/gtk-3.0/_drawing.scss
- Make the stackswitcher same style as pathbar (#160)
- Round the stackswitcher corners by using additional `border` (#160)
- Fix style of pathbar not in the headerbar (#174)
- Improve the buttons behavior slightly
- Simplify the code
Closes #174
=> Improve stackswitcher and pathbar

Communitheme/gtk-3.0/_common.scss
Also fixes some buttons appearing as a regular headerbar button. See below:
=> Use green for selection-mode

Communitheme/gtk-3.0/_apps.scss
=> Avoid scrollbar protruding from the terminal window on wayland session

Communitheme/gtk-3.0/_common.scss
Programs that use a popup button in the headerbar (GNOME Logs, Calculator & Calendar) would use the regular button bg color instead of the headerbar button bg color
Closes issue #206
=> Fix headerbar popup buttons

Communitheme/gtk-3.0/_common.scss, Communitheme/gtk-3.0/_drawing.scss
- Removes tab hover effect in backdrop
- Dims icons in backdrop - just barely does anything but it's better than nothing
This doesn't do anything but remove the hover effect as further discussion is being continued in  #212
Closes issue #194
=> Remove tab hover effect in backdrop

Communitheme/gtk-3.0/_apps.scss
GNOME Disks seems to inherit a dark separator bg color from the headerbar. Since no unique classnames or ids are being used, I tried to make the rule as specific as possible so it won't affect any other program.
Closes issue #205
=> Fix GNOME Disks using dark separator in a headerbar button's menu

debian/control
As the GTK2 theme is based on Adwaita, it's using libadwaita + svg assets.
Ensure the package dependencies reflect this.
=> GTK2 theme now depends on adwaita and pixbuf engines

Communitheme/gtk-3.0/_apps.scss
Possibly this may not look good in Communitheme. So I separated this from #233.
=> Add separators to Nautilus list view

Communitheme/gtk-3.0/_common.scss
Adding border to headerbar made separator look too sharp.
Removed side border from headerbar when are not only-child
see #217
=> Made separator in headerbar less sharp

Communitheme/gtk-3.0/_apps.scss, Communitheme/gtk-3.0/_common.scss
This allows easier debugging.
Also forces the stackswitcher style to the buttonbox since some GTK+ apps use
buttonbox instead of stackswitcher in the headerbar.
Closes #237
=> Code refactoring for headerbar

Communitheme/gtk-3.0/_common.scss
I know it's a matter of opinion, but I think they look a little too wide right now.
=> Make buttons tied to entries narrower

Communitheme/gtk-3.0/_apps.scss
Gives gedit search entry some padding and a border, otherwise it's right under the headerbar.
Close issue #251
=> Fix gedit search field padding

Communitheme/gtk-3.0/_apps.scss, Communitheme/gtk-3.0/_ubuntu-colors.scss
The old Unity 8 terminal colors were being used in some places, this just darkens and lightens the new (purple) $terminal_bg_color for use for $terminal_borders_color and $terminal_base_color
=> Update terminal colors

Communitheme/gtk-3.0/_apps.scss
- replaced white background color on hover with border
- added borders to the other buttons when hover for consistency
=> Fixed terminal inactive tab hover

Communitheme/gtk-3.0/_common.scss
Previously menuitem at the bottom of the menu had hover with rounded borders
on top instead of at the bottom, because menuitem at the bottom is actually a first-child.
Fixed setting appropriate border radius for first-child menuitem on hover
closes #316
=> Fixed menuitem hover radius

Communitheme/gtk-3.0/_colors.scss, Communitheme/gtk-3.0/_common.scss
- made sidebar color brighter and warmer
- fixed gnome-control-center language list color that was using sidebar color by mistake
- fixed some backdrop colors according to _backdrop_color function (which cannot be used directly in color.scss)
=> Fixed sidebar and some backdrop colors

Communitheme/gtk-3.0/_common.scss
- Fix `padding` size
- Remove unnecessary styling
- Stop using `backgorund-size` to avoid a chrome rendering bug
- Replace PNG assets with CSS `-gtk-gradient`
Closes #314
Closes #326
=> Fix window close button

Communitheme/gtk-3.0/_colors.scss
Uses a function to warm the sidebar color instead of a hardcoded value so the dark theme wouldn't be affected. (#327)
=> Fix sidebar color

Communitheme/gtk-3.0/_drawing.scss
As requested [here](https://github.com/ubuntu/gtk-communitheme/issues/302#issuecomment-382148039) for dealing with issue #302
=> Just add shadow to active headerbar buttons when active

Communitheme/gtk-3.0/_apps.scss, Communitheme/gtk-3.0/_common.scss
Not sure if the altered line was an isolated case, but it resulted in the wrong radius being used in some corners in most cases. #316 
Before:
After:
=> Fix context menu border-radius on hover

Communitheme/gtk-3.0/_common.scss
This change avoid button in headerbar to show a different timing
in backdrop transition
=> Fixed slow headerbar button backdrop transition

Communitheme/gtk-3.0/_common.scss
In dialog widows, default button is styled with a darker border.
Moreover selection ring style changed from solid to dashed so that when a
button is both selected and default the superposition of the two
lines (orange and ash) is not too strong.
=> Added style for default button

Communitheme/gtk-3.0/_common.scss
Mentioned [here](https://github.com/ubuntu/gtk-communitheme/issues/307#issuecomment-378414227). Includes a tiny fix for checks and radios sometimes using $text_color when hovered on in treeviews.
=> Use extend for selected text

Communitheme/gtk-3.0/_common.scss
To have the icon be the same color as the label. Closes #364
=> Selected sidebar row in nautilus icon has full opacity

Communitheme/gtk-3.0/_common.scss
Updates the tab focus outline to match the one seen [here](https://github.com/ubuntu/gtk-communitheme/issues/303#issuecomment-378215286).
Closes #303
=> Update tab focus outline

Communitheme/gtk-3.0/_colors.scss, Communitheme/gtk-3.0/_common.scss
Uses #FA794B. 
Addresses #363. 
Seen [here](https://github.com/ubuntu/gtk-communitheme/issues/363#issuecomment-385286238).
=> Lighter orange for selected text

Communitheme/gtk-3.0/_common.scss
- styled buttons when headerbar is in selection-mode (green buttons)
- removed black border from headerbar in selection-mode
- fixed missing left dark border in headerbar when maximized (not selection-mode)
closes #378, addresses a problem introduced with #371
=> Fixes to headerbar widget and borders

Communitheme/gtk-3.0/_common.scss, Communitheme/gtk-3.0/_drawing.scss
In order to avoid interferences between changes on buttons and check/radio, this commit adds a dedicated mixin function for check/radio button that fixes #367
I decided to add only the "button" types we actually use in scss files: normal, hover, active, insensitive, backdrop, backdrop-insensitive, so no osd- or alt-. I assume this is safe, but not 100% sure.
Below the result
=> Added dedicated mixin function for check and radio buttons

Communitheme/gtk-3.0/_apps.scss, Communitheme/gtk-3.0/_ubuntu-colors.scss
Backdrop color of tab label was hardly visible, but at the same time
the backdrop color of terminal was a bit too bright.
Defined a new terminal_text_backdrop_color for both
closes #390
=> Fixed gnome terminal backdrop color

Communitheme/gtk-3.0/_common.scss
In un-maximized mode only, added a inkstone colored window top border
to stress the idea of the light that comes from the top of the
screen.
Before
After
=> Made window top border bright

Communitheme/gtk-3.0/_apps.scss
- closes #400
- makes nautilus separator line in sidebar more similar to the one in other
sidebars (e.g. gnome-control-center, gnome-tweaks)
=> Made nautilus separator line lighter

Communitheme/gtk-3.0/_common.scss
Changed selection ring to white in focus treeview and row
When selected, treeview and row have at the same time orange background
and orange selection ring, so that the latter is not visible. Changing
the selection ring to white makes it visible again.
closes #423
=> Improved selection ring in treeview and row

Communitheme/gtk-3.0/_common.scss
Fixing https://github.com/ubuntu/gtk-communitheme/issues/183#issuecomment-385289802
It's the same shadow as popovers have.
Thanks to @vinceliuice for the tip!
@madsrh @clobrano is this okay for you?
=> box-shadow for context-menu -> readability

Communitheme/gtk-3.0/_apps.scss
Restyled gnome-terminal tab using headerbar's color palette to get along
with different terminal color schemes.
closes #410
=> Reworked gnome-terminal tab style

Communitheme/gtk-3.0/_common.scss
hover effect on spinbutton is now the same as the one of unchecked
check/radio buttons.
see #397
=> Added hover effect to spinbutton

Communitheme/gtk-3.0/_apps.scss, Communitheme/gtk-3.0/_common.scss
As per review of #410 
- fixed flat dark button style
- added bright border to active/checked tab
- fixed menubar backdrop color (this is a bonus. If this PR does not get merged, cherry-pick this commit as well)
=> Refine gnome terminal

Communitheme/gtk-3.0/_drawing.scss
entry background in backdrop was too dark and the label was not visible.
- made background-color brighter (like headerbar button hover)
- fixed a typo that made the color property overwritten and changed to backdrop_headerbar_text_color
closes #440
=> Fixed entry colors in backdrop

Communitheme/gtk-3.0/_apps.scss
I don't know if the wildcard is considered a hacky solution.
Make icons in Nautilus less bright in backdrop.
=> Make icons less bright in backdrop

Communitheme/gtk-3.0/_common.scss, Communitheme/gtk-3.0/_drawing.scss
Fixes some quirks like green checks using the gray $insensitive_borders_color, also lessens the box-shadow for regular buttons.
Before:
After:
=> Fix check + radio backdrop

Communitheme/gtk-3.0/_common.scss
Current focus ring on label is too tight and "cut" the text.
Increased outline-offset (-3px -> +1px) to avoid that.
closes #458
=> Fix focus ring cut label text

Communitheme/gtk-3.0/_apps.scss, Communitheme/gtk-3.0/_colors.scss, Communitheme/gtk-3.0/_common.scss
@madsrh @clobrano please test the dark version with apps that use the dark theme by default like
GNOME
videos ("totem")
eye of gnome (that picture viewer)
boxes (virtualization software)
peek
todo (if you activate the dark theme in appmenu-> extensions)
Updating the gifs and pictures with every commit to be up to date:
Filechooser:
Boxes:
Eye of gnome (image viewer):
Pitivi:
Todo:
=> darktheme introduction and light theme improvements

Communitheme/gtk-3.0/_apps.scss, Communitheme/gtk-3.0/_common.scss, Communitheme/gtk-3.0/_drawing.scss
Closes #453
Also makes the close button in backdrop have the same color as the other titlebuttons instead of white.
Before on the left, after on the right:
Also adjusts headerbar separator so it's more visible. Before on the left, after on the right:
=> Separator finetune + close button in backdrop fix

Communitheme/gtk-3.0/_common.scss
switch margin top and bottom where defined in two different places and
in a way that made the headerbar with a switch bigger than the ones
without.
Fixed defining the correct top and bottom margins in only one place
closes #462
=> Fixed switch margins in headerbar

Communitheme/gtk-3.0/_common.scss
Closes https://github.com/ubuntu/gtk-communitheme/issues/477
=> style GNOME logs .compressed-entries-label

Communitheme/gtk-3.0/_colors.scss, Communitheme/gtk-3.0/_common.scss, Communitheme/gtk-3.0/_drawing.scss
closes #476
Light variant standalone check and radio buttons
Dark variant standalone check and radio buttons
Light variant menu check and radio buttons
Dark variant menu check and radio buttons
=> Improve inactive check/radio colors

Communitheme/gtk-3.0/_common.scss
This fixes some deprecation warnings spamming the CLI (which isn't the case for upstream Adwaita):
Example starting gedit:
(gedit:11641): Gtk-WARNING **: 10:41:20.935: Theme parsing error: gtk.css:2672:72: The :insensitive pseudo-class is deprecated. Use :disabled instead.
(gedit:11641): Gtk-WARNING **: 10:41:20.935: Theme parsing error: gtk.css:2673:66: The :insensitive pseudo-class is deprecated. Use :disabled instead.
(gedit:11641): Gtk-WARNING **: 10:41:20.935: Theme parsing error: gtk.css:2674:57: The :insensitive pseudo-class is deprecated. Use :disabled instead.
(gedit:11641): Gtk-WARNING **: 10:41:20.935: Theme parsing error: gtk.css:2675:51: The :insensitive pseudo-class is deprecated. Use :disabled instead.
(gedit:11641): Gtk-WARNING **: 10:41:20.935: Theme parsing error: …
=> Fix GTK warnings as insensitive is deprecated

Communitheme/gtk-3.0/_common.scss
That's a regression, gtk process working spinner was orange for some commits. 
Fixed it back to blue:
=> bring_back_blue_spinner

Communitheme/gtk-3.0/_apps.scss
Closes https://github.com/ubuntu/gtk-communitheme/issues/243
=> Transparent background for pictures in GNOME Photos

Communitheme/gtk-3.0/_apps.scss, Communitheme/gtk-3.0/_common.scss
1. Fixed gedit Document panel row close button color issues
2. Removed gedit-search-entry-occurrences-tag ugly border
3. Removed firefox rounded menu corners
4. Removed menu overflow arrow button extra space
=> Fixed gedit and menu issues

Communitheme/gtk-3.0/_common.scss
=> Use flat buttons in toolbar only if explicitly defined by developer

Communitheme/gtk-3.0/_drawing.scss
When in insensitive/disabled state there is no difference between
checked and unchecked switches.
closes #238
=> Differentiate between checked and unchecked disabled switch

Communitheme/gtk-3.0/_drawing.scss
Continuation of the discussions here: https://github.com/ubuntu/gtk-communitheme/pull/508
And here: https://github.com/ubuntu/gtk-communitheme/issues/212#issuecomment-393887091
Closes https://github.com/ubuntu/gtk-communitheme/issues/212
@clobrano @madsrh I still think the grey has a better usability but this one looks better =)
=> Lighten the orange in backdrop

Communitheme/gtk-3.0/_common.scss, Communitheme/gtk-3.0/_drawing.scss
- added a new case for checked:hover
- reduced the highlight for cheched:hover button on headerbar
closes #501
=> Improved headerbar checked button transition to hover

Communitheme/gtk-3.0/_colors.scss, Communitheme/gtk-3.0/_common.scss
- libreoffice has some hardcoded text selection color
- adapt the text selection to that
- EXCEPT gtkentries, which use regular ubuntu orange
This is a test PR for  @madsrh and for everyone who has too much time! ;D
=> Light orange for text, ubuntu orange for entries

Communitheme/gtk-3.0/_apps.scss
https://github.com/ubuntu/gtk-communitheme/issues/465
Before: https://user-images.githubusercontent.com/3986894/40322689-7aa7016c-5d33-11e8-8764-2de8eec1e585.png
After: https://user-images.githubusercontent.com/15329494/41205770-12cac1ce-6cfa-11e8-8ffa-d9eb64353e77.png
I'll leave the selection menu to @clobrano the button master :+1:
=> Add a border left/right to GNOME Software's installed apps rows

Communitheme/gtk-3.0/_apps.scss, Communitheme/gtk-3.0/_colors.scss, Communitheme/gtk-3.0/_common.scss, Communitheme/gtk-3.0/_drawing.scss
Initially discussed in #407 and revived by [this comment](https://github.com/ubuntu/gtk-communitheme/pull/407#issuecomment-395594228)
But basically is because current mainview and sidebar and button (yes I know) look a bit dull.
---
**EDIT** still to be done: 
Here are a new attempt. Please make a long test, several pieces can be affected (One for all, the filechooser, that is to be fixed already).
Filechooser fixed
=> sidebar colors tweaks

Communitheme/gtk-3.0/_drawing.scss
Currently, switch's selection ring is placed in correspondence of
slider's border, while in button and similar widgets it is slightly
internal to the widget itself.
This commit changes the switch's outline-offset from -1px to -2px.
closes #491
=> Made switch's selection ring more similar to the button's one

Communitheme/gtk-3.0/_apps.scss, Communitheme/gtk-3.0/_colors.scss, Communitheme/gtk-3.0/_common.scss, Communitheme/gtk-3.0/_drawing.scss
The following changes were made only for the dark theme:
- bg color 
- button color 
- border color 
- button color 
- button active/hover/insensitive colors
- backdrop button active/hover/insensitive colors
- some gnome todo tweaks
@madsrh  please check out the look
@clobrano please double check the implementation. especially in _drawing
Despite the must have changes like super bright button hovers and pressed colors I changed the backdrop with the following idea in mind:
- don't change to much from the active colors
- only soften the border and text color
To do:
=> Darktheme color changes

Communitheme/gtk-3.0/_common.scss
currently, stack-switcher button color in backdrop is darker than the
headerbar's one in the same state, while in normal state the color
relationship is inverted (hb darker then stack-switcher). This causes
a bad transition effect.
Using _backdrop_color function to automatically get a valid bg color
for this widget.
Before
After
=> Improved stack-switcher button backdrop color

Communitheme/gtk-3.0/_common.scss
On headerbar image buttons are taller than wide, except appmenu button.
Fixing this adjusting headerbar top and bottom margins.
Incidentally, this also fixes issue #381
=> Fix headerbar button height > width

Communitheme/gtk-3.0/_common.scss
This change gives to circular sliders the same hover effect that check and radio buttons have
Note: for non circular sliders, we need to create the appropriate png
see #397
=> Added gray hover effect to circular slider

Communitheme/gtk-3.0/_apps.scss, Communitheme/gtk-3.0/_colors.scss, Communitheme/gtk-3.0/_common.scss, Communitheme/gtk-3.0/_drawing.scss
This PR re-introduces hover effect on backdropped wigets.
Since the list of widgets is long, I though it would have been better to give immediatly a snap branch to test and a PR on which discuss and remind widgets I might have forgotten
TODOs
closes #194
=> re-introducing backdrop hover effect

Communitheme/gtk-3.0/_apps.scss, Communitheme/gtk-3.0/_common.scss
=> Firefox fixes

Communitheme/gtk-3.0/_apps.scss
Closes https://github.com/ubuntu/gtk-communitheme/issues/559
Also fixes the light theme which looks this way in master :
=> Box-shadows to style gnome-software

Communitheme/gtk-3.0/_apps.scss
Give terminal unchecked backdrop tab hover proper border and background
colors
closes #591
=> Fixes terminal tab backdrop hover

Communitheme/gtk-3.0/_apps.scss
Missing commit from #609 
improved hover effect also on other buttons in the tabs area that are not
part of the tab. Added also a darker border to the buttons above and to
the close tab button of unchecked tab. Checked tab close button gets a
background highlight instead.
=> Improved backdrop hover in nautilus tabs

Communitheme/gtk-3.0/_common.scss
Adding the missing border color that non-flat buttons have on hover
closes #571
=> Toolbar button hover added missing border color on hover

Communitheme/gtk-3.0/_common.scss
separator in a contextual menu of pathbar (e.g. Nautilus) takes the same
color of a headerbar separator. Being the latter dark and the first
bright, the same color can not be used, causing issue #576
Reorganized the code to avoid to style such contextual menu separator as
if it was in a headerbar.
closes #576
consider that this lines of code are used to style both headerbar's horizontal separator and Gedit paned separator as well
=> Fixed headerbar separator color

Communitheme/gtk-3.0/_common.scss
closes #611
This is actually made of two commits, the second is optional, so wait for @madsrh to review it before merging it (EDIT: I forgot he's on vacation :D)
1st commit removes top border highlight from the widget
2nd commit makes the color button squared
=> colorswatch hover and roundness

build-helpers/prepare-build-snap
This enable us doing some more cleanups and removing a file from the Travis env.
=> Take gtk-common snapcraft parts from current repo

CONTRIBUTING.md, build-helpers/replace-name, sessions/THEMENAME-wayland.desktop.in, sessions/THEMENAME.desktop.in, sessions/meson.build, sessions/meson/copy-to-wayland-session, snap/snapcraft.yaml
This install correct mode and names for them, following requirement
* Fallback to /usr for dev installation
GDM doesn't know about /usr/local and it's something we can't SRU easily
to bionic, we need to fallback thus to /usr for developers :/
As long as devs don't install the package version, that's fine.
* Add a separate wayland session
Separate wayland from xsession so that developers can choose between the 2.
* GNOME Shell only accept lowercase mode names
Ensure both reference and filename are lowercase to match GNOME Shell
requirements on those.
Make the renamer a little bit smarter if we use the keyword as a
lowercase.
Fixes #634.
=> Fix developer sessions

sessions/meson.build, sessions/meson/install-dock-override
Create an empty file matching mode name to let main css file override
ubuntu-dock style one.
Fixes: #637.
=> Install override file for ubuntu-dock style

gnome-shell/src/gnome-shell-sass/_common.scss, gnome-shell/src/gnome-shell-sass/_dock.scss
- reset -slider-border-color property
- removed background-size property with value "contain" from .show-apps-icon
it seems that gnome-shell does not support non-numeric values
closes #653
=> Fixed some gnome-shell error messages

gnome-shell/src/gnome-shell-sass/_dock.scss
Closes https://github.com/ubuntu/communitheme/issues/584
We tried several iterations of a new appgrid icon but came to the conclusion to completely follow upstream.
=> Use upstream appgrid icon.

gnome-shell/src/gnome-shell-sass/_dock.scss
Fix missing line so the press effect is only for the icon:
=> Press effect only for the icon, add missing line.

gtk/src/gtk-3.0/_common.scss
- added border to the box
- fixed notebook header color (it was white as the tabs)
closes #505 
Backdrop
=> Restyled Software updater technical description box

gtk/src/gtk-3.0/_apps.scss
Closes #412 again
before
after
=> Aligned again small title button in chrome/chromium

gnome-shell/src/gnome-shell-sass/_common.scss
```sass
background-gradient-direction: vertical;
background-gradient-start: #6D2169;
background-gradient-end: #370026;
```
Back to a purple gradient as most people seem to dislike the white box (I like it :D)
This time we use a (undocumented) gradient without a SVG needed. Sadly this gradient is limited to either horizontal or vertical. @madsrh @luxamman maybe you can chose colors and one of two directions :)
=> Login /lock screen

gtk/src/gtk-3.0/_apps.scss
Because the border radius of the taskrow is hardcoded.
=> Gnome-ToDo: Remove the border radius of the taskrow button and the outline

gnome-shell/src/gnome-shell-sass/_common.scss
Removing background-position property since gnome-shell does not
support it
close #664
=> Removed background-position property from gnome-shell common

CONTRIBUTING.md
Currently meson is using default location to install Yaru from source,
then update-alternatives should point to `/usr/share/gnome-shell/...`
instead that to `/usr/share/local/gnome-shell`
=> Fix update-alternative commands

gtk/src/gtk-3.0/_apps.scss
Closes https://github.com/ubuntu/yaru/issues/689
=> Make secondary nautilus icon labels less colorful

gtk/src/gtk-3.0/_apps.scss, gtk/src/gtk-3.0/_common.scss, gtk/src/gtk-3.0/_drawing.scss
Stop mimic stackswitcher with buttonbox
TODO
closes  #482
=> Define a proper buttonbox style

gnome-shell/src/gnome-shell-sass/_common.scss
In GDM the insensitive entry and buttons fades to a strange color 
because it was originally not designed to be light in drawing.scss.
This is fixed globally for light entries and locally for the light button now.
=> Light entry and button fix

gtk/src/gtk-3.0/_common.scss
- make the label more greyish instead of black
- overwrite the default button backdrop bg color for infobars because the 
not(:insensitive) buttons merge their color with the purple then
Before:
After:
@madsrh @clobrano please check if you like it or not
=> Infobar backdrop improvements

gtk/src/gtk-3.0/_colors.scss, gtk/src/gtk-3.0/_common.scss
- added a backdrop_bordes_color border to the DARK  theme headerbar 
bottom  border
- reduced the dark theme darkness borders by 2%
Before:
After:
Otherwise borders of for example sidebars and treeviews crash into the backdrop headerbar bg color and it looks "opened" and unfinnished imho. That's why I attached the rhythmbox AFTER screenshot
@madsrh @clobrano please check if you like this or not.
=> Dark theme border improvements

gtk/src/gtk-3.0/_common.scss
In combobox made of entry + button, the entry selection ring appears and
disappears at different speed on the right side, that is, the side
"shared" with the button.
Fixed
- applied "button_transition" on buttons that belong to such a combobox,
to fix the delay in selection ring appearance.
- applied "button_transition" on the entry widget only in case of focus,
to fix the disappearing delay.
closes #533
Result
=> Fixed speed of combobox selection ring transition

gtk/src/gtk-3.0/_common.scss
The red destructive-color is so similar to media-record-symbolic
icon that the icon itself is barely visible (see Sound Recorder).
Added a icon-shadow layer of a darker red to improve icon visibility.
closes #708 
Result
=> Improved visibility of destructive-action button icon

gtk/src/gtk-3.0/_common.scss
Emoji-section's label uses the opacity parameter < 1 for unchecked
ones, but that makes those icons invisible (I suppose opacity parameter
is not supported in labels).
Removing opacity parameter to fix the issue.
closes #721
=> Remove opacity parameter from label in emoji-section

gtk/src/gtk-3.0/_apps.scss
Carlo introduced the awesome "light from above" headerbar color
Geary uses the global headerbar styling for their inapp-reply feature.
This is a minor GEARY ONLY fix which removes the headerbar border
Before:
After:
=> Remove the headerbar border for geary new messages.

gtk/src/gtk-3.0/_common.scss
Before:
The margin is uneven at the moment, after we stopped to mimic the stackswitcher in buttonboxes.
After:
=> Remove the uneven .counter-label margin because of the recent buttonbox changes

gtk/src/gtk-3.0/_common.scss
Closes https://github.com/ubuntu/yaru/issues/737
@madsrh please check
=> Lighten default button text color for the dark variant by 10%

gtk/src/gtk-3.0/_common.scss
closes #725 
I could not find a more specific way to target check/radio widgets inside a treeview.view than this one. I observed no side effect however, but is to be tested well and in case of regression, remove this change.
=> white border selected row radio check

gtk/src/gtk-3.0/_common.scss
Progress bar color in treeview, when selected, gets a white color that
does not fit Yaru theme.
with this commit
- progress bar bg uses a lighter selection color for background
- progress bar fg (the label) turns white when selected. This
will give a slight visual hint that the progress bar is part of a
selection.
- progress bar and trough get a border to make the separation from the
row below more evident
moreover:
- uniformed border-radius using Yaru values (small_radius)
- set border radius to zero internally to the trough, this makes more
evident that the bar is progressing
closes #726
=> Avoid changing progressbar bg color when selected in treeview

gtk/src/gtk-3.0/_apps.scss, gtk/src/gtk-3.0/_colors.scss, gtk/src/gtk-3.0/_common.scss, gtk/src/gtk-3.0/_drawing.scss
This PR is also about organizing the code a bit more and using global styling instead of local styling so we can easily switch the colors. 
- replaced $orange with $selected_bg_color in the _backdrop_color 
function in _drawing
- replaced the local styling with %selected_text for dark entries
- use a darker blue for selected text in the dark variant
- use the text color for selected text in the dark variant, too
- use selected_text for the label in the backdrop
Todo:
Also closes https://github.com/ubuntu/yaru/issues/733
=> Selected text improvements

gnome-shell/src/gnome-shell-sass/_common.scss
We prefer full-color app icons in the top bar, in part because many
third-party apps don't provide symbolic icons yet so it is more
consistent to use full-color icons for all apps.
This fixes a regression accidentally introduced in 050ddce6
[LP: #1787401](https://launchpad.net/bugs/1787401)
=> gnome-shell: Don't use symbolic app icons in the top bar

gnome-shell/src/gnome-shell-sass/_common.scss
Also avoid double code by using almost the same styling from dialog 
buttons for notifications and hotplug items.
As seen in https://github.com/ubuntu/yaru/issues/749#issuecomment-416523193
=> Make dialogue, notificatio and hotplug buttons flat.

gnome-shell/src/gnome-shell-sass/_common.scss
I've given meld another chance to check differences between upstream and yaru (@didrocks!) to reduce the diffs, and setting the values to default when possible (like `.user-widget-label` that was changed in g-s 3.29.30, but not reported here).
=> Gnome shell upstream less diff

gtk/src/gtk-3.0/_drawing.scss
I have forgotten suggested and destructive action buttons with $flat==true
@clobrano I just checked if there are any suggested action btns with flat==true outside of the headerbar and didn't find any - did I miss something?
=> Adapt flat suggested action buttons

gtk/src/gtk-3.0/_drawing.scss
In backdrop, dark entries background got darker by just 1%, however this
little change was enough to make the background the same as transparent,
loosing the difference from insensitive-background entries.
To fix it, this commit remove the background color change in backdrop
for dark entries, as keeping this same color in both normal and backdrop
state does seems to work fine as well.
closes #766
=> drawing/entries dark: fixed backdrop entry backdround color

gtk/src/gtk-3.0/_common.scss
check and radio buttons in a treeview.view (when unchecked) keep white
border when selected also in dark mode.
closes #725
=> view/check-radio: white border for selected in dark variant

gtk/src/gtk-3.0/_apps.scss, gtk/src/gtk-3.0/_colors.scss, gtk/src/gtk-3.0/_common.scss
In dark variant, notebook tabs are similar to gnome-terminal's tabs, but
they are style differently. Since gnome-terminal's tabs seems to be
appreciated, this commit style generic notebook tabs in a similar way.
NOTE: generic notebook tabs do not get the orange underline
gnome-terminal has. In fact, while the orange looks good in the
particular usage of gnome-terminal, in the wider variety of usage of
generic notebook tabs, this is not always true and instead orange make
those tabs look heavier.
**TODO**
=> Made notebook tabs more similar to gnome-terminal's ones

gtk/src/gtk-3.0/_common.scss
Also add a transparent white border for text-buttons like we did with 
the other text-buttons
@clobrano @madsrh are you okay with this?
=> Adapt selection-mode buttons in headerbar to the new headerbar styling

gtk/src/gtk-3.0/_apps.scss, gtk/src/gtk-3.0/_common.scss
In applications with a sidebar and status-bar (e.g. Nautilus and Gedit),
having unchecked notebok tabs with the same color as headerbar creates
a unpleasant effect of disconnection between the notebook and the
sidebar/status-bar.
To fix that this PR
- changes the sidebar color in Gedit to bg_color (Nautilus already uses it)
- changes the color for unchecked tabs in Gedit and Nautilus to bg_color
(the one used by the sidebar and status bar)
Note: general notebook tabs, like the ones in gnome-terminal, keep the
previous headerbar_bg_color
Also, clean ups to let Nautilus use styling from _common.scss
closes #786
=> notebooks refinements

gtk/src/gtk-3.0/_common.scss
Closes https://github.com/ubuntu/yaru/issues/769
As seen here: https://github.com/ubuntu/yaru/issues/769#issuecomment-418080454
This replaces the previous bold font with black/white for light/dark theme
Because the buttons increase in size as you can see here:
https://github.com/ubuntu/yaru/issues/769#issuecomment-419586399
=> Color the .default button's text-color black/white for light/dark theme

gtk/src/gtk-3.0/_apps.scss
Because the close button bug is fixed for the new released, and thus we 
don't need to make it bigger anymore
=> Remove chrome styling from _apps

gtk/src/gtk-3.0/_common.scss
Currently the checked button has a background, I think this looks a bit strange.
This changes the checked to have no bg and active to use base_active_color for the second you press and hover base_hover_color
Current:
This PR:
@madsrh @clobrano decide please
=> Emoji Picker Buttons: Style button active, hover and checked

gtk/src/gtk-3.0/_common.scss, gtk/src/gtk-3.0/_drawing.scss
unchecked check/radio widget uses transparent background in dark variant
=> drawing/check+radio dark: use transparent background

gnome-shell/src/gnome-shell-sass/_common.scss
=> Remove the declaration, which let's the icon style fallback

gtk/src/gtk-3.0/_apps.scss
Backdrop border color of nautilus' circular button (stop loading button)
stays dark in backdrop. This commit makes it transparent in backdrop
=> apps/nautilus: fix circular button backdrop border color

gtk/src/gtk-3.0/_apps.scss
=> Use small radius for nautilus widgets/canvas items

gtk/src/light/gtk-3.0/meson.build
Some GTK3 applications can choose to pick up dark theme in a light
environment.
Restore installing gtk-dark.css in the light theme directory.
=> Readd support for GTK3 apps choosing dark theme in a light environment

gtk/src/light/gtk-3.0/_common.scss
Some filechosers use a label, within a box, within the headerbar 
buttons. This makes them white, when styled with .default
Closes https://github.com/ubuntu/yaru/issues/823
=> Style labels inside default buttons inside headerbar

build-helpers/gtk-common-themes-parts.yaml, build-helpers/prepare-build-snap
As we now need sassc for gtk-common-themes, ensure we upgrade the image
to bionic as well for it.
=> Build gtk-common-themes using bionic docker image

gtk/src/light/gtk-3.0/_apps.scss
Custom notebook code in Nautilus is not needed anymore and moreover it
causes #829 or at least makes it very hard to fix.
closes #829
TODO
=> apps/nautilus: removed custom notebook code

build-helpers/prepare-build-snap
gtk-common-themes has moved from github to gitlab.gnome.org
=> Updated url to pull gtk-common-themes from gitlab.gnome.org

gtk/src/light/gtk-3.0/_drawing.scss
As we changed the elements in the headerbar to be flat, we have forgotten to adapt this to the entries. 
This styles the entries like buttons (flat) in foreground and backdrop.
Before:
After:
@madsrh @clobrano please check design
@didrocks this has been forgotten - so it should be considered to be a fix and thus merged into cosmic?
=> Adapt headerbar entries to the buttons in headerbar

gtk/src/light/gtk-3.0/_common.scss
We have forgotten to style this in backdrop
Before:
After:
=> Make .inline-toolbar.horizontal.sidebar-toolbar transparent in backdrop

gnome-shell/src/gnome-shell-sass/_colors.scss, gnome-shell/src/gnome-shell-sass/_common.scss
With current shell popover/popups border color, it might be hard to
see the boundaries of the widget on dark backgrounds (see #847).
This PR makes the borders brighter to help with the issue above.
closes #847
=> shell/colors: made osd_borders_color brighter

gtk/src/light/gtk-3.0/_common.scss
**Testing** PR for gnome disks (https://github.com/ubuntu/yaru/issues/714#issuecomment-422325117) and every other widget that is selected (they should all have orange bg and bright fg)
Currently, gnome-disk(s-utility) has it's selected partitions colored with black text-color even if they are selected. Which makes the text hard to read with our default selected background color: orange
This change applies widget:selected { color: $selected_fg_color; } high up in _common.scss 
I can not think of a selected widget which should not have a bright text color. But we should check carefully if this does not change anything else.
@madsrh @paz-it @clobrano please test this PR if you have time and check for all the selections of UI elements and if this has a negative effect
-->  does this overwrite …
=> GNOME disks: Selected widgets should have the a light text color.

gtk/src/light/gtk-3.0/_apps.scss
- Add a margin to usb-creator's dialog
Closes https://github.com/ubuntu/yaru/issues/853
- Correct geary headerbar (had a mistake in my commit back then which limited this to headerbar to a specific style class)
=> Usb creator margin and geary fix

gtk/src/light/gtk-3.0/_common.scss
When active, the notebook tab's label gets bold, this increases its
size and, since labels seem center aligned, the label starts one pixel
below the other non-active labels.
This PR add a 1px bottom padding to this label to fix the alignment.
closes #854
=> align active notebook tab labels

gnome-shell/src/gnome-shell-sass/_common.scss
Closes https://github.com/ubuntu/yaru/issues/870
=> Make separators visible again in popups and calendar

gtk/src/light/gtk-3.0/_drawing.scss
closes #850 
result
Note: this PR is slightly different than what I posted on #850 to avoid changing the aspect of light version
=> fixed backdrop insensitive switch

build-helpers/gtk-common-themes-parts.yaml
We don't need it this snap only covers GTK assets.
=> Remove Shell artefacts from gtk-common-themes

gnome-shell/src/gnome-shell-sass/_common.scss
popup-menu-item uses a transparent 1px top border by default.
Being transparent, it shows the dark color from below levels when the
item is in selected state, resulting in a black line.
Fixed changing the color of such top border to the one of the
highlighted background in selected state.
closes #896
=> shell/popup-menu-item: fixed black border in submenu hover

gnome-shell/src/gnome-shell-sass/_dock.scss
**This should not be merged into master but instead into a new branch "Cosmic" or something
to not break the bionic snap theming**
Currently there is a bug in Cosmic, which prioritizes the stylesheet.css from /usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/ over our dock theming  in the yaru shell theme (https://github.com/ubuntu/yaru/issues/928)
And we end up with a color overlay of red on our green badge which looks really messy and buggy
This commit changes the badge border to a dark red to remove this "bugged" look. (the dashtodock css only overrides the background and does not style the border, thus our border style is used)
@didrocks I would call this rather important because currently it looks very broken in cosmic. 
We should revert this ASAP when a fix is applied in …
=> Make the badge border temporarly dark red

gnome-shell/src/gnome-shell-sass/_common.scss, gnome-shell/src/gnome-shell-sass/_dock.scss
The dash-to-dock v64 now applies both transparency values (as
it was before) and background color (this is new). Because of this,
Yaru's dock customization needs to set both values now.
Also, revert notification-badge background and border color to green.
see #928
=> shell common+dock: Fix dock opaque color and revert badge color

gnome-shell/src/gnome-shell-sass/_common.scss
Use $light_base_color (#FFFFFF) in place of $light_bg_color (#FAFAFA)
keeping the same transparency level.
closes #938
=> shell/common: Made dialog background brighter

gnome-shell/src/gnome-shell-sass/_common.scss
Made Gnome shell _authorization dialog_ title the same as the one in _close session dialog_
closes #937
=> shell/common: fixed auth dialog title style

gtk/src/light/gtk-3.0/_common.scss, gtk/src/light/gtk-3.20/_common.scss
- the infobar file changes got applied onto the "old" folders i.e. 3.18 now after the merge of https://github.com/ubuntu/yaru/pull/935
- this is a damage control to get a stable master now and leaves infobars unstyled for gtk 3.18, this needs further investigation @jhenstridge
- also fixes a semicolon miss
- fixes backdrop
=> Fix infobar branch merge

gnome-shell/src/gnome-shell-sass/_common.scss, gnome-shell/src/key-enter.svg, gnome-shell/src/key-hide.svg, gnome-shell/src/key-layout.svg, gnome-shell/src/key-shift-latched-uppercase.svg, gnome-shell/src/key-shift-uppercase.svg, gnome-shell/src/key-shift.svg, gnome-shell/src/meson.build
Still a WIP
Thoughts? @madsrh @clobrano @Feichtmeier 
Icons still need to be replaced, but I'm not sure which ones to go with yet. The language/region key especially.
=> Style the Shell's virtual keyboard to match the rest of the theme

build-helpers/gtk-common-themes-parts.yaml
If the "theme" part yaml requires libglib2.0-dev dependency, the "yaru" part in gtk-common-themes-parts.yaml should need it too.
=> Added missing dependency in yaru part yaml

gnome-shell/src/gnome-shell-sass/_common.scss
=> Fixing entries to have a blue/dark blue selection for light/dark entries

gnome-shell/src/gnome-shell-sass/_common.scss
Closes https://github.com/ubuntu/yaru/issues/964
=> Use the same purple bg color for GDM as Grub uses in Ubuntu

gtk/src/light/gtk-3.20/_common.scss
-gtk-icon-source uses the same properties (-GtkWidget-text-handle-width/height)
to set both text-selection icons and insertion-cursor icons, but since the two
kind of icons differ in size in Yaru, the latter looks stretched.
Using background-* CSS properties instead, to set the proper icon sizes.
closes #945
=> Use background property to set insertion-cursor icon

gtk/src/light/gtk-3.20/_drawing.scss
- The active state looks a bit detached from the surface + the border-color difference is too big
- The dark variant hover has it's bottom border color darkened too heavy
-> Light+Dark Variant: change the active state to be on the same level as the bg
-> Dark only: change the hover state to be 1% brighter but have a 9% less dark bottom-border-color
Also
Closes https://github.com/ubuntu/yaru/issues/1006
=> Button hover and active refinements

gtk/src/light/gtk-3.20/_common.scss
Closes https://github.com/ubuntu/yaru/issues/1011
Explicitly styling for buttons inside horizontal linked boxes inside toolitems inside toolbars so we do not destroy a styling elsewhere
=> Removes margin for toolbar toolitem box .linked.horizontal button

gtk/src/light/gtk-3.20/_apps.scss
Nautilus dark backdrop sidebar separator color was different than other
similar separators, e.g. in gnome-settings, in the same state.
closes #1013
=> Fixed Nautilus dark backdrop separator color

gtk/src/light/gtk-3.20/_common.scss
Made treeview expander (pan-end-symbolic) icon paler in normal mode
and darker on hover.
closes #1016
=> treeview expander invert hover colors

icons/Suru/scalable/categories/gnome-control-center-symbolic.svg, icons/src/symlinks/symbolic/categories.list
gnome shell changed the icon name to gnome control center
Adding a new symlink fixes this
Closes https://github.com/ubuntu/yaru/issues/894
=> Fix wrong settings icon in gnome shell 3.30+ status menu popup

gtk/src/light/gtk-3.20/_common.scss, gtk/src/light/gtk-3.20/_drawing.scss
Added instructions for color of linked entry + button in combobox
when the entry is in error and warning state
closes #1031
=> Fix linked entry+button combobox in error and warning state

gtk/src/light/gtk-3.20/_drawing.scss
@clobrano @madsrh @godlyranchdressing please test and say if you like it/agree
Imho that dark orange looks strange in the dark theme
That function may work in adwaita with their blue, but it looks washed out in our color theme (imho)
Makes not much sense to provide screenshots as PEEK always changes the color a tiny bit :man_shrugging:
=> Make focus border for entries always the same color in dark and light

gtk/src/light/gtk-3.20/_common.scss
I've forgotten to style the switches in the dark popovers, this is the fix
=> Bring back normal switches for dark popovers

gtk/src/light/gtk-3.20/_common.scss
Set headerbar's left and right borders width to 0px, as windows' side borders are.
close #1049 
NOTE: with this change, we will lose some distinction between the edges of the headerbar and dark backgrounds.
before
after
For reference, this is adding a border color (inkstone) to the window view
from my point of view, the result depends too much on the background (it's invisible in white bg, and looks bright on the wallpaper) and on the actual window view color
=> Remove headerbar and menubar side borders

gtk/src/light/gtk-3.20/_drawing.scss
Currently check/radio button background is transparent, so that on
bright backgrounds, these widgets are invisible (the borders are bright
as well).
Changing the background color to solid.
close #1054 
TODO
=> Add solid bg to check and radio

gnome-shell/src/gnome-shell-sass/_colors.scss, gnome-shell/src/gnome-shell-sass/_common.scss, gtk/src/light/gtk-3.20/_colors.scss, gtk/src/light/gtk-3.20/_common.scss
@madsrh @clobrano 
: / Time to let go, gtk does not really support this.... or... since Gtk App devs focus on adwaita, they look up for selected_bg_color and don't support a difference between selected items and selected text
Please test and check if I have forgotten anything
Closes https://github.com/ubuntu/yaru/issues/1069
=> Make selected text orange again in gtk and shell themes

gtk/src/light/gtk-3.20/_apps.scss, gtk/src/light/gtk-3.20/_common.scss
On dark backgrounds the scrollbar slider visibility is very low.
Reenable trough's background color, but with high transparency
to fix this behavior without loosing the elegant effect in
light backgrounds
closes #1096 
Dark bg
Light bg
I double checked and the dark variant does not have the original issue and with this change it is good as well
=> Visible scrollbar trough improve slider visibility

debian/rules
=> Actually release Yaru-dark in debian package

gtk/src/light/gtk-3.20/_colors.scss, gtk/src/light/gtk-3.20/_drawing.scss
- removed dependency from variant in background colors, specifically
hover and active
- added dependency from variant to $osd_insensitive_fg_color, since
original color did not fit well with a light window background.
closes #1104
=> Fixed osd button hover in light variant

gtk/src/light/gtk-3.20/_common.scss
@madsrh please test it
I found that the strange color jumps I made there introduced too much crap. Removed basically all of the old notupstream styling and now light theme has a dark fg in backdrop just like everywhere else. See if you like it, I think this way it's more in line with the rest of the theme
=> Fix infobar backdrop

gtk/src/light/gtk-3.20/_common.scss
Closes https://github.com/ubuntu/yaru/issues/1122
@madsrh and/or @clobrano please test
=> Don't include entry:focus and entry selection in the jetpopoverwildcard

gtk/src/light/gtk-3.20/_drawing.scss
Before:
After:
@clobrano should I reduce the code further?
=> Fix active disabled/insensitive headerbar buttons

gtk/src/light/gtk-3.20/_common.scss
Before:
After
@madsrh @clobrano look closely at the edge between the menubar and when the menu pops up
There is a super small overlapping of the box-shadow
Looks a bit blurry
Please test this if you have time ;)
Closes https://github.com/ubuntu/yaru/issues/1117
=> Improve menu, popover and window borders

gtk/src/light/gtk-3.20/_common.scss
Because it causes a bug with a black border for some apps. The backdrop is also settled in line 4407
=> Revert box-shadow removal for decoration.ssd in backdrop

gtk/src/light/gtk-3.20/_common.scss
All elements in the headerbar are completely flat and sharp except the switches.
The darker border-top and the box-shadow make the round corners a little bit unsharp.
Before/current:
After flatness applied:
=> Remove top highlight for switches in headerbar

gtk/src/light/gtk-3.20/_common.scss
=> Remove border-top change and box-shadow also in backdrop for hb switches

gtk/src/light/gtk-3.20/_colors.scss
GtkTheme's tooltips look blurry and not sharp at the edges:
The shell theme's tooltips look sharper:
This adapts gtk tooltips border to shell:
=> Adapt gtk tooltips border to shell

icons/src/fullcolor/render-bitmaps.py
`render-bitmaps.py` script does not manage SVG files whose `height` and `width` are not integers. Making the script more robust parsing those values as float first and then converting them to integers.
=> Enforce integer sizes when rendering bitmaps

gtk/src/light/gtk-3.20/_common.scss
suggested and destructive btns Border-color changes on hover and active in headerbar
This should fix it:
=> Fix HB suggested- and destructive-action buttons border color

icons/src/symlinks/generate-symlinks.sh
`generate-symlink` now accepts one argument to filter out
any `.list` entry that does not match with such argument.
With this change, it is possible to generate only specific symlinks.
If no argument is provided, the script falls back to the usual behavior,
symlinking all the entries in any `.list` file.
e.g.
The command
$ ./generate-simlink.sh folder-open
generates only symlinks for `.list` entries that concern
`folder-open`, both as source and destination
folder-open folder          (OK)
folder-close folder-open    (OK)
folder-one   folder-two     (NO)
image-x      image-y        (NO)
=> Allow generate-symlink providing a pattern

icons/Suru/scalable/actions/view-more-horizontal-symbolic.svg, icons/Suru/scalable/actions/view-more-symbolic.svg, icons/src/scalable/source-symbolic.svg
For #1144 - I've exactly cloned the dots/positioning from the view-app-grid-symbolic icon for maximum consistency:
=> Add symbolic icons for view-more-symbolic and view-more-horizontal-symbolic

gtk/src/light/gtk-3.20/_common.scss
Upstream changed the pathbar again
This hopefully fixes it
At least one of you
@clobrano @madsrh @ubuntujaggers @eaglersdeveloper 
Please check this on
- 18.04 with the snap (update: works!)
- 18.10 with meson installation
- 19.4 with the meson installation
Todo
=> Fix path-bar and nautilus-path-bar styling to the known underline design

icons/Suru/16x16/places/inode-directory.png, icons/Suru/16x16@2x/places/inode-directory.png, icons/Suru/24x24/places/inode-directory.png, icons/Suru/24x24@2x/places/inode-directory.png, icons/Suru/256x256/places/inode-directory.png, icons/Suru/256x256@2x/places/inode-directory.png, icons/Suru/32x32/places/inode-directory.png, icons/Suru/32x32@2x/places/inode-directory.png, icons/Suru/48x48/places/inode-directory.png, icons/Suru/48x48@2x/places/inode-directory.png
Some applications such as KDE's Dolphin lookup the mimetype of files to
decide which icon to use. For folders that's inode/directory. This
mean's Yaru's custom folder icon is ignored and instead a fallback icon
used from another theme.
**Before:**
(falling back to what I believe is the Humanity icon theme?)
**After:**
(correctly using Yaru's folder icon)
=> Add inode-directory symlinks to folder icon

gtk/src/light/gtk-3.20/_common.scss
I hope that's the last vicitim of my wildcard. @clobrano @madsrh please see if you like this unification 
Fixed #1184
Before:
no orange stripe on :checked but orange stripe on :checked:hover, transparent button bg
orange stripe on :checked and :hover, transparent bg
After:
orange stripe on :checked and :hover, button bg
orange stripe on :checked and :hover, transparent bg
=> Fix Light/Dark emoji.popover button:checked difference

gtk/src/light/gtk-3.20/_common.scss
With GNOME 3.32 the settings app provides a responsive design. The headerbar was changed and a new widget called hdyleaflet needs extra styling to keep our current look for separators in the headerbar, which is added with this commit.
Before:
After:
@clobrano please see if you would prefer a local variable instead of 3x styling the same color with that mixed(...) function
Firstly reported in #1175
=> Style new hdyleaflet separators

gtk/src/light/gtk-3.20/_apps.scss, gtk/src/light/gtk-3.20/_common.scss
Bottom border on checked tabs seems to cause resize issues to the new
gnome-terminal when the scaling factor is > 1 (e.g. 1.5).
Removing such border fixes it.
fixes #1196
=> Remove orange bottom border in selected tab

gnome-shell/src/gnome-shell-sass/_common.scss
After recent improvement to the desktop icons extension by the awesome @clobrano :tada: 
This commit adds a tiny roundness to the selection frame, which is the same small border radius we use in other parts of the theme
Before:
After:
=> Add round edges for desktop items selection frame

gtk/src/light/gtk-3.20/_common.scss
hdyleaflet widget has been deactivated for gnome 3.32, resulting in an unstyled separator in gnome-control-center again.
This removes the hdyleaflet selector which enables the correct styling for this gnome release
After:
=> Correctly style headerbar sidebar separator

gtk/src/light/gtk-3.20/_common.scss
Headerbar sliders look blurry, this should fix it. 
Before:
After:
Tested with lollypop built from src
=> Remove border-color for sliders in headerbar

gtk/src/light/gtk-3.20/_common.scss
Even though gnome-controlcenter removed hdyleaflet for 3.32, there are apps that use it.
Currently found gnome-contacts
Before:
After:
=> Gtk theme hdyleaflet again

build-helpers/prepare-build-snap
As per Gnome shell changes on Disco, we are going to freeze Bionic
development. For this reason, any future change for the snap package
will be build only if pushed on the dedicated `bionic` branch.
Moreover, the majority of PRs will be for master branch, so there is no
real need to build testing snaps for each of them.
Summing it up:
- Stop building testing snap for each PR
- Build and push on edge channel only merge on `bionic` channel
=> Build snaps only for bionic branch

icons/Suru/scalable/apps/gnome-power-manager-symbolic.svg, icons/Suru/scalable/apps/goa-panel-symbolic.svg, icons/src/symlinks/symbolic/apps.list
Cherry picked from bionic_IconTheme_goa_and_power_symlinks
preferences-system-power-symbolic.svg->gnome-power-manager-symbolic.svg
preferences-desktop-online-accounts-symbolic.svg->goa-panel-symbolic.svg
=> Disco: Cherry-Picked from Bionic branch - New symlinks for gnome-control-center

icons/Suru/scalable/apps/gnome-power-manager-symbolic.svg, icons/Suru/scalable/apps/goa-panel-symbolic.svg, icons/src/symlinks/symbolic/apps.list
I wonder why this suddenly came up in bionic? Has something been backported? O.o
We need a SRU for this to get into 19.04 - any volunteers? ;D @madsrh @ubuntujaggers 
preferences-system-power-symbolic.svg->gnome-power-manager-symbolic.svg
preferences-desktop-online-accounts-symbolic.svg->goa-panel-symbolic.svg
Closes #1259
=> Bionic: New symlinks for gnome-control-center

gtk/src/light/gtk-3.20/_apps.scss
Close button hover color was too dark in Yaru-dark.
Considering that the tab background is always dark in both Yaru and Yaru-dark,
it is not necessary to use a variant-dependent color and an always bright
color can be used instead. Using `porcelain` in this case.
closes #1263
=> Fix gnome-terminal tab close button hover color

gtk/src/light/gtk-3.20/_common.scss
Exclude menu inside popover from the wildcard of transparent background
closes #1272
=> Prevent menu inside popover from having transparent background

build-helpers/prepare-build-snap
Snaps for PR on bionic branch are still build, but directly on the `edge` channel, so that the next snap PR overwrite the previous one.
This change brings back the special naming for PR snap, still on *bionic* branch only
(To be ported to bionic branch, once accepted)
=> Enable again testing snap for bionic PR

gtk/src/light/gtk-3.20/_drawing.scss
Headerbar button in `backdrop-active-insensitive` state has a background
too dark. Changing the color using a similar, but dimmed, color than
`backdrop-active` state for coherence.
Before:
After:
This is the same button on focus
This is an active-backdrop button:
=> drawing: fix hb backdrop active insensitive button

gtk/src/light/gtk-3.20/_common.scss
The treeview focus outline is invisible on white background. This PR changes the outline to the same style than the [global outline](https://github.com/ubuntu/yaru/blob/6a4d98747160c9d28bb0fe1249d4117d37bb472c/gtk/src/light/gtk-3.20/_common.scss#L29).
Before: 
After:
=> Improve treeview focus outline for white background

gtk/src/light/gtk-3.20/_common.scss
Edit: updated with mads correction
@madsrh @ubuntujaggers @clobrano @mpt :innocent: 
Why?
1) We love our orange but it is a problematic color - especially  when it is used as a big surface like the rows. Staring at it every day using ubuntu as my daily driver on my private PC, it becomes really hard for the eyes.
2) The full color selection is a little bit dated, when you comepare it to... 
Spotify
Vscode
Windows10 settings
Gmail on tablets
Battle.net Client
Imgur settings
discourse settings
gnome gitlab
3) it "fits" somehow to firefox tabs design
and To our gnome shell panel button selection
and to our gnome shell workspace selections
=> Testing PR: reduce the orange in selected rows

build-helpers/prepare-build-snap
Now that we refreshed tokens, only use one for both communitheme and
gtk-common-themes snaps.
=> Use single token for both snaps

gtk/src/light/gtk-3.20/_common.scss
This PR was requested by @Feichtmeier [here](https://github.com/ubuntu/yaru/pull/1286#issuecomment-486616054).
=> Bionic: Improve treeview focus outline for white background

gtk/src/light/gtk-3.20/_common.scss, gtk/src/light/gtk-3.20/_drawing.scss
When the border color of the top border is different than the rest of the border, there are dark and washed out edges in the border top where a darker green shines through the lighter green. Probably because gtk lets the background color shine through the green. which is no problem in the light theme but in the headerbar and the darktheme. We changed this already for the headerbar some months ago, this commit does the same for the dark theme in general.
Before:
After:
=> Remove bordercolordifference in darkthemeswitches

gtk/src/light/gtk-3.20/_drawing.scss
Replace `backdrop_color` with `_backdrop_color`
regression introduced with #1317
=> drawing: Fix typo in function name

icons/src/symlinks/generate-symlinks.sh
Add proper CLI interface to generate-symlinks.sh script to help usage.
* Use --help flag to show the usage message.
* Use --all flag to regenerate all the symlinks defined in .list files
* Use --match <string> flag to generate only the symlinks that match the given <string>
```
$ ./generate-symlinks.sh -h
A script for quick generation of symlinks of an in-development icon theme
usage:
generate-symlinks.sh [--all|--match <string>] [--verbose]
options:
-a, --all            Generates all the symlinks defined in .list files
(warning: this might break manually generated symlinks)
-m, --match <string> Generates only the symlinks in .list files that matches
the provided string
-v, --verbose        More verbose output
example:
$ generate-symlinks.sh -m inode-directory
This generates only the link …
```
=> symlink: Improved generate-symlinks script CLI

gtk/src/light/gtk-3.20/_common.scss
In sidebar, selected row has a stronger pressed effect and an orange
left border which does not seem necessary.
Before
After
=> row: no difference between pressed and pressed+selected row

gtk/src/light/gtk-3.20/_common.scss
=> sidebar: fix orange border in selected row's button

gtk/src/light/gtk-3.20/_common.scss
When a viewport is inside a scrolledwindow there is 1 px gap due to
separator's min-width visible only when the row is selected, since
otherwise viewport and separator have the same bg color.
To fix this, let separator's min-width be zero.
closes #1363
=> common: fix 1px gap in sidebar

gtk/src/light/gtk-3.20/_common.scss, gtk/src/light/gtk-3.20/_ubuntu-colors.scss
By introducing headerbar_border_color
and making it dependent on headerbar_bg_color
This way the border changes when the headerbar_bg changes without changing the previously designed color visibly
Inkstone:
lighten($headerbar_bg_color, 8%)
Difference is barely visible:
=> Make headerbar border flexible

gtk/src/light/gtk-3.20/_common.scss
When one opens the popover on selected rows, the row turns orange
This fixes this
=> Fix selected row bug

gtk/src/light/gtk-3.20/_common.scss
The border of linked widgets is gone when you focus the headerbar entry 
This removes the separation
@galgalesh was probably right here
https://github.com/ubuntu/yaru/issues/68#issuecomment-358628766
Eventually caused by https://github.com/ubuntu/yaru/pull/197
=> Fix hb entry border bug

gtk/src/light/gtk-3.20/_common.scss
By setting it to transparent. Previously it became blurry in the backdrop.
@clobrano please see if you like it - if not just close it and let's try other stuff!
Before:
After:
=> Sharpen backdrop headerbar border color

gtk/src/light/gtk-3.20/_common.scss
By setting it to transparent. Previously it became blurry in the backdrop.
Cherry-pick from https://github.com/ubuntu/yaru/pull/1399
=> Bionic: Sharpen backdrop headerbar border color

gtk/src/light/gtk-3.20/_common.scss
depends on https://gitlab.gnome.org/GNOME/nautilus/issues/992
---
Latest nautilus added a `.width-maximized` class style that is applied
to nautilus-path-bar when the windows is "big enough". In such situation, the
nautilus-path-bar changes from left-aligned to centered and it starts moving
together with the `search` button. Yaru did not show any connection
between nautilus-path-bar and search icon, so the two widgets looked floating
in the headerbar with no reason.
Add a path-bar border (only when `.width-maximized` class exists) that
starts from the right end towards the search button to show that a
connection exists (very much like Adwaita does).
Note: path-bar class (i.e. filechooser) did not changed
Closes #1304
Note^2: I noticed some glitches in my VM so that sometimes the path-bar …
=> Fix path-bar-box with width-maximized class

gtk/src/light/gtk-3.20/_common.scss
The wildcard to get the osd styled dark popovers destroys also the selected background color.
Adding yet one more wildcard for every widget in :selected state fixes this
--->
Closes https://github.com/ubuntu/yaru/issues/1406
=> Fix dark popover selected items

icons/Suru/16x16/apps/org.remmina.Remmina.png, icons/Suru/16x16@2x/apps/org.remmina.Remmina.png, icons/Suru/24x24/apps/org.remmina.Remmina.png, icons/Suru/24x24@2x/apps/org.remmina.Remmina.png, icons/Suru/256x256/apps/org.remmina.Remmina.png, icons/Suru/256x256@2x/apps/org.remmina.Remmina.png, icons/Suru/32x32/apps/org.remmina.Remmina.png, icons/Suru/32x32@2x/apps/org.remmina.Remmina.png, icons/Suru/48x48/apps/org.remmina.Remmina.png, icons/Suru/48x48@2x/apps/org.remmina.Remmina.png
I know we likely won't need this for long, but, for completeness, I added the missing symlink for Remmina.  This means Disco will use the Yaru icon for Remmina in the meantime.
Test:
=> Add missing Remmina symlink

icons/Suru/16x16/apps/org.remmina.Remmina.png, icons/Suru/16x16@2x/apps/org.remmina.Remmina.png, icons/Suru/24x24/apps/org.remmina.Remmina.png, icons/Suru/24x24@2x/apps/org.remmina.Remmina.png, icons/Suru/256x256/apps/org.remmina.Remmina.png, icons/Suru/256x256@2x/apps/org.remmina.Remmina.png, icons/Suru/32x32/apps/org.remmina.Remmina.png, icons/Suru/32x32@2x/apps/org.remmina.Remmina.png, icons/Suru/48x48/apps/org.remmina.Remmina.png, icons/Suru/48x48@2x/apps/org.remmina.Remmina.png
This is a cherry pick of #1429, the missing symlink for Remmina, for Bionic.
=> Bionic: Adding missing Remmina symlink

gtk/src/light/gtk-3.20/_tweaks.scss
- fixes headerbars that are not titlebars to be also dark ...
- needs fixing again for selection mode buttons in some apps like gnome-contacts
- also fixing app menu hover state
Merging it now, since inconsistent app titlebars are more of a problem and creating an issue for the selection mode buttons
=> Fix headerbars that are not titlebars

icons/Suru/scalable/apps/camera-app-symbolic.svg, icons/Suru/scalable/apps/filemanager-app-symbolic.svg, icons/Suru/scalable/apps/jockey-symbolic.svg, icons/src/scalable/source-symbolic.svg
I'm doing this as one PR to avoid clashes.
**File Manager**
The symbol has been updated to use the same design as the new full colour:
**Camera**
I drew a camera symbol for the app, but recently found an existing one in Devices.  The existing one is a nicer design, so I retired mine:
**Jockey**
...and we've got a symbol for Jockey:
=> Symbols: Updated file manager, camera, new symbol for Jockey

gtk/src/light/gtk-3.20/_tweaks.scss
- re-inserting selection mode styling
- insert suggested and destructive action buttons
- add comments for each section
- fix some intendation
@clobrano please test the branch, there is a lot diff, because I needed to re-insert many lines
Things tested:
- normal headerbar 
- selection menu in gnome software 
- selection mode in gnome contacts
- selection mode in gnome-music / gnome-videos
- suggested action buttons in headerbars:
- headerbars that are not .titlebar like Gedit:
- appmenu
- appmenu hover
- appmenu active/checked
=> Fixing headerbar

gtk/src/light/gtk-3.20/_colors.scss, gtk/src/light/gtk-3.20/_common.scss, gtk/src/light/gtk-3.20/_tweaks.scss
- use a darker switch border for the dark theme (exactly like upstream)
- use a local var for headerbar buttons
- adjust the headerbar switches in the light theme to the dark headerbar
- Fix selected row slider border this needs to be done upstream for the next cycle, fixing this for EON downstream
=> Switches and switches in the headerbar

gnome-shell/src/gnome-shell-sass/_common.scss, gtk/src/light/gtk-3.20/_drawing.scss
- less diff in gtk and shell
- fixes a bug gnome-contacts focus border bottom for 1px borders
- also fixed jumping in GDM entry, reported this back to upstream
- and two typo fixes from gnome shell master
=> Minor changes to focus borders

gtk/src/light/gtk-3.20/_common.scss
Fine-tune feature currently is not working properly. Instead of making
the slider thicker, it actually changes only the space around causing the
window to shrink.
(peek doesn't seem to show the cursor, but it is over the slider handle)
The fix consists in changing the margin-(top/bottom/left/right) according
to the position of the marks (above/below/etc.).
Note: tested only on slider with marks below for the lack of apps with
the other kind of sliders.
=> Fix slider fine-tune

gnome-shell/src/gnome-shell-sass/_common.scss, gnome-shell/src/key-enter.svg, gnome-shell/src/key-shift-latched-uppercase.svg, gnome-shell/src/key-shift-uppercase.svg, gnome-shell/src/key-shift.svg
- until now some assets where not taken from the yaru paths but from the upstream shell theme
- using links to the build assets fixes this
- needs eventually a correct absolute path to the yaru resource in the future
- using blue for the shift keys
- using green for enter key
- adds white enter key asset
Closes https://github.com/ubuntu/yaru/issues/1475
@3v1n0 @didrocks please review this paths - are the assets still converted into gresources like this? And if not, is this a problem?
Why did I change the paths? Because previously our asset **were not loaded at all** but some fallback to the upstream gnome theme happened
Thus this PR was needed to load out checkboxes:
https://github.com/ubuntu/yaru/pull/1472
@ubuntujaggers @madsrh @clobrano please see if you like this colours
=> FIx asset paths and blue shift keys

icons/Suru/scalable/actions/media-record-symbolic.svg, icons/src/scalable/source-symbolic.svg
I present my greatest artwork to date:
Which gives us:
Closes #1448.
=> Adding white dot symbolic for media-record

gtk/src/light/gtk-3.20/_apps.scss
- remove forced scrollbar colors to make them more visible in the dafult colors but also to make them visible in all color combinations if the user doesnt take the system colors
Gnome software app css:
- remove the commented code for stars which we decided to not ship since it does not really fix the problems of hardly seeable stars in the dark theme and rather makes it look ugly
- also remove code for the infobar in the shell extension tab because it is no longer needed after the upstream refresh
Nautilus:
Remove nautilus css that stopped working
- in nautilus 3.28 we had made selected folders in the main view to only color the label in orange and not the whole icon+image. This stopped working with nautilus 3.30, thus we can remove the code.
upstream bug: …
=> Yaru app gtk theme code changes

gtk/src/light/gtk-3.20/_apps.scss
- copy search entry custom code for nautilus that is only loaded if Adwaita is the current gtk theme https://gitlab.gnome.org/GNOME/nautilus/blob/master/src/resources/css/Adwaita.css#L77
@madsrh and/or @clobrano okay like this? Or further improvements?
Closes https://github.com/ubuntu/yaru/issues/1497
=> Re-add adwaita custom code for search entries

gtk/src/light/gtk-3.20/_apps.scss
- re-inserting custom code from https://gitlab.gnome.org/GNOME/nautilus/blob/master/src/resources/css/Adwaita.css#L60 for the maximized pathbar because this code is only loaded if the theme is Adwaita or Adwaita-dark
- remove the old nautilus window, which is no longer existant for 3.30+
Closes https://github.com/ubuntu/yaru/issues/1500
=> Nautilus custom code

gnome-shell/src/toggle-off.svg
- change the color values of the shell theme toggle-off asset to match the unchecked gtk switches, was previously using the upstream colors
=> Adapt shell toggle to gtk switch

gtk/src/light/gtk-3.20/_apps.scss
Nautilus floating-bar background is transparent, so the label is hard to
see if there's some text behind it.
Fixing it setting the background to solid, using $bg_color value
Also fix text formatting, removing empty spaces.
=> apps: Fix Nautilus floating-bar background

gnome-shell/src/gnome-shell-sass/_colors.scss
Visibly there are only dialogues, popovers and notifications using the bg_color in the shell
Brightening the gtk popovers by 1% needs brightening of the bg_color in the shell because there is no variable for the popup background color in the shell
=> Sync bg_color with gtk popover colors

gnome-shell/src/gnome-shell-sass/_dock.scss, gtk/src/light/gtk-3.20/_colors.scss, gtk/src/light/gtk-3.20/_tweaks.scss
Two actual fixes (actually quiet important):
- use our titlebuttons also in the selection-mode, accidentally they were unstyled
- use a transparent active effect for clicking on a not-selected app in the dock
And some organization (not so important):
- Organize _tweaks.scss
-> remove import of ubuntu-colors because it's already imported into _colors.scss
-> remove small_radius which is no longer needed, new corresponding upstream variable is $button_radius in _common.scss
-> use a $_titlebutton_height for both the min sizes of the titlebuttons and the draw_circle mixin to avoid mistakes
- Use ubuntu-colors in colors
-> actually use the colors we imported instead of using the same hexvalue
Merge either after 19.10 or when we got UI freeze exceptions for this OR if not needed because it is …
=> Gtk and shell theme post 19.10 ui freeze fixes

gnome-shell/src/gnome-shell-sass/_colors.scss
- revert back to the fully opaque dock to apply the transparency change in dashtodock, outside of yaru
=> Dash to dock opaqueness revert

gtk/src/light/gtk-3.20/_apps.scss, gtk/src/light/gtk-3.20/_tweaks.scss, gtk/src/light/gtk-3.20/_ubuntu-colors.scss
Closes https://github.com/ubuntu/yaru/issues/701
A block of extra code for unity in ```_apps.scss```
Doesn't hurt our built in any way. Nothing to fancy.
=> Provide basic unity support

gtk/src/default/gtk-3.20/_apps.scss
Firefox uses ~menubar~ headerbar colors for unfocused tabs in no-titlebar mode, this requires
a dark menubar, but also menuitems require the same style, otherwise they are invisible
(dark text on dark background)
closes #1548
=> apps: Fix invisible menuitems in Firefox under Yaru-ambiance

gtk/src/default/gtk-3.20/_apps.scss
On bionic, desktop icons keep the same label style they have in the
application, which is grey in light variants and so not clearly visible
on a wallpaper.
Re apply white color to desktop icon label color and a dark shadow to
improve contrast on bright wallpapers.
close #1552
=> [bionic] apps: fix desktop icon color label

gtk/src/default/gtk-3.20/_apps.scss
Setting the opacity for scrolledwindow in backdrop - to get opaque
icons under Nautilus in backdrop - breaks Tilix's backdrop transparency.
Limit the setting to Nautilus only fix the issue.
Close #1158
=> apps: limit scrolledwindow backdrop opacity to Nautilus only

communitheme-compat/install-compat.sh
gtk-common-themes builds with communitheme_compat=true.  This was missing the dark variant, so theming is broken on snaps when the user has communitheme-dark set as their gtk theme.
=> When building with communitheme_compat, link the dark varient as well

communitheme-compat/install-compat.sh
gtk-common-themes builds with communitheme_compat=true. This was missing the light variant, so theming is broken on snaps when the user has communitheme-light set as their gtk theme.
=> When building with communitheme_compat, link the light variant

gnome-shell/gnome-shell-sync.sh
Similar to upstream/gtk+3.0/adwayta-sync.sh, this
gnome-shell/gnome-shell-sync.sh is intended to symplify upstream
syncronization.
usage:
$ gnome-shell-sync.sh -d <destination folder>
e.g.
$ gnome-shell-sync.sh -d ./upstream
=> shell: add upstream sync script

gnome-shell/src/install-shell.sh
When creating a package (such as on Arch Linux) using:
`DESTDIR="${pkgdir}" ninja -C build install`
to install all files to `${pkgdir}` for later installation onto an
actual system, ensure the symlink to the shell theme can be created.
The link target should point to a location in `MESON_INSTALL_PREFIX`,
but the link itself should be in `MESON_INSTALL_DESTDIR_PREFIX`.
Furthermore, the link's parent directory needs to be created within
`MESON_INSTALL_DESTDIR_PREFIX` if it does not exist.
Fixes #1583
=> Ensure shell-theme link can be created when using DESTDIR

sounds/src/stereo/system-ready.oga
system-ready sound was not provided in yaru-theme-sound, preventing
ubiquity to play it when the system is ready.
Provide system-ready as symlink to desktop-login
closes LP: #1848217
closes #1575
=> sounds: provide system-ready sound

gtk/src/default/gtk-3.20/_tweaks.scss
- Which was a little bit rushed in the process of introducing Yaru 2.0 (by me! /selfslap)
- Resulting in some unstyled and transparent states and backgrounds
- We expect further modernization of checks/radios upstream instead
Closes https://github.com/ubuntu/yaru/issues/1584
New/old/unmodified upstream look:
=> Remove dowstream check/radio flattening

communitheme-compat/install-compat.sh
`install-compat.sh` currently fails the second time you build Yaru because the softlinks already exist.
This PR fixed that by forcing `ln` to overwrite the existing softlinks.
=> overwrite softlinks so install-compat can handle multiple builds

gtk/src/default/gtk-2.0/gtkrc, gtk/src/light/gtk-2.0/gtkrc
Closes #1539 
((( @clobrano do you think we could rather symlink the gtk2 folder from the mixed theme to the light theme or vice versa? Otherwise one needs to change both gtk2 versions )))
=> Adapt gtk2 menucolor to gtk3

gtk/src/default/gtk-3.20/_colors.scss
- upstream has a darker primary accent color (quiet darkish blue)
- our switch color is a quiet bright green
- darkening the border for the dark theme thus needs to be a bit stronger, resulting in a much less blurry and more **crisp** border
Before:
After:
It's a change inside _colors.scss which we changed anyways for our needs.
It's just a change of the value, no variable was added or removed, and common was not touched.
@madsrh @clobrano @ubuntujaggers 
anyone or everyone of you please see if you like this
(tip: click the images, looking at those dark pictures in a white window is not good)
=> Darken dark theme switch border

gnome-shell/meson.build, gnome-shell/src/install-shell.sh, gnome-shell/src/light/meson.build
Currently yaru gnome-shell theme is installed in the themes directory
/usr/share/themes/<themenane>/gnome-shell, which is where User-Themes
extension looks for 3rd party themes and a symlink is created under
/usr/share/gnome-shell/theme, where Gnome-shell looks for the session's
default theme.
Other than not being formally correct (the default theme should go into
the gnome-shell session's folder), this creates a dependency of the
gnome-shell-theme debian package from the gtk-theme package, that
creates the <themes>/Yaru folder first.
To fix the form and void adding dependency between packages (ideally,
gnome-shell could be installed without the gtk part), Yaru will be
installed under gnome-shell directory and the symlink will be created in
the themes directory, together with the …
=> shell: fix shell installation directories

debian/yaru-theme-gnome-shell.install, debian/yaru-theme-gtk.install
Requires #1596
Include the dark shell theme, and the link to the light shell theme, both in the shell debian package instead of the gtk package.
Tested on Ubuntu 19.10. I initially tried leaving the light shell theme in `/usr/share/themes/Yaru/gnome-shell`, but `dpkg` complained about `/usr/share/gnome-shell/theme/Yaru/gnome-shell.css` not existing - I suppose whatever tool was at work here was not able to follow symlinks. So #1596 looks to be necessary and not just a matter of good form.
=> Include shell themes in the shell Debian package, not the gtk package.

gtk/src/default/gtk-3.20/_tweaks.scss
- this leaves room for further coloring the WHOLE toolkit via $bg_color in _colors.scss
=> Remove the dedicated hb styling from tweaks

gtk/src/dark/gtk-2.0/gtkrc
This PR fixes the menubar color for dark variant (I picked the color from the given picture in #1539)
closes #1539
=> gtk2: use same color for menu in gtk2 and gtk3

gnome-shell/src/gnome-shell-sass/_common.scss, gtk/src/default/gtk-3.20/_colors.scss
- $selected_bg_color darkens by 8% in the dark theme
- $progress_bg_color didn't, thus being a bit too bright in the dark themes
- darkening it also by 4% fixes this
Result is a slightly darker blue in the dark theme
Comparison to the light theme:
@clobrano and/or @madsrh and/or @ubuntujaggers please see if you like this
=> Darken progress blue in dark themes

icons/Suru/scalable/actions/favorite-new-symbolic.svg, icons/Suru/scalable/emblems/emblem-system-symbolic.svg, icons/Suru/scalable/mimetypes/application-x-addon-symbolic.svg, icons/Suru/scalable/status/volume-warning-symbolic.svg, icons/src/scalable/source-symbolic.svg
While I was editing source-symbolic, I took the opportunity to export four symbols that were exporting but had been missed for some reason (possibly because they were untracked).  Closes #1608 .
favorite-new-symbolic:
emblem-system-symbolic:
application-x-addon-symbolic:
volume-warning-symbolic:
=> Four missing symbols including application-x-addon

gtk/upstream/nautilus/Adwaita.css, gtk/upstream/nautilus/nautilus-custom-css.sync
Nautilus uses a custom CSS specifically for Adwaita with some modification
that Yaru needs as well. To make it easier to look for changes, this
commit adds a script that download such css from Nautilus repo.
Also adding current version of Nautilus' css (Adwaita.css) for future
comparison.
=> script: Add sync script for Nautilus

gtk/src/default/gtk-3.20/_tweaks.scss
They are actually already gone for the headerbar buttons.
I think I used the wildcard wrong, this should be the correct way of removing them.
+ Removing also the icon shadows since we already have icon shadows for full color icons (they dont have that shadows in icon upstream)
=> Remove text and iconshadows for headerbar and buttons

gnome-shell/src/gnome-shell-sass/_dock.scss
Remove .opaque and .transparent classes styling from yaru's dock stylesheet
Closes #1649
=> fix dock background opacity to dynamic

icons/Suru/scalable/categories/applications-graphics-symbolic.svg, icons/Suru/scalable/categories/applications-utilities-symbolic.svg, icons/Suru/scalable/categories/preferences-other-symbolic.svg, icons/src/scalable/source-symbolic.svg
This PR has the following changes:
- applications-utilities-symbolic has changed from pencil/ruler to a Swiss army knife, to more closely follow Adwaita;
- applications-graphics is now a picture instead of a camera (although the Software Centre category is called Graphics & Photography, the same icon is used for Art & Design in Snap Store and a camera is a bit odd there);
- There's a new icon for preferences-other-symbolic (far right in following image)...  it's not amazing but hopefully will do for now?
This is how the categories now look in Software Centre - click to see them sharply, the image is slightly shrunk in this github post:
No idea why the app picks up the help icon for Science instead of my lovely test tube  :(  but there's not a symlink for it in categories or anything.
=> Icon theme: improvements to categories

gtk/src/default/meson.build, gtk/src/default/unity/meson.build, gtk/src/install-theme.sh
Add missing build configuration for Unity assets
Light and Dark variant assets are installed as symlink to the default
theme.
see #1670
=> unity: install assets with meson build system

gnome-shell/src/gnome-shell-sass/_colors.scss, gnome-shell/src/gnome-shell-sass/_common.scss, gnome-shell/src/gnome-shell-sass/_drawing.scss, gnome-shell/src/gnome-shell-sass/_ubuntu-colors.scss, gtk/src/default/gtk-3.20/_colors.scss, gtk/src/default/gtk-3.20/_drawing.scss, gtk/src/default/gtk-3.20/_headerbar.scss, gtk/src/default/gtk-3.20/_tweaks.scss, gtk/src/default/gtk-3.20/_ubuntu-colors.scss, gtk/src/default/gtk-3.20/assets/bullet-symbolic.svg, gtk/src/default/gtk-3.20/assets/check-symbolic.svg
As one of the outcomes of the design fest :gb: this pull request wants to merge the following into master:
*The official canonical vanilla colours*
- ```#f7f7f7``` as the new background colour for the light theme(s)
- ```#0e8420``` as the new green, now only used for positive/suggested things
- ```#f99b11``` as the new yellow, only used as a warning colour
- ```#335280``` as an additional blue second accent colour used as an replacement for both, the old green and the bright blue
- ```#007aa6``` as an additional new blue only used as the link colour
- ```#c7162b``` as the new red only used for destructive/negative elements
*Colour and contrast improvements*
- lighten the background colour of the dark themes slightly but darken the border colours of both the light and the dark themes-
- …
=> "Yaru 3.0" - colour set sync, button overhaul and contrast improvements

gnome-shell/src/gnome-shell-sass/_colors.scss, gnome-shell/src/gnome-shell-sass/_common.scss, gnome-shell/src/gnome-shell-sass/_ubuntu-colors.scss, gnome-shell/src/toggle-off-dark.svg, gnome-shell/src/toggle-off-intl.svg, gnome-shell/src/toggle-off.svg, gnome-shell/src/toggle-on-dark.svg, gnome-shell/src/toggle-on-hc.svg, gnome-shell/src/toggle-on-intl.svg, gnome-shell/src/toggle-on.svg, gtk/src/default/gtk-3.20/_colors.scss, gtk/src/default/gtk-3.20/_common.scss, gtk/src/default/gtk-3.20/_ubuntu-colors.scss
As per PR title, this change is a try for replacing the blue with aubergine. The color relationships between the widget that used blue are kept the same, that is:
- checkradio, switch and progress bar share the same dark tone (aubergine in this case)
- focus ring is a lighter variant than the color for the widgets above
- **link color is still blue**, since aubergine is usually used for "visited link" and might be misunderstood  
TODO:
- check what gtk2 is using (probably only orange, but let's double check) -> see #1730 
- gtk dark: slider-has-mark... is too dark (review the assets) -> see #1728
- [from @madsrh] consider #6e3c61 as base aubergine (for checkboxes, sliders, switches) -> see #1731 
EDIT: to avoid blocking development too much, I opened bug/discussion tickets for the …
=> Use Aubergine as second accent color instead of blue

gnome-shell/src/gnome-shell-sass/_colors.scss, gnome-shell/src/gnome-shell-sass/_ubuntu-colors.scss, gtk/src/default/gtk-3.0/_colors.scss, gtk/src/default/gtk-3.20/_apps.scss, gtk/src/default/gtk-3.20/_colors.scss, gtk/src/default/gtk-3.20/_drawing.scss, gtk/src/default/gtk-3.20/_headerbar.scss, gtk/src/default/gtk-3.20/_tweaks.scss, gtk/src/default/gtk-3.20/_ubuntu-colors.scss, gtk/src/default/gtk-3.20/gtk.scss
- Restructure the _ubuntu-colors.scss to only include our palette (though yet incomplete) and move widget colors to _colors.scss
- Move the two last used terminal colors to _apps.scss and include an underscore to make them not global
- move the @include _tweaks.scss out of _headerbar.scss and include them in gtk.scss to only have the build decide how to create the variants
- don't do if($variant...) checks in the palette file
- don't change any color values in this PR beside $switch_border_color
Closes https://github.com/ubuntu/yaru/issues/1732
No changes to any design or colors (except switch border color)... proof:
=> Reorganize colors and includes

gtk/src/default/gtk-3.20/_tweaks.scss
Use popover hover color for menuitems inside the menu bar
see #1703
=> gtk: grey selected filemenu item

gnome-shell/src/gnome-shell-sass/_colors.scss, gnome-shell/src/gnome-shell-sass/_dock.scss, gtk/src/default/gtk-3.20/_colors.scss, gtk/src/default/gtk-3.20/_headerbar.scss
- vanilla green looks great but it is a little bit too dark for gtk and gnome shell
- Lighten up all greens by 5% (shell and gtk)
(Left old, right upper side new [5% lighter])
- adapt the green border for mixed theme pressed buttons in the headerbar to look in the other themes: same color as the bg
(Pressed button: )
=> Green color improvements

gtk/src/default/gtk-3.20/_tweaks.scss
On hover, notebook tab's text is grey and so it might be mistaken for
disabled.
This change sets for tab's text on hover the same color that unchecked
tab's text have.
Moreover it sets a slightly brighter background color, still less than
checked tabs, to provide more feedback to the user.
closes #1762
=> tweaks: notebook tab hover text color

gnome-shell/src/gnome-shell-sass/_common.scss
Using deep dark border for scrollbar makes the scrollbar look way
smaller than in light variant and also clashes with the current border
of overdrive.
This change aligns the active scrollbar border to the overdrive one,
using a darker aubergine instead that a dark color. This, of course,
only for the dark variant.
Before
After
Before with overdrive
After with overdrive
=> shell: improve scrollbar border in dark mode

gtk/src/default/gtk-3.20/_colors.scss
More contrast for context menus and popovers 🙈 
This might be a bit too much but IMO the backgrounds in master still blend a bit together 🤷‍♂ 
Left is master and right is `lighten(bg_color, 2%)`
=> TESTING PR: More contrast for context menus

gtk/src/default/gtk-3.20/_apps.scss
I thought there was a simple way of doing this:
```
$_alpha: if($variant=='light', 0.08, 0.16);
$_separator_color: rgba(0, 0, 0, $_alpha);
background-image: image($_separator_color);
```
It turns out my solution looks just as complicated, but at least it uses the `$border_color ` variable.
`background-image: image(if($variant=='light', transparentize($borders_color, 0.6), darken($borders_color, 1%)));`
=> Small code change

gtk/src/default/gtk-3.20/_common.scss, gtk/src/default/gtk-3.20/_tweaks.scss
- change the global variable
- add a line in tweaks for axing the min-width
- "low hanging fruit" for upstream contribution as this also happens to upstream default sizes
Closes #1806
=> Fix circular button padding

gtk/src/default/gtk-3.20/_headerbar.scss
Use a lighter dark color for headerbar button border in backdrop (only for default theme)
see https://github.com/ubuntu/yaru/pull/1759#issuecomment-576021449
=> headerbar: lighter backdrop button border

gtk/src/default/gtk-3.20/_colors.scss, gtk/src/default/gtk-3.20/_drawing.scss, gtk/src/default/gtk-3.20/_tweaks.scss
The focus ring (outline) of the following widgets have been reviewd
taking care of their peculiarities
- button
it required a change in drawing, where the outline-color was
somehow hardcoded
- switch
- check/radio button
- row (selected/unselected)
it required - in selected state - a different outline. When
selected, the row's background is a solid orange, where the
standard aubergine outline is not visible enough. For this
reason bg_color has been choosen. Moreover, since bg_color
is the same as the row's backgroud window, a dashed line has
been preferred, so that it is clear that it is an outline and
not a border or a smaller row.
=> focus ring: review focus ring for some widgets

gtk/src/default/gtk-3.20/_colors.scss, gtk/src/default/gtk-3.20/_tweaks.scss
it was basically invisible before:
After:
=> Gtk dark theme: make headerbar border visible again

gtk/src/default/gtk-3.20/_tweaks.scss
- gtk defaults the outline to be on the switch sliders
- the new focus ring style plus the new switch bg color creates a blurry "experience"
- setting the outline on the slider to transparent
- adding a 3px spread box-shadow, opacified and lightened in the light themes(s)
Closes #1822
=> Special case switch focus

gtk/src/default/gtk-3.20/_common.scss
Currently, backdrop link color is orange, instead that some blue.
This has been alredy fixed upstream
https://gitlab.gnome.org/GNOME/gtk/merge_requests/1201
but it does not seem available yet, so this change manually cherry-picks it in Yaru.
=> common: fix backdrop link color

gtk/src/default/gtk-3.20/_colors.scss, gtk/src/default/gtk-3.20/_common.scss, gtk/src/default/gtk-3.20/_drawing.scss, gtk/src/default/gtk-3.20/_tweaks.scss
Closes #1844 
Closes #1840 
Closes #1838
- Add more comments to describe why we diverge from upstream for a certain widget
- Remove useless switch re-styling that is not nessecary
- Special case more widgets for the outline
- special case selected rows
- separating this in a second commit to eventually revert it
- upstream is highly interested in this
- the %linked_XXX classes are used all over the _common file, changing those 10 lines is the least problematic and probably the place where upstream wants the change
((( click the gifs to see it bigger )))
@clobrano currently trying to get the second commit done for upstream - let's see. Their UI freeze is independent from our UI freeze so if I get this into upstream before our UI freeze I can remove the changes from common
=> Gtk theme outline fixes

gtk/src/default/gtk-3.20/_drawing.scss
Current master:
Fixed: 
(same with default and dark)
=> Fix headerbar distorted transition

gtk/src/default/gtk-3.20/_headerbar.scss
- adapt the backdrop disabled button color to the headerbar
Closes https://github.com/ubuntu/yaru/issues/1869
- slightly improve background and border of suggested-action disabled buttons in active and backdrop windows:
Closes https://github.com/ubuntu/yaru/issues/1842
=> Default theme: disabled button improvements

gtk/src/default/gtk-3.20/_tweaks.scss
- Set the min-height of color buttons to the half of the headerbar, works for the default sizing of upstream and the compact sizing we use
- If the min-height is not set, it stretches compact headerbars
- should be moved to upstream as it is variable
Closes: #1878
=> Fix for color chose buttons

gtk/src/default/gtk-3.20/_tweaks.scss
- unify the color of the :checked button borders in the headerbar, because uneven border colors make the button look more pressed than necessary without improving the legibility
- this is also more consistent with the default theme :checked headerbar buttons
Before:
After:
Default theme:
@madsrh @clobrano @ubuntujaggers ?
=> Light and dark theme headerbar button border improvements

gtk/src/default/gtk-3.20/_headerbar.scss
Adapt borders and backgrounds better to the default theme headerbar colors.
(this gif covers :checked not(:checked) and :disabled switches for active and backdrop windows, best would be if you check out this branch locally and build yourself) 
@clobrano @madsrh please see if you like it. It turned out that I have the impression that it looks better with a darker slider. Also the borders don't fuzz out on a dark headerbar now. WDYT?
Closes #1839
=> Default theme: re-style switches

gtk/src/default/gtk-3.20/_headerbar.scss
The separator color in the backdrop was too strong.
With this commit we bind the color of the separators in the headerbar of the default theme to the headerbarcolor which also improves the :backdrop color. Changing the headerbar color should now change the separator color accordingly.
Before:
After:
Note: if you think the active window color needs improvement, we can do this. But anything is better than a set hex color :D (which was probably me in the rush of 19.10)
=> Default theme: headerbar separator improvements

icons/Suru/16x16/devices/media-removable.png, icons/Suru/16x16@2x/devices/media-removable.png, icons/Suru/24x24/devices/media-removable.png, icons/Suru/24x24@2x/devices/media-removable.png, icons/Suru/256x256/devices/media-removable.png, icons/Suru/256x256@2x/devices/media-removable.png, icons/Suru/32x32/devices/media-removable.png, icons/Suru/32x32@2x/devices/media-removable.png, icons/Suru/48x48/devices/media-removable.png, icons/Suru/48x48@2x/devices/media-removable.png, icons/src/symlinks/fullcolor/devices.list
We can work out how to do this better (if it's within the gift of the theme, rather than an upstream quirk) but in the meantime I thought it would be good to add this symlink, to prevent a symbol appearing in a full colour context.  @Jupiter007-43, grateful if you could test!
Closes #1859
=> Adding symlink drive-removable-media-usb --> media-removable

gtk/src/default/gtk-3.20/_headerbar.scss
Remove the box-shadow and even out the border of switches inside the headerbar of the datk theme in the backdrop.
=> Default theme: switch backdrop improvements

gtk/src/default/gtk-3.20/_tweaks.scss
Since notebooks and entries both use $base_color, entries drown in the dark theme, looking almost disabled. Darkening them for the dark theme only in notebooks helps here. We reduce the change for notebooks only since it is safe to say that the $base_color won't be changed by apps. Everywhere else it is not clear where the entries are drawn.
Closes #1784
=> Dark theme: darken entries in notebooks

gtk/src/default/gtk-3.20/_apps.scss
A third (#1831 and https://github.com/ubuntu/yaru/pull/48) attempt at removing the orange tint on the icons in Nautilus.
This is VERY close, but I need the wizard skills of @Feichtmeier or @clobrano to fix the label color when right clicking :disappointed: 
I don't know why, but the label is gray in the dark theme but "invisible" in the light theme.
=> Remove orange tint on icons

gtk/src/default/gtk-3.20/_apps.scss
- only style .nautilus-canvas-item, not all widget.view
- remove the outline ring, not needed because the focus is already orange and it corrupts the label
- remove the background then bring it back for dir(ltr)
@clobrano @madsrh 
I hope you like the backdrop color
I also removed the outline ring because I don't think that it's nessecary because I think there is no room for the focus ring in this tiny label - WDYT?
Closes: #43
Closes: #1914
=> nautilus: complete do not color folder on selection

gnome-shell/src/gnome-shell-sass/_common.scss, gtk/src/default/gtk-3.20/_colors.scss, gtk/src/default/gtk-3.20/_common.scss, gtk/src/default/gtk-3.20/_tweaks.scss
Replace current orange with a silver-ish color for mouse selection
- gtk rubberband (e.g. Nautilus folder selection with mouse)
- shell rubberband (e.g. Desktop Icon selection and area screenshot)
- shell tile-window-preview (e.g. snapping windows on left/right side of the screen)
Co-authored-by: MadsRH <madsrh@gmail.com>
Closes: #1727
=> shell/gtk: use silver color for mouse selection

gtk/src/default/gtk-3.20/_apps.scss, gtk/upstream/nautilus/Adwaita.css
- Take the nautilus in app code and convert the styles for yaru
- Slightly adjust the free disk space colors for the light theme(s)
- fix the border color for the default theme ($ambiance)
Closes #1807 
Before:
For some reason they use a black border here... :thinking: 
After:
=> Gtk theme upstream nautilus sync + fixes

gnome-shell/src/gnome-shell-sass/_widgets.scss
This is a regression caused by me in the upstream shell sync
Before:
After:
=> Round the desktop icons

gtk/src/default/gtk-3.20/_apps.scss
Make the circles real circles and not stretched circles :) 
As pointed out by @friendlyapple 
Before:
After:
=> Make ubiquity progressbars look like real circles

gtk/src/default/gtk-3.20/_headerbar.scss
=> Headerbars.scss: sharpen sliders

gtk/src/default/gtk-3.20/_tweaks.scss
The selected_bg_color is leaking through a disabled check in a treeview. This tweak fixes this. Should move to upstream as they are affected, too.
Before:
After:
Closes #1743
=> Gtk3: Fix for checks in selected treeviews

gnome-shell/src/gnome-shell-sass/widgets/_misc.scss, gnome-shell/src/gnome-shell-sass/widgets/_tiled-previews.scss
re-apply #1883 to the shell, since it was lost after upstream rebase
Closes: #1727
=> shell: re-use silver color for mouse selection

gtk/src/default/gtk-3.20/_tweaks.scss
Include more headerbars (hopefully all) for styling their button borders equally when active. See https://github.com/ubuntu/yaru/pull/1898
For example Gedit and Rhythmbox were missing.
=> Gtk3: headerbar button fixes

gtk/src/default/gtk-3.20/_tweaks.scss
=> Gtk3: Make all :not:(.empty) level bars green

gnome-shell/src/gnome-shell-sass/widgets/_app-grid.scss
So it stays variant independent, should be moved to upstream since they have forgotten this
Before:
After:
=> ShellTheme: color app grid rename dialog label

gtk/src/default/gtk-3.20/_tweaks.scss
In default and light variant, the disabled checked switch is the same as non-disabled one. In the dark variant, the only difference is the handle.
This is due to the need to move our switch style to tweaks to reduce upstream diff in common, so the fix consists in porting some missing styling from common to tweaks.
Closes: #2016
=> switch: stronger disabled state in default and light variants

gnome-shell/src/gnome-shell-sass/widgets/_tiled-previews.scss
Currently, tile-preview has rounded corner as in upstream, but in Ubuntu
the dock is not rounded, then the tile-preview corners shall be
straight.
Closes: #2021
=> shell: tile-preview has straight corners in Yaru

icons/Suru/scalable/categories/accessories-dictionary-symbolic.svg, icons/Suru/scalable/categories/document-page-setup-symbolic.svg, icons/src/scalable/source-symbolic.svg
Excuse the typo in the branch name!!
Snap Store is looking for the following two icons for two of the missing categories (just need a name for the fitness icon now):
**accessories-dictionary-symbolic** (for "Books & Reference")
For this one I simply copied an appropriate symbol that already exists.
**document-page-setup-symbolic** (for "Education" - note that this won't work until upstream fix the fact that the app looks for document-page-setup, rather than document-page-setup-symbolic - that's why a colour icon is seen currently):
For this one I drew a new symbol which works for both education and page setup.  In fact, I followed the metaphor of the colour icon that's currently seen:
=> Adding Snap Store category symbols for Reference and Education

gnome-shell/src/gnome-shell-sass/_drawing.scss, gnome-shell/src/gnome-shell-sass/widgets/_app-grid.scss
- removed !important assigment from _drawing, so it does not overwrite app grid buttons, reduces diff with upstream and makes more sense
=> ShellTheme: reduce diff in drawing and app-grid

gtk/src/default/gtk-3.20/_common.scss, gtk/src/default/gtk-3.20/_tweaks.scss
Remove this from tweaks as it introduced bugs. The only riskfree way of changing the headerbar outside of _common is to fully re-style it, like we did in _headerbar.scss for the default theme. Asking upstream to fix this uneven borders so the diff is gone again.
Closes #2028
=> Fix headerbar button regression caused by #2010

gtk/src/default/gtk-3.20/_colors.scss
I have the impression that we need to increase the contrast of borders in the dark theme a bit more, especially while looking on Adwaita-dark for a while, they do better there:
Adwaita-dark:
Before:
After:
Please see if you agree @clobrano @madsrh @ubuntujaggers
=> Dark gtk3 theme: darken $borders_color by 2%

gtk/src/default/gtk-3.20/_headerbar.scss, gtk/src/default/gtk-3.20/gtk.scss
headerbar.scss is parsed after tweaks.scss, removing the outline definition. The less risky action is to re-set it in headerbar
Closes: #2019
=> headerbar: custom outline for suggested-action button

gtk/src/default/gtk-3.20/_apps.scss
- remove gnome-photos tweak, there is no reason to tweak here in a not pre-installed application plus it actually looks worse without the black background in the grid
- remove chromium bright border for the dark theme, this is an artifact styling when we had OSD-like context menus in "Yaru 1.0"
=> Clean up third party app styling

gtk/src/default/gtk-3.20/_colors.scss
when looking at the unfilled progressbars with a border versus the part of the progressbar that is filled, it looks like the progressbar is 1px bigger when filled, which is not exactly clean.
Darkening the progressbars slightly in the dark and light themes fixes this and also increases the contrast to the background, no matter if the progressbar sits on $bg_color or $base_color
Closes https://github.com/ubuntu/yaru/issues/2031
=> Gtk3: darken progressbar border colors

gtk/src/default/gtk-3.20/_headerbar.scss
Fix headerbar suggested button outline's states styling missing from #2033
=> headerbar: fix missing states in suggested button outline

gtk/src/default/gtk-3.20/_drawing.scss
Give check/radio backdrop a border-color so it doesnt change on hover
Before:
After:
Closes https://github.com/ubuntu/yaru/issues/2049
=> Fix check/radio backdrop

gnome-shell/src/meson.build
in order to make use of User Themes extension, both theme variants need
to be under `/usr/share/themes/<theme-name>/gnome-shell, but Yaru-dark
was missing.
Add back the symlink to Yaru-dark shell variant
Closes: #2043
=> build/shell: symlink shell variants to alternate theme directory

gnome-shell/src/eye-not-looking-symbolic.svg, gnome-shell/src/eye-open-negative-filled-symbolic.svg
Not sure how to test these because my password field on the lock screen doesn't have the eye symbol:
Closes #2026
=> Adding eye assets with thinner strokes

gtk/src/default/gtk-3.20/_common.scss, gtk/src/default/gtk-3.20/_headerbar.scss
cherry-pick #2072
* headerbar: use the same backdrop border color of dark variant
* headerbar: make button background color the same as dark variant
* common: remove whitespaces
* reduce difference in headerbar insensitive buttons
=> Reduce differences between default and dark variant headerbar buttons

icons/Suru/16x16/legacy/object-locked.svg, icons/Suru/16x16/legacy/object-unlocked.svg
Trying to fix the issue where the lock icon for layers in Inkscape isn't visible because of the red / green clashing with the orange selection.
Before:
After:
=> Legacy icon for object locked / unlocked

gtk/src/default/gtk-3.20/_apps.scss, gtk/src/default/gtk-3.20/_tweaks.scss
In order to show when the tab has "just got" the focus with keyboard the
outline is still necessary.
Add a thinner style for tab's outline, since the normal 2px outline
seems too heavy for this widget.
Fixes: #2114
=> tweaks: outline for tabs

gtk/src/default/gtk-3.0/_common.scss, gtk/src/default/gtk-3.20/_headerbar.scss
libsass 3.6.3 do not support any more compound selector
Fixes: #2079
=> headerbar: do not use compound selectors

bootstrap.sh
In order to simplify and share the same build and testing approach, I wrote the `bootstrap.sh` script.
```
usage:
bootstrap.sh --development
bootstrap.sh --testing
bootstrap.sh --build
options:
-d, --development Install the dependencies for building and installing Yaru theme
-t, --testing     Install the dependencies for testing an already installed Yaru theme
-b, --build       Build and install Yaru theme
```
=> onboarding: add bootstrap bash script

gnome-shell/src/calendar-today.svg
In the default Yaru shell theme, the calendar dot of days having an
appointments is not visible. The dark shell theme is not affected.
The problem is due to the color of calendar-today.svg being too similar
to the calendar background.
Fix consists in changing the color of calendar-today.svg in a way that
is both visible in the light and dark shell theme.
Fixes: https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1870938
=> gnome-shell/calendar: darken event dot

gtk/src/default/gtk-3.0/_common.scss
with libsass>3.6.2 compound selectors may not be extended anymore.
using placeholder selector instead (%)
Closes: #2079
=> do not extend compound selectors in gtk-3.0

gnome-shell/src/gnome-shell-sass/widgets/_calendar.scss
When a non-working day has events, the color is different from other
non-working days without any event.
This happens because the color of days with events is set explicitly,
this might be wanted, but the view looks uneven this way.
To prevent this, do not explicitly set a specific color for days
with events. The color is expected to stay the same regardless the day
being a working or non-working one.
=> gnome-shell/calendar: do not change color of day with events

gnome-shell/src/gnome-shell-sass/widgets/_switcher-popup.scss
Currently the highlighted app in switcher-popup has low contrast
respect the background, and eventually poor visibility in some
light conditions.
Improve contrast with a slightly brighter highlighted app background
=> shell/switcher-popup: improve contrast of highlighted app

gnome-shell/src/gnome-shell-sass/widgets/_login-dialog.scss
=> gnome-shell: Use $osd_fg_color for all the login messages

gnome-shell/src/gnome-shell-sass/_dock.scss
And sync settings from [upstream stylesheet](https://github.com/micheleg/dash-to-dock/blob/ubuntu-dock/stylesheet.css).
=> Dash to dock padding fixes

gtk/src/default/gtk-3.20/_tweaks.scss
Bright blue spinners on bright green/red buttons looks weird. This can happen in simple-scan.
This special cases those situations and uses selected_fg_color instead, keeps the blue spinner for the rest.
Closes https://github.com/ubuntu/yaru/issues/2182
@clobrano please test this
=> Special case  spinners in destructive, suggested action buttons

gnome-shell/src/gnome-shell-sass/_colors.scss, gnome-shell/src/gnome-shell-sass/widgets/_osd.scss
Style .button with %button and use osd colors for the window
@madsrh @clobrano they want to fix it for 3.38 I think (looking at their tags), and since I think this bug should be fixed as soon as possible for 20.04 wacom users, let's get this in?
Closes #2099
=> Make wacom overlay visible

gnome-shell/src/gnome-shell-sass/_colors.scss
Shell: revert insensitive fg color change
Introduced with https://github.com/ubuntu/yaru/pull/2198
=> Shell: revert insensitive fg color change

gtk/src/post_install.py
The Arch AUR package was failing to build after #1884
This is because the new `post_install.py` script uses the `MESON_INSTALL_PREFIX` environment variable to determine which paths to rename, whereas the Arch package is installed to `DESTDIR` with:
`DESTDIR="${pkgdir}" ninja -C build install`
to install all files to `${pkgdir}` for later installation onto an actual system.
This is essentially the same issue that occurred in #1583
I believe using `MESON_INSTALL_DESTDIR_PREFIX` instead solves the issue. At least, it works for the AUR package, and since I made essentially the same fix for the gnome-shell theme in #1585 I am guessing this works for installs not using `DESTDIR` as well. Since IIUC `MESON_INSTALL_DESTDIR_PREFIX` is always set and is the concatenation of `DESTDIR` (if any) with …
=> Use MESON_INSTALL_DESTDIR_PREFIX in post_install.py

gtk/src/default/gtk-3.20/_tweaks.scss
"backrop" instead than "backdrop"
Fixes: #2207
=> Fix spinner typo in tweaks.scss

icons/Suru/scalable/apps/system-users-symbolic.svg, icons/src/scalable/source-symbolic.svg
As requested for Lollypop, which uses this symbol to stand for Compilations:
Closes #1988 ???
=> Adding second user to system-users-symbolic

gtk/src/default/gtk-3.20/_apps.scss
Added missing highlighting for selected text when renaming files in Nemo (#2183), as well as shading for the unfocused pane in split pane mode (the right pane in the screenshots). (Based on the fallback code that implements this in Nemo for unsupported themes.)
(2nd PR, as #2218 didn't update with new commit)
=> Nemo selected text highlighting and inactive pane shading

gtk/src/default/gtk-3.20/_colors.scss, gtk/src/default/gtk-3.20/_tweaks.scss
_colors.scss: Switch menu background color back to white to let them "pop" out more for the light theme(s), no change for the dark theme
_tweaks.css: Increase the menu shadow for all themes, to make them more visible on the background they are drawn upon
Closes #2221 
@clobrano and/or @madsrh and/or @ubuntujaggers and/or @Jupiter007-43 please test all three gtk3 themes and share your opinion. 
Preview screenshots following but I would really test this on your screens etc etc:
=> Gtk3: increase menu visibility

gnome-shell/src/gnome-shell-sass/_colors.scss, gnome-shell/src/gnome-shell-sass/widgets/_notifications.scss
Light/Dark shell theme: add a dedicated box-shadow to notifications to make them more visible against different backgrounds
Dark shell theme: adapt $borders_color to the gtk3 $borders_color which makes shell popups and notifications more visible and more sharp and less blurry against different backgrounds. Also increases consistency with the gtk3 theme
Closes #2217 
(zoom in)
=> Shell: popup and notification improvements

gtk/src/default/gtk-3.20/_apps.scss
Nautilus column label color is too gray and unreadable when selected and
in backdrop.
This seems to be due to a previous fix (#2113) which I can not reproduce
anymore anyway, so the best thing to do is to remove the old code.
Closes: #2216
=> Nautilus: fix gray label in backdrop

icons/src/fullcolor/mimetypes/application-x-virtualbox-hdd.svg, icons/src/fullcolor/mimetypes/application-x-virtualbox-ova.svg, icons/src/fullcolor/mimetypes/application-x-virtualbox-ovf.svg, icons/src/fullcolor/mimetypes/application-x-virtualbox-vbox-extpack.svg, icons/src/fullcolor/mimetypes/application-x-virtualbox-vbox.svg, icons/src/fullcolor/mimetypes/application-x-virtualbox-vdi.svg, icons/src/fullcolor/mimetypes/application-x-virtualbox-vhd.svg, icons/src/fullcolor/mimetypes/application-x-virtualbox-vmdk.svg, icons/src/fullcolor/mimetypes/image-x-cursor.svg, icons/src/fullcolor/mimetypes/text-dockerfile.svg
Hi,
Found these-extras in mimetypes
1) Virtual (all): 
2)cursor:
3)docker:
application-x-virtualbox-hdd.svg (extra jar-text)
application-x-virtualbox-ova.svg (extra jar-text)
application-x-virtualbox-ovf.svg (extra jar-text)
application-x-virtualbox-vbox-extpack.svg (extra jar-text)
application-x-virtualbox-vbox.svg (extra jar-text)
application-x-virtualbox-vdi.svg (extra jar-text)
application-x-virtualbox-vhd.svg (extra jar-text)
application-x-virtualbox-vmdk.svg (extra jar-text)
image-x-cursor.svg (extra Pictogram-layer of application-json.svg)
text-dockerfile.svg (extra Pictogram-layer of text-x-qml.svg)
Thanks!
=> Removes extra texts and layers from the following mimetype

icons/src/fullcolor/mimetypes/text-x-systemd-unit.svg
I accidently pushed the _systemd_ icon to master 🤦‍♂️ 
In the .SVG there are two versions of the icon. The current hidden layer - that this PR removes - contains [the original logo](https://systemd.io/). I found the original logo to be not great at small sizes, so what's now in master (doh) is a squeezed version. 
The squeezed version also renders better, but it's a bit blasphemous to change a logo. Just imagine if it was something else:
Screenshots explains the two versions better: 😄  
This is the squeezed version:
@clobrano @Feichtmeier if you're fine with current version you can just merge this PR
=> Fix for systemd mimetype icon in master

icons/src/scalable/README.md, icons/src/scalable/extract-symbolic-icons.rb
Rework extract-symbolic-icons ruby script 
- streamline "main" function
- forbid running the app with no arguments to avoid using the script the wrong way
- improve CLI arguments parsing (it needs docopt, install it with gem install docopt)
- improve function naming when possible
- let the system chose which inkscape/svgo binaries to use
- improve documentation
This new version adds a help message, which examples
$ ./extract-symbolic-icons.rb --help
Usage:
./extract-symbolic-icons.rb [force] all
./extract-symbolic-icons.rb [force] only <icon>...
Options:
all     extract all icon in the SVG file
only    extract only the list of given icon names
force   force extraction of already existing icon [optional]
Examples:
./extract-symbolic-icons.rb only image1 image2  # render only image1 and …
=> Rework extract symbolic icons

icons/Suru/scalable/apps/gnome-disks-state-standby-symbolic.svg
I reused the same metaphor as upstream (zzz), adding a light gradient of opacity:
Closes #2324
=> Add gnome-disks-state-standby-symbolic icon

icons/Suru/scalable/actions/window-new-symbolic.svg
Brace yerself guys, this is quite a radical change.  I've turned this:
...into this:
I know it's a tiny difference :) but this is quite a high profile symbol because it's used in Nautilus, etc..  What do you think?
=> Making new window icon slightly more rounded

gnome-shell/src/gnome-shell-sass/widgets/_switcher-popup.scss
Use OSD fg color on switcher OSDs
Using $fg_color is wrong and does not work on the light theme in this case. Should be reported upstream someday...
Closes #2320
=> Use OSD fg color on switcher OSDs

gnome-shell/src/gnome-shell-sass/_colors.scss, gnome-shell/src/gnome-shell-sass/_high-contrast-colors.scss, gnome-shell/src/gnome-shell-sass/_palette.scss
Same rework done in gtk folder.
- Rename ubuntu_color.scss into palette.scss to be more generic and facilitate future alternative palette
- add semantic colors for primary and secondary accent colors
=> Rework shell palette

icons/Suru/scalable/actions/selection-symbolic.svg, icons/Suru/scalable/actions/window-symbolic.svg, icons/Suru/scalable/devices/display-symbolic.svg, icons/src/symlinks/symbolic/devices.list
=> Add missing Gnome-screenshot icons

gtk/src/default/gtk-3.20/_apps.scss, gtk/src/default/gtk-3.20/_colors-public.scss, gtk/src/default/gtk-3.20/_common.scss, gtk/src/default/gtk-3.20/_drawing.scss, gtk/src/default/gtk-3.20/_tweaks.scss, gtk/upstream/gtk+3.0/Adwaita/_colors-public.scss, gtk/upstream/gtk+3.0/Adwaita/_common.scss, gtk/upstream/gtk+3.0/Adwaita/gtk-contained-dark.css, gtk/upstream/gtk+3.0/Adwaita/gtk-contained.css, gtk/upstream/nautilus/Adwaita.css
- Upstream fixes for error labels in _common and _drawing
- Exported colors also received two new colors from upstream
- dropping the slim yaru button padding for now, as there are more and more gtk apps using those new big hdy (mobile ready), transformable headerbars, which think of the adwaita padding and thus stretch our small buttons plus custom button widgets that use the adwaita padding can be found across the desktop small buttons look weird along along side these
- added comments for our changes to make it easier for other maintainers to keep our style
- for some reason I had to put code into _tweaks to fix the corners, I checked what upstream does and found nothing on their scss files or in the app css of screenshot and geary, yet adwaita doesnt have this issue. Anyways, fix is …
=> Gtk upstream sync for groovy & several fixes

gtk/src/default/gtk-3.20/_tweaks.scss
no longer needed after we use adwaita padding. if we use it, it over trims circular buttons in rows
Before:
After:
=> _tweaks: remove circular button min-width

gtk/src/default/gtk-3.20/_drawing.scss, gtk/src/default/gtk-3.20/_tweaks.scss
After we've aligned our button styling to upstream the theme suddenly felt a bit too bulky.
Reducing the button shadows opacity for normal and hover for all three themes by 0.05 and changing the sidebar row selection from orange + white focus ring to light gray + orange focus ring helps.
Closes #2373 
Pictures can be seen here: https://github.com/ubuntu/yaru/issues/2373#issuecomment-701519737
And here:  https://github.com/ubuntu/yaru/issues/2373#issuecomment-701431601
And here: https://github.com/ubuntu/yaru/issues/2373#issuecomment-701522049
=> Gtk theme: less shadows, gray sidebars

gnome-shell/src/gnome-shell-sass/widgets/_calendar.scss
"calendar-other-month-day" with event has a different color than
"calendar-other-month-day" without an event.
"calendar-other-month-day" is a special day, like non-working day, and
should not have a different color, or it would be mistaken for an
in-current-month working day.
Prevent this changing the color of a day with an event only if not a
"calendar-other-month-day".
Closes: #2164
=> calendar-other-month-day color shall not change if the day has an event.

icons/Suru/scalable/actions/globe-centered-symbolic.svg, icons/Suru/scalable/status/alarm-centered-symbolic.svg, icons/src/symlinks/symbolic/actions.list, icons/src/symlinks/symbolic/status.list
hi,
alarm-centerd-symbolic, globe-centered-symbolic are used in gnome-clocks
This will symlink 
**globe-symbolic.svg** to **globe-centered-symbolic.svg** in **scalable/actions**
**alarm-symbolic.svg** to **alarm-centered-symbolic.svg** in **scalable/status**
thanks !
=> added symlinks to alarm-centerd-symbolic, globe-centered-symbolic for gnome-clocks

gtk/src/default/gtk-3.20/_apps.scss, gtk/src/default/gtk-3.20/_colors.scss, gtk/src/default/gtk-3.20/_headerbar.scss, gtk/src/default/gtk-3.20/_tweaks.scss
- align all sidebars to have the same backdrop color, like the rest of the window
- fix default theme headerbar to have the intended, but never correctly set, backdrop color
Closes #2388 
Before:
After:
Dark theme:
Default theme:
Light theme:
@madsrh please test and see if you see stuff I've missed
=> Backdrop text improvements

.github/lpbugtracker.py, .github/workflows/track-lp-issues.yaml, launchpad/yaru_lp_bugs.json
This is an initial deploy for the resources needed to automatically
track LP issues on Yaru-theme package.
This commit contains:
- a python script that uses launchpadlib to get a list of yaru-theme
bugs on Launchpad.
- a new GitHub action yaml file to configure the automation.
- the first copy of the json file containing the LP issues.
The automation is initially supposed to:
1. download the list of LP issues for Yaru and store them in a json file.
2. compare the above list with the one under launchpad/yaru_lp_bugs.json.
3. if the two files differs, the new one is stored and a PR is created.
A maintainer is then supposed to take the list, which contains ID, Title,
and web link, and manually check the issues, eventually adding or removing
bugs.
The python script is able to extract which …
=> Lp bug tracker

.github/lpbugtracker.py, .github/workflows/track-lp-issues.yaml, launchpad/yaru_lp_bugs.json
The goal of this PR is to automatically port issues from Launchpad.
In order to do so, we use [hub](https://github.com/github/hub) inside the LP Github Action. I opted for HUB, because it is advertised as working fine inside a Github Action, reusing the GITHUB_TOKEN.
Hub is not available as debian package, nor as snap (or at least, is discouraged its use), then to avoid build from sources inside the github action, I prebuilt it in my system and uploaded it with this change. Not sure it will work fine.
The script will add only new issues, that is, issues not already saved into launchpad/yaru_lp_issues.json.
=> Create LP issue

gtk/src/default/gtk-3.20/_common.scss, gtk/src/default/gtk-3.20/_tweaks.scss
- in groovy we moved away from altering the upstream button sizes, because those sizes are sometimes hardcoded in gtk apps, which ends in inconsistent button sizes in the desktop (slim beneath big, or vice versa) and because it can cause newer gtk3 apps to have a stretched headerbar
- additionally because gtk-common-themes will receive the updated yaru version from groovy this change destroys the chance gtk3 snaps using yaru have different button sizes than gtk3 debs using yaru
Before:
After:
Closes #2447
=> Sync gtk3 button metrics with upstream & groovy

gnome-shell/gnome-shell-sync.sh
GNOME Shell upstream has broken out widget styling into separate inherited files. Using the sync script does not fetch these files by default. This will add the new files to the list of files to fetch so that changes will be pulled in from upstream when necessary.
=> (gnome-shell): Add widget files to upstream sync script

icons/src/cursors/x11-make.sh
Closes https://github.com/ubuntu/yaru/issues/2451
=> Install grab and wait cursors

gtk/src/dark/gtk-2.0/assets.txt
Some assets of gtk2.0 dark theme were missing in assets.txt. I just copied them from default variant.
=> Added missing GTK2 dark assets

gtk/src/default/gtk-3.20/_common.scss, gtk/src/default/gtk-3.20/_drawing.scss, gtk/src/default/gtk-3.20/_tweaks.scss
I've sadly missed to also sync the corresponding button shadows for this SRU https://bugs.launchpad.net/ubuntu/+source/yaru-theme/+bug/1899731 in https://github.com/ubuntu/yaru/pull/2456
@3v1n0  is it possible to yet include it in the SRU? 
It looks like the .deb is not yet in focal
Pictures are here:
https://github.com/ubuntu/yaru/issues/2373#issuecomment-701519737
(the sidebar change is **_NOT_** included, only the button shadow)
=> Focal groovy gtk theme button shadow sync

icons/Suru/16x16/apps/org.gnome.Shotwell.png, icons/Suru/16x16@2x/apps/org.gnome.Shotwell.png, icons/Suru/24x24/apps/org.gnome.Shotwell.png, icons/Suru/24x24@2x/apps/org.gnome.Shotwell.png, icons/Suru/256x256/apps/org.gnome.Shotwell.png, icons/Suru/256x256@2x/apps/org.gnome.Shotwell.png, icons/Suru/32x32/apps/org.gnome.Shotwell.png, icons/Suru/32x32@2x/apps/org.gnome.Shotwell.png, icons/Suru/48x48/apps/org.gnome.Shotwell.png, icons/Suru/48x48@2x/apps/org.gnome.Shotwell.png, icons/Suru/scalable/apps/og.gnome.Shotwell-symbolic.svg, icons/src/symlinks/fullcolor/apps.list, icons/src/symlinks/symbolic/apps.list
hi, 
This will symlink **shotwell** with **org.gnome.Shotwell** 
**modified files:**
/icons/src/symlinks/fullcolor/apps.list 
/icons/src/symlinks/symbolic/apps.list
thanks!
=> symlink shotwell with org.gnome.Shotwell

icons/Suru/24x24/legacy/tool-tweak.svg
Current one looks nice but metaphor isn't very clear at all... this is the tool that you use to push lines and shapes around like putty:
(The icon is meant to be a blob of putty btw, lol).
This new version makes the function of the tool a lot clearer IMO, even if it's a bit drab:
=> Improving Inkscape tweak tool icon

gtk/src/default/gtk-3.20/_apps.scss
hi,
This will fix #2469, by reapplying #2102 and adding color in **.nautilus-canvas-item** to counter unreadable label when selected
**modified file:**
gtk/src/default/gtk-3.20/_apps.scss
thanks!
=> fix file-lables not dim in nautilus

icons/Suru/16x16/mimetypes/application-x-wine-extension-ini.png, icons/Suru/16x16@2x/mimetypes/application-x-wine-extension-ini.png, icons/Suru/24x24/mimetypes/application-x-wine-extension-ini.png, icons/Suru/24x24@2x/mimetypes/application-x-wine-extension-ini.png, icons/Suru/256x256/mimetypes/application-x-wine-extension-ini.png, icons/Suru/256x256@2x/mimetypes/application-x-wine-extension-ini.png, icons/Suru/32x32/mimetypes/application-x-wine-extension-ini.png, icons/Suru/32x32@2x/mimetypes/application-x-wine-extension-ini.png, icons/Suru/48x48/mimetypes/application-x-wine-extension-ini.png, icons/Suru/48x48@2x/mimetypes/application-x-wine-extension-ini.png, icons/src/symlinks/fullcolor/mimetypes.list
Link **text-x-generic** to **application-x-wine-extension-ini**
.ini file (like **php.ini**) are using **text-x-generic** in normal install of Ubuntu. When installing Wine, they get the **application/x-wine-extension-ini** one. As these files are just plain text, link them to **text-x-generic** restore the default behavior.
Closes #2533 
Related to #2334
=> Add .ini file mimetype

icons/Suru/scalable/places/network-server-symbolic.svg, icons/src/scalable/places/network-server-symbolic.svg
The current server symbol is very angular and not really in keeping with the current Yaru style:
This suggested change makes it a) more like the other symbols and b) more like the full colour server icon:
Just an idea so don't worry if you don't like it :+1:
=> Making network-server-symbolic more like the Yaru style

gtk/src/meson.build, icons/meson.build
Upstream has merged dark panels for the Yaru-MATE theme and Ambiant-MATE icons match a dark panel.
=> icons: Use Ambiant-MATE icons with Yaru-MATE

gtk/src/default/gtk-3.20/_apps.scss
Before:
After:
@flexiondotorg could you double check?
=> darker mate panel colors for default+dark

gtk/src/default/gtk-3.20/_apps.scss
=> Mate: axe border-radii of classic dialog buttons

metacity/src/dark/metacity-1/minimize_focused_prelight.svg, metacity/src/default/metacity-1/minimize_focused_prelight.svg, metacity/src/light/metacity-1/minimize_focused_prelight.svg, metacity/src/metacity-theme-1.xml.in
This pull request refactors/consolidates frame geometry to simplify the Metacity (Marco) theme maintenance. 
Dialog, modal and utility windows now correctly render the title bar and borders in all three variants of the theme.
Shaded windows are now styled. Title bar text clipping is fixed. Focused minimise button pre-light offset has been corrected. Buttons are placed at predictable offsets.
=> metacity: dialog and modal fixes. Shade support added.

metacity/src/metacity-theme-1.xml.in
Some assets still referenced non-existent .png file which prevented the Metacity (Marco) theme preview from rendering and loading.
=> metacity: Fix theme previews and loading

icons/Suru/scalable/apps/ubuntusoftware-symbolic.svg
Hi,
This adds symbolic for Ubuntu-Software (Snap-store) which is used in the App-Menu: (Issue: #2461)
=> Symbolic for Ubuntu Software

icons/Suru/16x16/apps/htop.png, icons/Suru/16x16@2x/apps/htop.png, icons/Suru/24x24/apps/htop.png, icons/Suru/24x24@2x/apps/htop.png, icons/Suru/256x256/apps/htop.png, icons/Suru/256x256@2x/apps/htop.png, icons/Suru/32x32/apps/htop.png, icons/Suru/32x32@2x/apps/htop.png, icons/Suru/48x48/apps/htop.png, icons/Suru/48x48@2x/apps/htop.png, icons/Suru/scalable/apps/htop-symbolic.svg, icons/src/symlinks/fullcolor/apps.list, icons/src/symlinks/symbolic/apps.list
Supplemental pull request for https://github.com/ubuntu/yaru/issues/2517
/cc @Feichtmeier because he suggested symlink https://github.com/ubuntu/yaru/issues/2517#issuecomment-750221951 (and possibly cherry-pick to Focal?)
=> Add symbolic link for 'htop'

gtk/src/default/gtk-3.20/_tweaks.scss
=> GtkTheme: do not change tab fg color on hover

gnome-shell/src/gnome-shell-sass/_colors.scss, gnome-shell/src/gnome-shell-sass/widgets/_slider.scss
Independent of the decision which theme to default to (light or dark) this commit includes the following changes:
- for popups, notifications and dialogs the dark theme is now much darker, having a transparent border. The background however is *not* transparent, unlike in previous iterations, to prevent visual glitches
- border is also slightly darker than the OSD border
- the slider knob is adapted to the OSD chroma in gtk, the slider trough sharpness is improved by using a solid darkened white
- **_all these changes do not affect the light (currently default) theme_**
Edit: sorry missed this:
the rationale behind this is that the current very light "dark" colors are not blending so well over the gtk windows in my opinion. This dark/jet look features the current ubuntu style better, in …
=> ShellTheme: make the dark shell darker

gnome-shell/src/gnome-shell-sass/_drawing.scss, gnome-shell/src/gnome-shell-sass/widgets/_slider.scss, gnome-shell/src/toggle-off-dark.svg, gnome-shell/src/toggle-on-dark.svg
- dark shell slider border is now crisp
Before:
After:
- dark shell switch border is now crisp
- dark shell switch knob color is now white like the slider
Before:
After:
- dark shell insensitive button border is now dark and not descending from the light borders
Before:
After:
=> ShellTheme: dark shell sliders, switches and button improvements

gtk/src/default/gtk-3.20/_apps.scss, gtk/src/default/gtk-3.20/_colors.scss, gtk/src/default/gtk-3.20/_drawing.scss, gtk/src/default/gtk-3.20/_tweaks.scss, gtk/src/default/gtk-4.0/_colors.scss, gtk/src/default/gtk-4.0/_drawing.scss, gtk/src/default/gtk-4.0/_tweaks.scss
- base the whole gtk dark theme on $jet `#181818` instead of $inkstone `#3b3b3b`
- as a result everything is now a bit darker
- another result is that the dark gtk theme is now closer to the shell popups/dialogs/notifications
- the gtk theme however does not use half transparent borders to avoid glitches
- gtk4 is adapted to this change (should be the same result ideally)
WIP: up-to-date screenshots can be followed through in the conversation below
Everyone please have a look and share your feedback.
Closes #2227
=> Gtk theme: darker dark theme

gtk/src/default/gtk-3.20/_apps.scss, gtk/src/default/gtk-3.20/_tweaks.scss, gtk/src/default/gtk-4.0/_tweaks.scss
Due to the ubuntu orange being quiet bright
we change the sidebar selection from a full orange
row to a thin orange stripe plus a soft gray selection
This change does not affect treeview rows, only .nautilus-list-view treeview
Before:
After:
CC @madsrh @elioqoshi @waynecrosby
Closes #2666 
Closes #2408
=> GtkTheme: tone down selected rows

gtk/src/default/gtk-3.20/_apps.scss
I failed to round the brisk menu without a black surface behind leaking through.
This axes the border-radius for the brisk menu
=> Mate: do not round brisk menu

gnome-shell/src/gnome-shell-sass/_colors.scss, gtk/src/default/gtk-3.20/_tweaks.scss, gtk/src/default/gtk-4.0/_tweaks.scss
all dark themes: slightly brighten up the borders
shell theme: do not use a transparent border, as it becomes blurry on certain backgrounds
Before:
After:
CC @elioqoshi @madsrh
=> Shell and gtk themes: do not transparentize border

gtk/src/default/gtk-3.20/_tweaks.scss, gtk/src/default/gtk-4.0/_tweaks.scss
This aligns gtk dark themes menus and popovers to shell themes popup separators 
Before:
After:
CC @madsrh @elioqoshi
=> GtkTheme: align dark themes separators to shell

gtk/src/default/gtk-3.20/_apps.scss
- give cayas toolbar the correct backdrop bg color
- give iconview a soft gray hover
- axe the border beneath panel menus
=> Fixes for yaru mate

meson_options.txt
Fixes the `meson.build:11:9: ERROR: Tried to access unknown option "metacity".` build failure.
=> Fix build failure

gtk/src/default/gtk-3.20/_colors.scss, gtk/src/default/gtk-3.20/_headerbar.scss, gtk/src/default/gtk-4.0/_colors.scss, gtk/src/default/gtk-4.0/_headerbar.scss
- default theme: improved the headerbar switch slider border to not overlap too much
- default+light themes: lighten up the backdrop text color to have a similar color to backdrop fg color
Edit: also fixed a typo in gtk4 since there are no longer normal-alt and hover-alt types for the button mixin 
Closes #2227
=> GtkThemes: fixes for backdrop text and headerbar switches

gtk/src/default/gtk-3.20/_drawing.scss, gtk/src/default/gtk-4.0/_tweaks.scss
Continued from #2704
@Feichtmeier I see you changed the shadow of Gtk3 alt-buttons, as Gtk4 drop alt it is needed to add some more tweaks?
=> Gtk4: dark switch improvements

gtk/src/default/gtk-3.20/_apps.scss
This removes the roundness and highlight from headerbars that are not the last vertical top element of a window
Closes #2715
=> Fix for mate and unity windows

gnome-shell/src/gnome-shell-sass/widgets/_calendar.scss
in the dark shell theme the calendar separator is too bright, this tones it down a bit
Before:
After:
=> Dark shell theme: tone down calendar separator

gnome-shell/src/gnome-shell-sass/widgets/_slider.scss
=> Fix Gnome-shell blurry slider

gnome-shell/src/gnome-shell-sass/widgets/_login-dialog.scss
I am sure that the problem comes from this line:
https://github.com/ubuntu/yaru/blob/4f1d31c5d4de784e9671cadf1303a9ba14f9f0cd/gnome-shell/src/gnome-shell-sass/widgets/_login-dialog.scss#L46
But I can't be able to test this on my computer (can't update GDM theme). I tried the way described into `CONTRIBUTING.md` but that doesn't work.
Closes #2746
=> Fix Login Screen disabled button color

sessions/THEMENAME-xorg.desktop.in, sessions/THEMENAME.desktop.in, sessions/meson.build
Hi,
Since wayland will be the default-session starting ubuntu-21.04, this PR renames and aligns the session names for both wayland and Xorg same as Ubuntu session. 
*Note: Screenshot taken in vm of hirsute-daily builds*
=> rename sessions according to ubuntu 21.04 sessions

.github/workflows/open-pr-on-icons-changes.yaml
This PR add a way to check upstream Adwaita icons changes. It list all given icons into a `.list` file, so we can easily see new files.
Closes #1544
=> Check upstream icons changes

icons/src/cursors/render-cursors.py
With inkscape 1.0 something changed in the way inkscape runs in background, and it seems than pre-running the script, creating a inkscape thread pool, communicating later the command to execute is not working properly.
As "Dirty Fix"® this commit replaces the inkscape thread pool with a direct call to inkscape with the full command for each rendering.
**Very likely this is slower, a lot**, but it should allow users to continue working with our cursors during a deeper refactory of this script.
=> Update render-cursors script for inkscape 1.0

gtk/src/default/gtk-3.20/libhandy/_Adwaita-base.scss, gtk/src/default/gtk-3.20/libhandy/_fallback-base.scss
Sync our libhandy theme with upstream master branch.
The most important change add the "**Tab View**" support:
**Before:**
**After:**
**Question:** It still needs to remove all ugly shadows. But do we want to mimic normal Gtk tabs look (I mean the orange bottom border)?
=> Sync libhandy with upstream

icons/Suru/scalable/actions/brisk_system-log-out-symbolic.svg, icons/src/symlinks/symbolic/actions.list
The icon is named brisk_system-log-out-symbolic (see: https://github.com/getsolus/brisk-menu/blob/master/data/brisk_system-log-out-symbolic.svg).
Closes #2762
=> Symlink mate logout symbolic icon

gnome-shell/src/gnome-shell-sass/widgets/_app-grid.scss
Here is a "backport" of the fix I did for GS40 (https://github.com/ubuntu/yaru/pull/2736/commits/bce61903168e28f4bc89c8642f2c8f1525b6422f).
Closes #2801
=> Fix app grid folder border-radius

gtk/src/dark/gtk-2.0/assets.svg
I fixed some wrong lines in assets.svg for dark gtk2 variant. This issue causes the scale-slider.png not being rendered.
=> fixed assets.svg in gtk2 dark

gtk/src/dark/gtk-2.0/render-all-assets.sh, gtk/src/default/gtk-2.0/assets.svg, gtk/src/default/gtk-2.0/render-all-assets.sh, gtk/src/light/gtk-2.0/assets.svg, gtk/src/light/gtk-2.0/render-all-assets.sh
@Jannomag I found a solution for Inkscape 1.0:
- modify all **assets.svg** files: replace `inkscape:pageopacity="1"` with `inkscape:pageopacity="0"`
- edit all scripts: drop `--export-background-opacity=0` and also replace `--export-png=$ASSETS_DIR/$i.png` by `-o $ASSETS_DIR/$i.png`
That's it :)
Closes #2815
=> Update Gtk2 assets render scripts

meson_options.txt
Because it looks like the gresource meson option cause some problems with Gnome Shell, this PR disable that option.
Revert #2825
=> Disable gresource meson option

icons/Suru/index.theme
Here on Arch Linux I'm seeing the below issue where window controls on GTK apps with client-side decorations render the incorrect icon when using the Yaru icon theme.
This appears to be due to the icons used on the controls recently moving in #2806. They  used to be here:
```
usr/share/icons/Yaru/scalable/actions/window-close-symbolic.svg
usr/share/icons/Yaru/scalable/actions/window-maximize-symbolic.svg
usr/share/icons/Yaru/scalable/actions/window-minimize-symbolic.svg
usr/share/icons/Yaru/scalable/actions/window-new-symbolic.svg
usr/share/icons/Yaru/scalable/actions/window-restore-symbolic.svg
usr/share/icons/Yaru/scalable/actions/window-symbolic.svg
```
and now they are here:
```
usr/share/icons/Yaru/scalable/actions/window-symbolic.svg …
```
=> Add scalable/ui folder to index.theme

icons/Suru/scalable/apps/snap-symbolic.svg, icons/Suru/scalable/mimetypes/application-vnd.snap-symbolic.svg, icons/src/scalable/apps/snap-symbolic.svg, icons/src/scalable/mimetypes/application-vnd.snap-symbolic.svg
Fixes https://github.com/ubuntu/yaru/issues/2403.
I based the icon name on the name of [the corresponding fullcolor icon](https://github.com/ubuntu/yaru/blob/master/icons/src/fullcolor/mimetypes/application-vnd.snap.svg).
The primary change I made when scaling down the full-size icon was thickening the negative-space lines and aligning them to the pixel grid so that the icon will look sharper when rendered on screen. There are a number of side-by-side previews in the linked Issue.
Please let me know if there's anything else I need to do for the pull request. (I'm new here.) Thanks!
=> Add symbolic Snap app and mimetype icons

gtk/src/default/gtk-3.20/_common.scss, gtk/src/default/gtk-3.20/_tweaks.scss
I'll do the patch for GTK4 inside the Libadwaita PR to avoid merging clash.
Closes #2847
=> Fix row:selected buttons

gtk/src/default/gtk-3.20/_tweaks.scss, gtk/src/default/gtk-4.0/_tweaks.scss
I just used `background` instead of `background-image`.
Closes #2858
=> Fix list rows orange flash when unselected

gtk/src/default/gtk-3.20/apps/_firefox.scss
- it is no longer needed and this could cause issues once the fire next-UI-menus are in (forgot how that UI overhaul is named, but on windows firefox nightly the new menus are already in and they are big and round)
=> Gtk3 theme: remove firefox border axing

gnome-shell/src/gnome-shell-sass/widgets/_login-dialog.scss
- Remove entry style overwrite on dark theme (was really too dark). Now it use the same background and border color as dash, search entry, popover, ...
- GDM buttons didn't respect theme variant. Now it use `$base_color` so this problem is solved.
- I also changed the fg color for buttons as they now use  `$base_color`.
Closes #2870
=> Make GDM widgets compliant with GS theme variant

gtk/src/default/gtk-4.0/_drawing.scss
I just noticed that the `button` mixin was missing some little things:
- Add a missing 'Yaru change' comment
- Stronger shadows for flatter buttons (just like the Gtk3 part): it removes the shadow blur.
=> Fix gtk4 button mixin

gtk/src/default/gtk-4.0/widgets/_scale.scss, gtk/src/default/gtk-4.0/widgets/_switch.scss
Sync Gtk4 with upstream.
**Major changes:**
- Remove leftover scale slider shadows (https://gitlab.gnome.org/GNOME/libadwaita/-/commit/72c24397feaa40b5f4836214f5a0a1bf2b00da35)
- Add an offset for switch focus ring (https://gitlab.gnome.org/GNOME/libadwaita/-/commit/015892d88dcff10435a9a8152c9327705b81f042).
=> Sync Gtk4 with upstream

gtk/src/default/gtk-3.20/_colors.scss, gtk/src/default/gtk-3.20/_tweaks.scss, gtk/src/default/gtk-4.0/_colors.scss, gtk/src/default/gtk-4.0/_tweaks.scss
- revert to "upstream" monochrome spinners
- get rid of blue links, as the last part of blue in the theme which is now jarringly out of place
=> GtkTheme: monochrome spinners and orange links

CONTRIBUTING.md
After days and days of trying and searching, I found all dependencies of Gtk4 and Libadwaita 😅
So I updated `CONTRIBUTING.md` with these new information.
@Feichtmeier That could be great if you can try this.
Gtk4 dev deps:
```console
sudo apt install sassc clang libglib2.0-dev libcairo2-dev libpango1.0-dev libgdk-pixbuf-2.0-dev libepoxy-dev libxkbcommon-dev libgraphene-1.0-dev cmake libwayland-dev libxrandr-dev libxi-dev
```
Libadwaita dev deps:
```console
sudo apt install sassc valac libglib2.0-dev
```
Both use the same **meson/ninja** command to compile:
```console
meson --prefix=/usr --sysconfdir=/etc --localstatedir=/var --libdir=lib/x86_64-linux-gnu _build .
cd _build
ninja
sudo ninja install
```
=> Add Gtk4 and Libadwaita install infos

gnome-shell/src/data/gnome-shell-theme.gresource.xml
The upstream shell theme has a placeholder when dragging a window in-between two workspace previews. This is not the case on Yaru. This tiny change properly renders the workspace preview on Yaru shell.
=> Use correct placeholder for workspace previews

gtk/src/default/gtk-4.0/_tweaks.scss
Remove transition for check/radio inside popover menus to fix wiggling effect.
Closes #2903
=> Fix menus checks wiggling effect

icons/Suru/16x16/legacy/dialog-selectors.svg, icons/Suru/16x16/legacy/snap-bounding-box-center.svg, icons/Suru/16x16/legacy/snap-bounding-box-corners.svg, icons/Suru/16x16/legacy/snap-bounding-box-edges.svg, icons/Suru/16x16/legacy/snap-bounding-box-midpoints.svg, icons/Suru/16x16/legacy/snap-bounding-box.svg, icons/Suru/16x16/legacy/snap-grid-guide-intersections.svg, icons/Suru/16x16/legacy/snap-nodes-center.svg, icons/Suru/16x16/legacy/snap-nodes-cusp.svg, icons/Suru/16x16/legacy/snap-nodes-intersection.svg, icons/Suru/16x16/legacy/snap-nodes-midpoint.svg, icons/Suru/16x16/legacy/snap-nodes-path.svg, icons/Suru/16x16/legacy/snap-nodes-rotation-center.svg, icons/Suru/16x16/legacy/snap-nodes-smooth.svg, icons/Suru/16x16/legacy/snap-nodes.svg, icons/Suru/16x16/legacy/snap-others.svg, icons/Suru/16x16/legacy/snap.svg, icons/Suru/16x16/legacy/zoom-center-page.svg
Closes #2895 
And while I'm doing missing icons, I added one for the selectors dialog:
=> Missing snapping icons for inkscape

gnome-shell/src/gnome-shell-sass/_colors.scss, gnome-shell/src/gnome-shell-sass/_dock.scss, gnome-shell/src/gnome-shell-sass/widgets/_panel.scss
- Make panel background static into the overview ;
- Use a 2% darken `jet` as panel background ;
- Define dock background as transparent (will render half dark transparent, we need to understand why).
=> Fix dock and panel look

gnome-shell/src/gnome-shell-sass/_colors.scss
Caused by #2948
I didn't noticed that the dash (not the dock) background was based on top panel background var. Into #2948, I've darkened the panel bg. As many components (search entry, search results, app folder, ...) are based on dash bg, it result a too much darker look everywhere.
So this PR revert `$dash_background_color` to old `$panel_bg_color` value: `lighten($jet, 2%)`.
=> Revert to lighten dash background

icons/Suru/scalable/actions/sidebar-show-right-rtl-symbolic.svg, icons/Suru/scalable/actions/sidebar-show-rtl-symbolic.svg, icons/src/symlinks/symbolic/actions.list
Add symlinked rtl variants for `show-sidebar` symbolic icons.
See: https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/commit/33ebc3988db722775830ff7676b7798e4830ade2
=> Add symlinked rtl variants for show-sidebar

gtk/src/default/gtk-3.20/_common.scss, gtk/src/default/gtk-3.20/_tweaks.scss
Improve selected row look:
- Remove the little orange left stripe (except on Nautilus sidebar) ;
- Increase bg contrast.
Closes #2954
=> Improve selected row look

gnome-shell/src/gnome-shell-sass/widgets/_search-entry.scss
Due to fixed panel opacity, the search entry looks too close from it.
**Before:**
**After:**
=> Fix search entry margin-top

icons/src/scalable/render-symbolic-icons.sh
This PR updates [`render-symbolic-icons.sh`](https://github.com/ubuntu/yaru/blob/master/icons/src/scalable/render-symbolic-icons.sh) script to add the  _**emotes, legacy**_ and _**ui**_  as contexts
=> update contexts in symbolic-script to add more contexts

icons/Suru/scalable/apps/org.gnome.Settings-multitasking-symbolic.svg, icons/src/scalable/apps/org.gnome.Settings-multitasking-symbolic.svg, icons/src/symlinks/symbolic/apps.list
Multitasking-panel has been introduced into Settings (see: [!729](https://gitlab.gnome.org/GNOME/gnome-control-center/-/merge_requests/729) ) and requires the symbolic with name: `org.gnome.Settings-multitasking-symbolic.svg` this PR symlinks it to `session-properties-symbolic`
Thanks!
=> symlink for multitasking-panel

gtk/src/default/gtk-3.20/_tweaks.scss
The problem come from these lines: https://gitlab.gnome.org/GNOME/gnome-software/-/blob/main/src/gtk-style.css#L812-814
As they use exported color for background, it is impossible to overwrite it. So I used transparent background:
Hover state:
Closes #2980
@LinuxLlama @Muqtxdir Can you tell me if it works for you?
=> Fix G-software unvisible close button

.github/workflows/open-pr-on-changes.yaml
**Gnome shell** and **Gtk** moved from `master` to `main` branch name.
=> Fix branch names

gtk/src/default/gtk-4.0/_colors-yaru.scss
They did so much change that I can't tell if we want all of them.
Fortunately, thanks to the symlink system, I didn't have to do anything but delete unnecessary variables in our overwrite color file.
=> Sync GTK4 with upstream (remove old color vars)

gnome-shell/src/gnome-shell-sass/widgets/_login-dialog.scss
I added border on GDM/lock screen buttons, and updated background colors.
In bonus, I added a focus ring on focused buttons (using `tab`).
@Feichtmeier can you post a screenshot for me here, I don't have a VM within easy reach. Also tell me if you don't like the focus ring :)
Closes #3012
=> Add border and focus ring on GDM buttons

gtk/src/default/gtk-3.20/_tweaks.scss
=> Fix backdrop insensitive selected text color

gtk/src/default/gtk-3.20/_tweaks.scss
Use `:disabled` instead of deprecated :insensitive pseudo-class.
Closes #3028
=> Fix deprecated :insensitive pseudo-class

icons/Suru/scalable/actions/eog-image-gallery-symbolic.svg, icons/src/symlinks/symbolic/actions.list
**eog-image-gallery-symbolic:**
Related to #3033 #3064
=> Add missing eog symbolic icon

gtk/src/default/gtk-3.20/_apps.scss
As gnome-terminal (3.36) doesn't support transparent notebook background, I just re-overwritten it to use `$bg_color`.
So it isn't transparent, but it looks just like if it was. To avoid any cascading effect I only targeted `gnome-terminal`
Closes #2481
@Feichtmeier This PR will be merged to `ubuntu/focal` but I have no idea of how make a patch to yaru deb package. Can you help me?
=> Fix gnome terminal notebook header bg

.github/workflows/open-pr-on-icons-changes.yaml
**Evince** repository branch name is renamed to `main`.
=> Fix evince branch name

icons/Yaru/scalable/actions/selection-mode-symbolic.svg, icons/src/scalable/actions/selection-mode-symbolic.svg
Added new `selection-mode-symbolic` icon:
See: #3155 and https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/blob/master/Adwaita/scalable/actions/selection-mode-symbolic.svg
=> Add selection-mode-symbolic icon

.github/workflows/open-pr-on-icons-changes.yaml
I noticed we have a problem with the current listing command `find . -name "*-symbolic.svg"`, because it sometimes randomly change the listing sort, and so create a lot of spamming and useless PRs.
So I added a piped `sort` instruction to stabilize the output.
@clobrano do you think this will solve the problem?
=> Sort symbolic action listing

gtk/src/default/gtk-4.0/_tweaks.scss
Use exported accent color for the red close button instead of hardcoded orange color var.
This allows to not have to modify the `_tweaks` hardcoded value for the `mate` branch.
=> Use exported accent for red close button

icons/Yaru/16x16/apps/config-users.png, icons/Yaru/16x16@2x/apps/config-users.png, icons/Yaru/24x24/apps/config-users.png, icons/Yaru/24x24@2x/apps/config-users.png, icons/Yaru/256x256/apps/config-users.png, icons/Yaru/256x256@2x/apps/config-users.png, icons/Yaru/32x32/apps/config-users.png, icons/Yaru/32x32@2x/apps/config-users.png, icons/Yaru/48x48/apps/config-users.png, icons/Yaru/48x48@2x/apps/config-users.png
The fullcolor `config-users` icon is duplicated with a broken symlink and it makes the installation fails.
=> Fix broken duplicated config-users icon symlink

gtk/src/default/gtk-3.20/_apps.scss, gtk/src/default/gtk-3.20/apps/_guake.scss
This will need a backport to `21.10`, `20.04`.
Closes #2149
=> Fix transparent guake notebook headerbar

gnome-shell/src/gnome-shell-high-contrast.scss
=> Add dock styles to GS hc variant

gnome-shell/src/data/gnome-shell-theme.gresource.xml, gnome-shell/src/gnome-shell-start.svg
This PR adds `gnome-shell-start.svg` as it used if `gnome-tour` app is present/installed during initial-setup.
_NOTE: `gnome-tour` is not shipped with **ubuntu-desktop**, this will benefit for people who use Yaru on other distributions_
https://user-images.githubusercontent.com/54065734/141304662-9f85ab16-17d3-47ae-a4fd-b9cc4159f8eb.mp4
=> add gnome-shell-start

gnome-shell/src/gnome-shell-sass/widgets/_window-picker.scss
- smaller border-radius
- add border
=> Rework .window-caption

.github/workflows/build-ci.yaml
As some meson options are `false`, the build CI doesn't test every part of the repository.
So I forced here all `false` options to `true`.
=> Force meson options to true in build CI

icons/meson.build
The previous way of installing `index.theme` files was very problematic because the `configure_file` meson function is storing temp files in the same in the same temp folder. As they was using the same name, the last one was overwriting the previous one.
So I had the `index.theme` file of the **mate** flavour in both `/usr/share/icons/Yaru` and `/usr/share/icons/Yaru-mate` folders, with very weird side effects.
This PR solve the problem by prefix the file name, and then by rename it at the installation step.
=> Fix index.theme flavour overwriting

gtk/src/default/gtk-3.0/_tweaks.scss
Revert `treeview:selected` rows to upstream look.
Closes #3245
=> Drop treeview grey selected row tweak

gtk/src/default/gtk-3.0/apps/_nautilus.scss
=> Nautilus: keep gray rows until gtk4 port

icons/Yaru/16x16/categories/preferences-desktop-keyboard.png, icons/Yaru/16x16@2x/categories/preferences-desktop-keyboard.png, icons/Yaru/24x24/categories/preferences-desktop-keyboard.png, icons/Yaru/24x24@2x/categories/preferences-desktop-keyboard.png, icons/Yaru/256x256/categories/preferences-desktop-keyboard.png, icons/Yaru/256x256@2x/categories/preferences-desktop-keyboard.png, icons/Yaru/32x32/categories/preferences-desktop-keyboard.png, icons/Yaru/32x32@2x/categories/preferences-desktop-keyboard.png, icons/Yaru/48x48/categories/preferences-desktop-keyboard.png, icons/Yaru/48x48@2x/categories/preferences-desktop-keyboard.png, icons/src/symlinks/fullcolor/categories.list
Symlink **preferences-desktop-keyboard** to **input-keyboard**.
Closes #3284
=> Add preferences-desktop-keyboard icon

debian/yaru-theme-icon.install
was added when `mate` variants were merged into `master`
=> add 22x22/categories to yaru-theme-icon.install

sessions/THEMENAME.gschema.override.in, sessions/mode.json.in
- sync `enabledExtensions` offered in session with ubuntu-sessions's `enabledExtensions`
- sync `button-layout` offered in session with ubuntu-sessions's `button-layout`  (_will be helpful to testers who are  on different distribution ex: Fedora, Pop! OS_)
- add gedit preferences scheme for overriding to `@ThemeName@`
=> update session overrides

gnome-shell/src/gnome-shell-sass/widgets/_screen-shield.scss
Revert GDM background to upstream (`$system_bg_color` - same as overview) to avoid jarring transition **purple** -> **grey**.
This is just for testing and get opinions, because I can't take screenshot.
Closes #2908
=> Drop GDM purple background

metacity/src/mate-dark/metacity-theme-1.xml.in, metacity/src/mate/metacity-theme-1.xml.in
The **mate** metacity variants wasn't working because:
- There was an extra quote in **mate** variant ;
- ... and also because I inverted **mate** and **mate-dark** 😅
=> Fix metacity mate variant

icons/Yaru/scalable/devices/ups-symbolic.svg, icons/src/symlinks/symbolic/devices.list
Symlink **ups-symbolic** to **uninterruptible-power-supply-symbolic**.
Related to #3298 (all other icons was already here)
=> Symlink ups to uninterruptible-power-supply (symbolic)

gnome-shell/src/gnome-shell-sass/_colors.scss, gnome-shell/src/gnome-shell-sass/_common.scss, gnome-shell/src/gnome-shell-sass/_drawing.scss, gnome-shell/src/gnome-shell-sass/_high-contrast-colors.scss, gnome-shell/src/gnome-shell-sass/widgets/_app-grid.scss, gnome-shell/src/gnome-shell-sass/widgets/_calendar.scss, gnome-shell/src/gnome-shell-sass/widgets/_dash.scss, gnome-shell/src/gnome-shell-sass/widgets/_dialogs.scss, gnome-shell/src/gnome-shell-sass/widgets/_keyboard.scss, gnome-shell/src/gnome-shell-sass/widgets/_looking-glass.scss, gnome-shell/src/gnome-shell-sass/widgets/_message-list.scss, gnome-shell/src/gnome-shell-sass/widgets/_network-dialog.scss, gnome-shell/src/gnome-shell-sass/widgets/_notifications.scss, gnome-shell/src/gnome-shell-sass/widgets/_panel.scss, gnome-shell/src/gnome-shell-sass/widgets/_popovers.scss, gnome-shell/src/gnome-shell-sass/widgets/_search-entry.scss, gnome-shell/src/gnome-shell-sass/widgets/_search-results.scss, gnome-shell/src/gnome-shell-sass/widgets/_slider.scss, gnome-shell/src/gnome-shell-sass/widgets/_switcher-popup.scss, gnome-shell/src/gnome-shell-sass/widgets/_switches.scss, gnome-shell/src/gnome-shell-sass/widgets/_workspace-switcher.scss
Add support for **Gnome Shell 42** _- still compatible with 40_.
Please test this and report your comments here.
The most noticeable change is an _huge increase_ of padding...
Related to #3311
=> Add support for GS42 - upstream sync

gnome-shell/src/gnome-shell-sass/widgets/_window-picker.scss
As we dropped the orange close button in Gtk, I think we should also revert our change of orange close for Gnome Shell, so it looks consistent.
What do you think of?
=> Revert close button to upstream look

icons/Yaru/scalable/emblems/padlock-open-symbolic.svg, icons/src/scalable/emblems/padlock-open-symbolic.svg
Fix `padlock-open-symbolic` icon, which was using Adwaita look.
**Before:**
**After:**
=> Fix padlock-open-symbolic icon

.github/workflows/open-pr-on-icons-changes.yaml
Fix GH actions branches.
Libhandy now use `main` as default master branch.
=> Fix GH actions branches

gtk/src/mate-dark/gtk-4.0/gtk-dark.scss, gtk/src/mate-dark/gtk-4.0/gtk.scss
Fix mate-dark gtk4 variant (was using light version of `gtk.scss`).
=> Fix mate-dark gtk4 variant

gtk/src/default/gtk-3.0/_common.scss
Sync Gtk3 with upstream.
I noticed we wasn't perfectly synced in the Window Manager part of `_common`, so I fixed that.
Related to #3375
=> Sync Gtk3 with upstream

gtk/src/default/gtk-3.0/_common.scss
Sync Gtk3 light headerbar bg with Gtk4 (use `#ebebeb`).
**Before:**
**After:**
=> Sync Gtk3 light headerbar bg with Gtk4

gnome-shell/src/gnome-shell-sass/_common.scss, gtk/src/default/gtk-3.0/_common.scss, gtk/src/default/gtk-3.0/libhandy/_Adwaita-base.scss
Sync Gtk3, Libhandy and Gnome Shell border-radius with Gtk4 one: `6px`.
=> Sync Gtk3 + Libhandy + GS with Gtk4 radii

gnome-shell/src/meson.build, meson.build
Fix those meson warning messages:
```
WARNING: Project specifies a minimum meson_version '>= 0.51' but uses features which were added in newer versions:
* 0.53.0: {'Fs Module'}
NOTICE: Future-deprecated features used:
* 0.56.0: {'meson.source_root'}
```
**Changes:**
- Bump required meson version to `>= 0.53`;
- remove deprecated `meson.source_root` usage.
=> Fix meson warning

gtk/src/default/gtk-3.0/_drawing.scss
Test PR for shadow less buttons.
Normal state buttons got no shadow, hover state uses previous normal shadow.
https://user-images.githubusercontent.com/36476595/154840783-8c43ef0c-2adb-4f9e-9d6a-d30d2b901d42.mp4
=> Remove shadow on normal buttons

gnome-shell/src/gnome-shell-sass/_dock.scss
Update dash-to-dock base CSS to respect latest upstream changes, fixing
the padding for edge icons.
Moved the logic to handle most of style such as color and transparency
of the dock here, as it's something we'd prefer not to change through
settings overrides.
Fixes #3111
Fixes #3327
LP: #1942702
---
There's some results, this requires also some dash-to-dock changes in order not to define colors via settings overrides anymore.
I'm also wondering if we could do something like this when the applications are showing as IMHO the show-apps button is easy to confuse with applications when it's checked:
```diff
diff --git a/gnome-shell/src/gnome-shell-sass/_dock.scss b/gnome-shell/src/gnome-shell-sass/_dock.scss
index 969d22d47..4975662b5 100644
--- a/gnome-shell/src/gnome-shell-sass/_dock.scss …
```
=> Dash to dock updates for GNOME 41 (and dash-to-dock 71+)

icons/Yaru-mate/16x16/apps/nautilus.png, icons/Yaru-mate/16x16/apps/org.gnome.Nautilus.png, icons/Yaru-mate/16x16/apps/system-file-manager.png, icons/Yaru-mate/16x16@2x/apps/nautilus.png, icons/Yaru-mate/16x16@2x/apps/org.gnome.Nautilus.png, icons/Yaru-mate/16x16@2x/apps/system-file-manager.png, icons/Yaru-mate/24x24/apps/nautilus.png, icons/Yaru-mate/24x24/apps/org.gnome.Nautilus.png, icons/Yaru-mate/24x24/apps/system-file-manager.png, icons/Yaru-mate/24x24@2x/apps/nautilus.png, icons/Yaru-mate/24x24@2x/apps/org.gnome.Nautilus.png, icons/Yaru-mate/24x24@2x/apps/system-file-manager.png, icons/Yaru-mate/256x256/apps/nautilus.png, icons/Yaru-mate/256x256/apps/org.gnome.Nautilus.png, icons/Yaru-mate/256x256/apps/system-file-manager.png, icons/Yaru-mate/256x256@2x/apps/nautilus.png, icons/Yaru-mate/256x256@2x/apps/org.gnome.Nautilus.png, icons/Yaru-mate/256x256@2x/apps/system-file-manager.png, icons/Yaru-mate/32x32/apps/nautilus.png, icons/Yaru-mate/32x32/apps/org.gnome.Nautilus.png, icons/Yaru-mate/32x32/apps/system-file-manager.png, icons/Yaru-mate/32x32@2x/apps/nautilus.png, icons/Yaru-mate/32x32@2x/apps/org.gnome.Nautilus.png, icons/Yaru-mate/32x32@2x/apps/system-file-manager.png, icons/Yaru-mate/48x48/apps/nautilus.png, icons/Yaru-mate/48x48/apps/org.gnome.Nautilus.png, icons/Yaru-mate/48x48/apps/system-file-manager.png, icons/Yaru-mate/48x48@2x/apps/nautilus.png, icons/Yaru-mate/48x48@2x/apps/org.gnome.Nautilus.png, icons/Yaru-mate/48x48@2x/apps/system-file-manager.png
Generate missing mate symlinks for `filemanager` fullcolor icon.
=> Generate missing mate symlinks

gnome-shell/src/gnome-shell-sass/_common.scss
**Before:**
**After:**
Related to #3407
=> Fix apps_label color in light theme

gnome-shell/src/gnome-shell-sass/_drawing.scss, gnome-shell/src/gnome-shell-sass/widgets/_keyboard.scss
Fix keyboard in light and dark theme.
**Before:**
**After:**
https://user-images.githubusercontent.com/36476595/156054455-4e85c13b-f121-452e-8867-161264a7fcc3.mp4
=> Fix keyboard in light and dark theme

gtksourceview/src/dark.xml.in, gtksourceview/src/default.xml.in
| ubuntu 21.10 | PR: |
| ----------------- | ------- |
| ![old-lighty](https://user-images.githubusercontent.com/54065734/156159412-f88a8c94-689a-4d3f-ac1a-454cf26111bd.png) | ![light](https://user-images.githubusercontent.com/54065734/156159454-ffc152ad-aaf7-461f-a330-6d5fbb720f31.png) |
| ![old-darky](https://user-images.githubusercontent.com/54065734/156159525-e475a5d7-5185-4450-9949-bb5028012c20.png) | ![dark](https://user-images.githubusercontent.com/54065734/156159575-71f469f5-4a8f-4fa1-8ef4-f48f8892fb1a.png) |
Closes: #3419
=> update default and dark gtksourceview styles

gtk/src/default/gtk-3.0/apps/_caja.scss
**Before:**
**After:**
CC @flexiondotorg 
Fix https://github.com/ubuntu-mate/ubuntu-mate-artwork/issues/83
=> Fix invisible caret in caja

gnome-shell/src/gnome-shell-sass/widgets/_window-picker.scss
Fix over bright hover close button.
**Before:**
**After:**
Before the sync with GS42, the default state was using 10% lighten of `$osd_bg_color` and hover 15% (so it's 5% lighter than normal state).
With the GS42 sync, there's a new var `$window_close_button_color` with the same value as normal state (10%). But the hover state is lighten this var to 15% again (so 25% which is really too bright).
So to fix that, I decreased the hover state lighten to 5%, so it looks like before.
=> Fix close button hover bg

gnome-shell/src/gnome-shell-sass/widgets/_popovers.scss
Fix popovers menu item states: it shouldn't lighten the bg on hover and active in light theme.
**Before:**
https://user-images.githubusercontent.com/36476595/156554388-420aa767-63cc-4b86-8380-2b355a7fbaed.mp4
**After:**
https://user-images.githubusercontent.com/36476595/156554404-ea578b2a-9153-4842-b26e-e2c7f0b5f505.mp4
Related to #3407
=> Fix popovers menu item states

gnome-shell/src/gnome-shell-sass/widgets/_search-entry.scss
Increase search entry margin bottom because the entry was too close from workspaces thumbnails.
**Before:**
**After:**
=> Fix search entry alignement

gnome-shell/src/gnome-shell-sass/widgets/_login-dialog.scss
As the lock screen entry is transparent and as we are using a box-shadow for focused entries, it result a very weird effect of ugly background.
**Before:**
**After:**
Related to #3407
=> Fix focused unlock-dialog entry

gnome-shell/src/gnome-shell-sass/widgets/_notifications.scss
Fix notification look: use `$bg_color` for better contrast with buttons.
**Before:**
**After:**
=> Fix notification look

icons/Yaru/scalable/emblems/explore2-symbolic.svg, icons/src/symlinks/symbolic/emblems.list
This icon is used here (Adwaita on the screenshot):
=> Add missing explore2 icon

gnome-shell/src/gnome-shell-sass/widgets/_dash.scss
Add border to dash-label and align app-running-dot like dock ones.
**Before:**
**After:**
=> Gs dash label border and app-dot realign

icons/Yaru/scalable/actions/go-last-symbolic-rtl.svg, icons/src/symlinks/symbolic/actions.list
Fix `go-last-symbolic-rtl` icon which was symlinked to the wrong icon. Now it point to the left.
Also clean duplicated go-last-* and go-first-* symlinks.
Closes #3506
=> Fix go-last-symbolic-rtl icon

gnome-shell/src/gnome-shell-sass/widgets/_search-entry.scss
Remove a  typo in `_search-entry` I committed by mistake in #3446.
=> Remove typo in _search-entry

gnome-shell/src/gnome-shell-sass/widgets/_login-dialog.scss
**Before:**
**After:**
Closes #3491
=> Fix lock screen in light theme

common/accent-colors.scss.in
Adjusts the hue of the accent colour named magenta to better match the actual magenta colour. (https://en.wikipedia.org/wiki/Magenta)
N.B.: The saturation and brightness are still toned down to a) meet contrast ratio requirements and b) avoid looking garish, especially on dark backgrounds.
Addresses a comment by @Muqtxdir made on this pr https://github.com/ubuntu/yaru/pull/3496#issuecomment-1073048482
=> Adjust hue of magenta so it corresponds better to the name magenta

gtk/src/index.theme.in, gtk/src/meson.build
Adding `MetacityThemeName` to `index.theme` makes all the Yaru theme variants compatible with MATE Appearance Properties
=> gtk: Add MetacityThemeName to index.theme

metacity/src/dark/metacity-theme-1.xml.in, metacity/src/default/metacity-theme-1.xml.in
This pull request corrects `metacity-theme-1.xml.in` for the `default` and `dark` themes so Metacity matches GNOME/CSD windows. Essentially this is just copying the constants over from the `mate` and `mate-dark` themes.
=> metacity: Correct titlebar contrast for default and dark themes

.github/workflows/open-pr-on-icons-changes.yaml
Renames some branch to `main`.
=> Fix upstream icons CI branch names

gtk/src/default/gtk-3.0/apps/_mate.scss
**Before:**
**After:**
Closes #2760
CC @flexiondotorg
=> Mate: Hide focus outline on menu-bar buttons

gnome-shell/src/gnome-shell-sass/_colors.scss
Use a darker `$bg_color_dark` value and a lighten border.
**Before - `lighten($jet, 6%)`:**
**After - `lighten($jet, 2%)` + lighten border:**
This will affect all the popovers, but as we have the same issue with the overview which use the same bg as login screen, this is imo not a problem.
Closes #3490
=> Increase contrast of popover menus

icons/Yaru/16x16/actions/printer.png, icons/Yaru/16x16/actions/printers.png, icons/Yaru/16x16@2x/actions/printer.png, icons/Yaru/16x16@2x/actions/printers.png, icons/Yaru/22x22/actions/printer.png, icons/Yaru/22x22/actions/printers.png, icons/Yaru/24x24/actions/printer.png, icons/Yaru/24x24/actions/printers.png, icons/Yaru/24x24@2x/actions/printer.png, icons/Yaru/24x24@2x/actions/printers.png, icons/Yaru/256x256/actions/printer.png, icons/Yaru/256x256/actions/printers.png, icons/Yaru/256x256@2x/actions/printer.png, icons/Yaru/256x256@2x/actions/printers.png, icons/Yaru/32x32/actions/printer.png, icons/Yaru/32x32/actions/printers.png, icons/Yaru/32x32@2x/actions/printer.png, icons/Yaru/32x32@2x/actions/printers.png, icons/Yaru/48x48/actions/printer.png, icons/Yaru/48x48/actions/printers.png, icons/Yaru/48x48@2x/actions/printer.png, icons/Yaru/48x48@2x/actions/printers.png, icons/src/symlinks/fullcolor/actions.list
The pull request adds symlinks for fullcolour `printer` and `printers` icons used by `system-config-printer`. 
`system-config-printer.desktop` is hidden from GNOME and KDE so this fix is for other desktop environments, such as MATE.
=> icons: Add symlinks for fullcolor printer and printers icons

gtk/src/default/gtk-3.0/_tweaks.scss
Fix for selected image.
By default this use white, but as we use lighter `bg_color` we need a darker selected background on light theme and a lighter one on dark theme.
Closes #2813
=> Gtk3: Fix selected image

icons/meson.build, icons/src/fullcolor/accented/actions/edit-select-all.svg, icons/src/fullcolor/accented/actions/folder-new.svg, icons/src/fullcolor/accented/actions/go-first.svg, icons/src/fullcolor/accented/actions/go-last.svg, icons/src/fullcolor/accented/actions/mail-reply-all.svg, icons/src/fullcolor/accented/categories/preferences-desktop-wallpaper.svg, icons/src/fullcolor/accented/devices/audio-speaker-center-back-testing.svg, icons/src/fullcolor/accented/devices/audio-speaker-center-testing.svg, icons/src/fullcolor/accented/devices/audio-speaker-left-back-testing.svg, icons/src/fullcolor/accented/devices/audio-speaker-left-side-testing.svg, icons/src/fullcolor/accented/devices/audio-speaker-left-testing.svg, icons/src/fullcolor/accented/devices/audio-speaker-mono-testing.svg, icons/src/fullcolor/accented/devices/audio-speaker-right-back-testing.svg, icons/src/fullcolor/accented/devices/audio-speaker-right-side-testing.svg, icons/src/fullcolor/accented/devices/audio-speaker-right-testing.svg, icons/src/fullcolor/accented/devices/audio-subwoofer-testing.svg
Make possible to add accent to more icons, we were not including them.
I've simply replaced the color with the accent "magic", but more tuning could be done. But I think they look good enough this way.
I simply didn't find the right shades to apply so far, but I feel that using a scss transformation to get some better colors could be still used (as per `common/yaru-colors-defs.scss`).
=> icons: Add more accented icons

gnome-shell/src/gnome-shell-sass/_drawing.scss
Just use inset box-shadow instead of previous outset one.
**Before:**
**After:**
Closes  #3583
=> GS: fix entries border radius

gtk/src/default/gtk-3.0/_colors.scss, gtk/src/default/gtk-4.0/_defaults.scss
**Note:** `$dark_4` = `$jet` in Gtk4 colors.
=> Sync Gtk popover/menu bg with GS

metacity/src/default/metacity-theme-1.xml.in
This pull request defines the base window button dimensions and is used to determine whether the image needs to be re-scaled when rendering on different DPI densities. See https://pad.lv/1967507 Tested on regular DPI displays and Thinkpad P1 with 3840x2160 HiDPI using Intel iGP and NVIDIA dGPU. Close #3602
It also adds window buttons to dialog windows ensuring they will always have a close window button.
=> metacity: Define the base button dimensions and ensure dialog windows have a close button. Close #3602

gtk/src/default/gtk-3.0/_tweaks.scss
**Before:**
**After:**
Closes #3588
=> Gtk: remove windowcontrols button background on backdrop

icons/Yaru/scalable/actions/adw-entry-apply-symbolic.svg, icons/src/symlinks/symbolic/actions.list
Symlink new `adw-entry-apply-symbolic` with `object-select-symbolic`.
Related to #3614
=> Sync with Libadwaita symbolics 3614

.github/workflows/open-pr-on-icons-changes.yaml
Change upstream branch from `master` to `main` for **gnome-calendar** and **gnome-control-center**.
=> Fix some upstream branches (master → main)

icons/Yaru/scalable/actions/adw-mail-send-symbolic.svg, icons/Yaru/scalable/emblems/adw-external-link-symbolic.svg, icons/src/symlinks/symbolic/actions.list, icons/src/symlinks/symbolic/emblems.list
Symlink:
- **document-send-symbolic** to **adw-mail-send-symbolic**
- **external-link-symbolic** to **adw-external-link-symbolic**
Related to #3657
=> Sync symbolic icons with upstream 3657

gnome-shell/src/data/icons/scalable/actions/dark-mode-symbolic.svg
**New icon:**
Related to #3665
=> Sync GS with upstream - 3665

metacity/src/dark/metacity-theme-1.xml.in
I'm setup a MATE VM to test this, but I'm 100% sure it will solve the problem.
Closes #3675
=> Metacity: add missing dialog window controls in dark theme

.gitattributes
The Debian package excludes this folder but I think it makes sense to do it here instead (so that tarball releases don't have this folder).
=> gitattributes: Exclude .github from tarball releases

gnome-shell/src/data/gnome-shell-icons.gresource.xml
=> Add missing dark-mode-symbolic entry to gnome-shell-icons.gresource.xml

gnome-shell/src/gnome-shell-sass/widgets/_app-grid.scss
**Before:**
**After:**
Fixes #3714
=> App grid arrow use wrong color

gnome-shell/src/gnome-shell-sass/widgets/_quick-settings.scss
**Before**
**After:**
Fixes #3706
=> Wrong quick action button color on click

common/sass-utils.scss, common/test-sass-utils.scss, gtk/src/default/gtk-3.0/_colors.scss, gtk/src/default/gtk-4.0/_colors.scss, gtk/src/meson.build
Compute accent-color value (the one used by links, so far) to have a
contrast value to be optimized according to W3C requirements.
See: https://twitter.com/alexm_gnome/status/1526531918166212608
=> gtk: Optimize accent color definition taking background in account

gnome-shell/src/gnome-shell-sass/_dock.scss
This includes fixes coming from:
- https://github.com/micheleg/dash-to-dock/pull/1826
- https://github.com/micheleg/dash-to-dock/pull/1827
And more importantly:
- Increase apps tooltips margins
- Set margin for default app-running dots
- Remove upstream defined dash-item-container's children margin
- Do not add edge padding to edge elements
- Fix definition for dash-separator in shrink mode
- Take in account side margin and opposite padding in separators
- Explicitly use border radius and spacing from upstream
- Simplify dash separator definition based on upstream one
- Use unique function to handle padding/margin on internal children
- avoid computing the shrunk dash padding multiple times
- Use generic style generator for shrink mode too
- Move mixins to the top of the file for easier …
=> dock: Sync theme with upstream

icons/Yaru/scalable/devices/computer-chip-symbolic.svg, icons/src/symlinks/symbolic/devices.list
[Upstream icon](https://github.com/GNOME/gnome-software/blob/main/data/icons/computer-chip-symbolic.svg)
Related to #3826
=> Sync icon theme with upstream

icons/Yaru/16x16/apps/timeshift.png, icons/Yaru/16x16@2x/apps/timeshift.png, icons/Yaru/24x24/apps/timeshift.png, icons/Yaru/24x24@2x/apps/timeshift.png, icons/Yaru/256x256/apps/timeshift.png, icons/Yaru/256x256@2x/apps/timeshift.png, icons/Yaru/32x32/apps/timeshift.png, icons/Yaru/32x32@2x/apps/timeshift.png, icons/Yaru/48x48/apps/timeshift.png, icons/Yaru/48x48@2x/apps/timeshift.png, icons/Yaru/scalable/apps/timeshift-symbolic.svg, icons/src/symlinks/fullcolor/apps.list, icons/src/symlinks/symbolic/apps.list
@Muqtxdir Timeshift isn't a pre-installed app, and I agree with the linked issue comment that it can be confusing with Déjà-dup, WDYT?
Fixes #3816
Revert #3477
=> Timeshift icons overridden with backups icon

gtk/src/default/gtk-3.0/_colors.scss, gtk/src/default/gtk-4.0/_colors.scss
It is consistent with what we did in yaru.dart.
**Note:** `$suggested_bg_color` var is only used for suggested button
Closes #3610
=> Suggested button green only in default variant

gnome-shell/src/gnome-shell-sass/_dock.scss
The dash separator was white in the light theme.
This PR use the dark variant of the border colour.
| Before | After 
| --- | ---
| ![Capture d’écran du 2023-03-17 12-35-58](https://user-images.githubusercontent.com/36476595/225894008-ad96ff2a-3ed8-4699-a014-a264a91add55.png) | ![Capture d’écran du 2023-03-17 12-34-51](https://user-images.githubusercontent.com/36476595/225894015-3519391d-08c2-4304-9303-3eba7dd3f212.png)
=> Fix dash separator color in light theme

.github/workflows/build-ci.yaml, .github/workflows/build-deb.yaml
I had previously added a pre-job to cancel duplicated runs (#3695).
But we just need to add a better `on` condition.
=> Drop CI pre-job and fix 'on' condition

gnome-shell/src/gnome-shell-sass/_yaru-colors.scss
Revert the progress track color to pure accent, like before #3974 (https://github.com/ubuntu/yaru/pull/3974/files#diff-d2ffad6a03458277f589a156a75cd154971ba0a9f85fe2890159f703e6217597L101)
| | Before | After |
| --- | --- | --- |
| Light | ![image](https://github.com/ubuntu/yaru/assets/36476595/ab66a952-3565-4490-ad56-45cd24d844ac) | ![Capture d’écran du 2023-09-09 22-59-41](https://github.com/ubuntu/yaru/assets/36476595/de5738a2-a9e8-4a44-9c21-a731c89688ee) |
| Dark | ![Capture d’écran du 2023-09-09 22-49-36](https://github.com/ubuntu/yaru/assets/36476595/d569d787-a2e7-434d-bff6-b19d323dc18e) | ![Capture d’écran du 2023-09-09 22-59-21](https://github.com/ubuntu/yaru/assets/36476595/34b53717-0ce7-4c47-88dd-fec5423ebabd)
=> Revert progress color to pure accent

common/accent-colors.scss.in, gnome-shell/src/gnome-shell.scss.in, gnome-shell/src/meson.build
We did not generate the shell accent color loader files anymore causing the accent color not being used for color variants.
Avoid ending up in the same situation again by adding a sssc check at compile time.
LP: #2033688
Closes: #3978
=> gnome-shell: Ensure accent color is used in shell variants

debian/yaru-theme-gtk.install, gtksourceview/gtksourceview/meson.build
Test Case
-------
- Install Ubuntu 24.04 LTS. Choose the dark style option.
- After the install, install gedit (as a .deb)
- Run gedit
What Happens
---------------------
gedit's text area has major readable issues. When run from the command-line, this warning appears:
`Style scheme 'Yaru-dark' cannot be found, falling back to 'tango' default style scheme.`
Other Info
---------------
The gedit maintainer has forked gtksourceview to a new libgedit-gtksourceview library, ignoring advice from several that it was not ideal. Ubuntu 24.04 LTS has gedit 46 where that change has been made.
=> gtksourceview: Support gedit's forked library

gnome-shell/src/gnome-shell-sass/widgets/_login-lock.scss
Its parent `lockDialogGroup` has exactly the same background-color set in the same file. Giving them both the same wasted render time on overdraw, and caused multi-layer blending artifacts (slight flickering of the grey background) when the login dialog fades in/out.
While the flicker can also be fixed using `set_offscreen_redirect`, there's no point adding that overhead when the extra layer doesn't need to be painted. Removing it halves the average render time of the login animation.
Closes: #4048
Copied-from: https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/d09509b2cbce
=> gnome-shell: Don't give login-dialog another background-color

gnome-shell/src/gnome-shell-sass/_dock.scss
Some changes were required in the scss to make Dash to Dock compatible with Gnome Shell 46, while also keeping compatibility with Gnome Shell 45. These are those changes. This is the PR in DashToDock: https://github.com/micheleg/dash-to-dock/pull/2146
=> Update Yaru to new Dash-to-Dock code

gnome-shell/src/gnome-shell-sass/_dock.scss
There was a difference between the scss file from DashToDock and the current one in Yaru. This PR adds it.
=> Add extra changes from DashToDock

gnome-shell/src/gnome-shell-sass/_dock.scss
The apps view shows an extra rectangle in the icons when they are hovered by the cursor.
This patch fixes it (extracted from patch for gnome 46 for Dash to Dock).
=> Fix apps view

gnome-shell/src/gnome-shell-sass/_colors.scss, gnome-shell/src/gnome-shell-sass/_common.scss, gnome-shell/src/gnome-shell-sass/_dock.scss, gnome-shell/src/gnome-shell-sass/_yaru-colors.scss, gnome-shell/src/gnome-shell-sass/widgets/_calendar.scss, gnome-shell/src/gnome-shell-sass/widgets/_dash.scss, gnome-shell/src/gnome-shell-sass/widgets/_popovers.scss, gnome-shell/src/gnome-shell-sass/widgets/_quick-settings.scss, gnome-shell/src/gnome-shell-sass/widgets/_search-results.scss, gnome-shell/src/gnome-shell-sass/widgets/_workspace-thumbnails.scss
Various fixes as per latest testing:
- Tuned the dock icons highlights
- Fixed highlighting on search items
- Reduced the radius on datemenu to match quicksettings
=> Shell 46 fixes

gtksourceview/gtksourceview/dark.xml.in, gtksourceview/gtksourceview/default.xml.in
The `version` attribute was removed in `libgedit-gtksourceview` 299.2 https://gedit-technology.github.io/developer-docs/libgedit-gtksourceview-300/porting-guide-299-0-to-299-2.html
The same release also made the `kind` attribute mandatory
The underline-color attribute for style elements was apparently removed in 299.0.2, but the parser previously wasn't as strict https://github.com/gedit-technology/libgedit-gtksourceview/commit/4575db49b48b67c0898716995fbc4c68072873a6
=> gtksourceview: Add support for new libgedit-gtksourceview 299.2 xml scheme

gnome-shell/src/gnome-shell-sass/_common.scss, gnome-shell/src/gnome-shell-sass/widgets/_login-lock.scss, gnome-shell/upstream/theme/gnome-shell-sass/widgets/_login-lock.scss
=> gnome-shell: Webauth qrcode light theme fixes

gnome-shell/src/gnome-shell-sass/widgets/_login-lock.scss
This commit removes a part of the scss file, which causes the login entry field focus borders to not be themed correctly.
This part causes ".login-dialog" to be missing in front of ".login-dialog-prompt-entry:focus", which causes the theme to fall back to the default color. If that default color isn't the same as the currently selected Yaru theme color, they mismatch.
closes #4102
=> Remove an issue causing ".login-dialog-prompt-entry"

gnome-shell/src/gnome-shell-sass/widgets/_login-lock.scss
Before:
After:
LP: #2080321
UDENG-4490
=> gnome-shell: Use button style for auth dialog list items

CONTRIBUTING.md
This fixes a minor typo in the contributing guide to ensure clarity for contributors. The affected line is: "to verify that everyting is in place."
=> Fix typo: "everyting" to "everything" in documentation

debian/control
index.theme specifies `Inherits=Humanity`, so we should at least suggest having humanity-icon-theme installed.
=> debian: Suggest humanity-icon-theme

.github/lpbugtracker.py, .github/workflows/track-lp-issues.yaml
If it ends up in the debian sources we may share a pre-compiled binary that is not a good thing to do
=> ci: Install hub from sources instead of using a precompiled binary

.github/workflows/build-deb.yaml
No need to maintain ours anymore while the re-usable action can also do linting and sources generation
=> ci: Drop the in-house action to build deb files, reusing desktop team one

gnome-shell/src/gnome-shell-sass/_dock.scss
I noticed that the padding of the dock radii doesn't uniformly match the icon containers' radius 
**before**
**after**
**BEFORE**
**AFTER**
resolves #4225
=> fix: visual Correction on Ubuntu Dock Radius

gtk/src/default/gtk-4.0/_tweaks.scss
We were not overriding the case in which an image was child of an hovered or active parent, so do it properly now by handling such case as base theme does, so that we can fully override it.
LP: #2107388
=> gtk-4/tweaks: Actually override the default windowcontrols definition

icons/src/fullcolor/default/apps/workspace-switcher-left-bottom.svg, icons/src/fullcolor/default/apps/workspace-switcher-left-top.svg, icons/src/fullcolor/default/apps/workspace-switcher-right-bottom.svg
Those icons was rendered to the wrong destination file (`id="icon-name"` in SVG source), causing "Check rendered icon changes"  workflow to fail.
Related to: https://github.com/ubuntu/yaru/actions/runs/16900269814/job/49015137378?pr=4271
=> fix(icons): fix workscape-switcher-* icon-name in source file

icons/Yaru/scalable/status/lock-small-symbolic.svg, icons/Yaru/scalable/status/network-wireless-encrypted-symbolic.svg, icons/src/scalable/default/status/network-wireless-encrypted-symbolic.svg, icons/src/symlinks/symbolic/status.list
The network-wireless-encrypted-symbolic icon is not drawn correctly. According to the its css class it is supposed to be sized, $scalable_icon_size * 0.5 meaning the base icon is supposed to be 8x8 not 16x16 px . With the pixel fitted changed, the lock-small-symbolic is also transformed into a symlink syncing with network-wireless-encrypted-symbolic
I was supposed to just use the lock-small-symbolic icon but noticed that an outlined icon doesn't fit well in an 8x8 canvas
so I went and tried to pixel fit the original network-wireless-encrypted-symbolic.
**All in all**:
- Solved: lock icon for gnome-shell wifi indicator and gnome-control-center are now the same.
- the icon is already too small to be outlined so it was changed to be a filled icon.
**Before:**
**After:**
=> Chore: Improve and Sync Wi-Fi Encrypted Indicator Icons

gnome-shell/src/gnome-shell-sass/widgets/_dialogs.scss
Task:
|  before  |  after  |
|  --- | ---  |
| <img src=https://github.com/user-attachments/assets/1900d820-40e6-49d3-8bb3-d3482a672150 width=400/> | <img src=https://github.com/user-attachments/assets/963670bb-5ed2-4439-8568-2373b14ddd16 width=380/> |
|  before  |  after  |
|  --- | ---  |
| <img src=https://github.com/user-attachments/assets/4aa9d4cd-0c7b-4b29-b464-3c3aac15be61 width=390/> | <img src=https://github.com/user-attachments/assets/deae04a9-87fb-46d9-b309-8fc9a383db44 width=390/> |
|  before  |  after  |
|  --- | ---  |
| <img src=https://github.com/user-attachments/assets/e18afcbc-cb87-47a9-b794-ffdf70a35d77 width=390/> | <img src=https://github.com/user-attachments/assets/cc3c40ea-95ec-48b1-8862-7cd227f310e7 width=390/> |
I might retain the original border radius later on. …
=> Improve the Look of Gnome Shell Dialogs

gnome-shell/src/gnome-shell-sass/widgets/_login-lock.scss
before:
after:
followed 9 px radius of `entry` widget using `base_border_radius` + 6
=> adjusted radii of login entry. Initial commit

.github/workflows/build-ci.yaml, .github/workflows/open-pr-on-optimized-symbolic-icons-changes.yaml, .github/workflows/open-pr-on-rendered-icons-changed.yaml, .github/workflows/track-lp-issues.yaml
Speed up CI jobs by avoiding installation of locales and man pages.
The major performance gain that can be expected is that it makes the "Processing triggers for man-db" step a no-op. That step can otherwise take more than a minute, for example in [this recent run](https://github.com/ubuntu/yaru/actions/runs/17451766904/job/49557610398#step:4:104) it took 1m 51s:
UDENG-7865
=> ci: Avoid installing locales and man pages

gnome-shell/src/gnome-shell-sass/_yaru-colors.scss, gnome-shell/src/gnome-shell-sass/_yaru-default-colors.scss, gnome-shell/src/gnome-shell-sass/widgets/_osd.scss
In practice the shell only use the warning color, but optimize them all in case some extension relies on the other ones (yep, ubuntu-dock!)
Compare with original screenshots in #4320
Partially overrides #4320
=> gnome-shell: Optimize contrast for warning, success and destructive texts
